### PR TITLE
fix: improve default naming for canvassing households

### LINKED ISSUE #2550: Canvassing: Default household naming confusing
### The feature

Zetkin features a new tool for organizing so-called canvassing (visiting households for talking and distributing material). Canvassers are provided with a dedicated interface in which they can view and interact with areas and locations visualized on a map. 

The canvasser may add any amount of households on a location.

### The bug

When adding households one-by-one and not naming them they are all given the same default name.

## Steps to reproduce

1. Go to https://app.dev.zetkin.org/organize/1
2. Make sure you're signed in as `testadmin@example.com`
3. Click on **🗺 Geography** in the side menu
4. Draw an area (currently by clicking the DRAW button and putting a few points on screen) 
5. Click SAVE button to save the area.
6. Create a project from the top-right button
7. Create an area assignment from the "CREATE" button, call it `Household naming`
8. Click on maps tab in the newly created area assignment 
9. Use the map interface to locate and click on the area created in step 4
10. Type to find, and select the user `Angela Davis` in the **Add assignee dropdown**.
11. Click the top-right START ASSIGNMENT button
12. Go to https://app.dev.zetkin.org/my
13. Locate the **and tap** the `Household naming` area assignment (possibly filed under "Canvass" category)
14. Tap START ASSIGNMENT
15. Use the + button until the map is maximally zoomed in
16. Tap ADD LOCATION, name it, tap CREATE LOCATION
17. Use the appearing drawer UI to open the location details by tapping the element or its ߍ button
18. Tap HOUSEHOLDS button
19. Tap + ADD NEW HOUSEHOLD button
20. Go back to Households screen with the `<` back button
21. Tap + ADD NEW HOUSEHOLD again

### Expected Behaviour
- Name of the first household created is `Household 1` by default
- Name of the second household created is `Household 2` by default

### Actual Behaviour
- All households are named `Untitled household`

### PR DESCRIPTION
**Pull request by ajoensson**
## Description
This PR improves the default naming for canvassing households by giving them the title "Household X", where X counts up. This way, we avoid having multiple households with the same name. We also reuse the default household name used in the bulk-add-action, instead of having different default names based on how the household was added.

## Screenshots
image

It might be a bit counterintuitive that the households are seen in descending order, but that is because newly created households are added to the top of the list.

## Changes
* Reuse the `createMultiple.householdDefaultTitle` when adding single households as well
* Remove the (now) unused `default.household` message ID

## Related issues
Resolves #2550

### CODE REVIEW

File: src/features/canvass/components/LocationDialog/pages/HouseholdsPage.tsx [hunk 1]
```diff
@@ -124,9 +124,17 @@ const HouseholdsPage: FC<Props> = ({
...
-              const newlyAddedHousehold = await addHousehold({
-                title: messages.default.household(),
-              });
+
+              // Since this button adds households to the unknown floor, we only count those households
+              const householdsOnUnknownFloor = sortedHouseholds.filter(
+                ({ floor }) => floor == null
+              );
+              const title =
+                messages.households.createMultiple.householdDefaultTitle({
```
Comment (ziggabyte) [inline src/features/canvass/components/LocationDialog/pages/HouseholdsPage.tsx:133]: Maybe this message could be moved to a more general part of the households messages, since it is no longer only used for creating multiple?

**Review by ziggabyte — APPROVED** [review]
I played with it and like how it works, it feels like it makes sense and definitely improves the naming flow! 

I have one tiny comment that you can do something about if you're in a pedantic mood, but otherwise you can just ignore and we'll merge! :D

File: src/features/canvass/components/LocationDialog/pages/HouseholdsPage.tsx (hunk 1 above)
Comment (ajoensson) [reply src/features/canvass/components/LocationDialog/pages/HouseholdsPage.tsx]: Good idea! I fixed it now!

**Review by ziggabyte — APPROVED** [review]
Niiiice :D Let's merge it!
