### PR TITLE
My organizations page

### LINKED ISSUE #3379: Org Page: Shows Connect button even when connected
### The feature
A Zetkin instance is a piece of the Zetkin software running on a dedicated server with it's own domain. Lots of organizations can share the same Zetkin instance (as is the case with the zetk.in instance), and even for instances that are dedicated to a single partner organization, there can be lots sub-organizations.

Each (sub-) organization has it's own public page in the Zetkin web app, which most importantly shows the event calendar for that organization.

The organization page also has a "Connect" button, which allows any user to connect to that organization after creating a user account and logging in. Connecting means that you can sign up for the events, or be given assignments.

Once connected, it's possible to decide whether you want to _follow_ the organization or not. Following an organization means being able to see their events in your "All events" feed at /my/feed.

### The bug
The "Connect" button remains even after connecting. For already connected users, the button should be replaced with a follow/unfollow button (depending on current follow state).

## Steps to reproduce
This seems to be happening right now for the `testuser@example.com` account

1. Go to https://app.dev.zetkin.org/my
2. Sign in with `testuser@example.com` and `password`
3. Go to https://app.dev.zetkin.org/o/1

### Expected Behaviour
There should be a "Follow" or "Unfollow" button next to the organization title. Clicking the button should toggle whether the user follows the organization or not.

### Actual Behaviour
There is a "Connect" button next to the organization title. Clicking the button results in a HTTP error.

## Screenshots
The screenshot shows the conflicting state between the "Connect" button being incorrectly displayed in the UI on the left, and the fact that the API correctly returns the current organization (ID 1) as one of the organizations that the user is connected to and follows.

Image

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR adds a My organization page. I've had most of this code lying around for a while, but finished it now inspired by #3388.

In order to be able to reuse functionality elsewhere, I also had to make changes to `ZUIItemCard` and the `useMemberships` and `useUserMemberships` hooks, coincidentally fixing #3379 and superseding #3389 in the process.

## Screenshots
image

## Changes
* Refactors the severely overlapping `useUserMemberships()` and `useMemberships()` hooks
  * Renames the `useMemberships()` to `useOfficialMemberships()` to reflect the filtering
  * Moves filtering for official memberships to after loading, storing the full list in the store, which fixes #3379 
  * Replaces many uses of `useMemberships()` with `useUserMemberships()`
  * Gets get rid of duplicate state across the `user` and `organizations` store slices, instead reusing the same data
* Adds a new page at `/my/orgs` which lists all organizations that the user is connected to

## Notes to reviewer
Please help me double check that the hooks refactor did not break anything on the organizer side (officials settings page and organization switcher menu).

## Related issues
Main purpose of this PR is not documented
Resolves #3379

### CODE REVIEW

File: src/app/my/layout.tsx [hunk 1]
```diff
@@ -25,6 +25,8 @@ export async function generateMetadata(): Promise<Metadata> {
     pageTitle = messages.tabs.home();
   } else if (lastSegment === 'settings') {
     pageTitle = messages.tabs.settings();
+  } else if (lastSegment === 'orgs') {
+    pageTitle = messages.tabs.orgs();
   }
```
Comment (laurablum) [inline src/app/my/layout.tsx]: Should we consider using a `switch case` statement here? Or maybe having a 
```js
pageTitle = messages.tabs.[lastSegment]?.()
```

could be an option too, although I don't think this makes things easier/more readable

File: src/features/home/hooks/useUserMemberships.ts [hunk 2]
```diff
@@ -1,14 +1,19 @@
...
   const apiClient = useApiClient();
-  const list = useAppSelector((state) => state.user.membershipList);
+  const list = useAppSelector(
+    (state) => state.organizations.userMembershipList
+  );
   return useRemoteList(list, {
-    actionOnLoad: () => membershipsLoad(),
-    actionOnSuccess: (data) => membershipsLoaded(data),
+    actionOnLoad: () => userMembershipsLoad(),
+    actionOnSuccess: (data) => userMembershipsLoaded(data),
```
Comment (laurablum) [inline src/features/home/hooks/useUserMemberships.ts]:
```suggestion
    actionOnLoad: userMembershipsLoad,
    actionOnSuccess: userMembershipsLoaded,
```

Comment (richardolsson) [reply src/features/home/hooks/useUserMemberships.ts]: I see what you're doing here, and I think I understand why, but I actually do not think that this is an improvement. This ties the interface of `userMembershipsLoad` with the interface of `actionOnLoad`, which are not guaranteed to stay compatible. It's not a big difference in this case, but I see no reason to make a change unless you think it's very important and could help me understand why.

I elaborated on this general matter in [another comment](https://github.com/zetkin/app.zetkin.org/pull/2677#discussion_r2069861305) on a PR once.
