### PR TITLE
Issue 1930/smart search min matching tags

### LINKED ISSUE #1930: Smart search: Cannot select number in "at least" option in tags filter
## Description
I can't seem to select a number in the number selector in the tags filter, when selecting "at least" version of the filter. 

## Steps to reproduce
1. Go to somewhere with a smart search dialog
2. Select to add/remove people, and select "Based on tags"
3. Select "at least" from the dropdown
4. Attempt to edit the number 

### Expected Behaviour
I can edit the number either from clicking the field and then using the keyboard for deleting the existing number and typing in a new one, or by using the little up/down arrow buttons to increase or decrease the number

### Actual Behaviour
I cannot use the up/down arrow buttons, and when I attempt to delete the existing number to type in a new one, the filter changes and I cannot change back to the "at least" version. 

## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/58265097/9c6f1a4e-2edd-4882-8733-b1ff1f6515ff

### PR DESCRIPTION
**Pull request by awarn**
## Description
Fixes two issues with SmartSearch form for matching tags when setting the number of tags to match "at least".

Note that the filter being specified does not seem to work correctly. Regardless of number of tags set to match against, it still seems to behave as the "any" variant of the filter.

## Changes
- The upper bound of the number is now set by the number of _selectable_ tags, not the number of _selected_.
- Allows the number input to be empty (so you can delete it using a keyboard) without the form resetting to the match "any" variant.

## Related issues
Resolves #1930

### CODE REVIEW

File: src/features/smartSearch/components/filters/PersonTags/index.tsx [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { FormEvent } from 'react';
+import { FormEvent, useState } from 'react';
 import { Box, Chip, MenuItem } from '@mui/material';
```
Comment (kaulfield23) [inline src/features/smartSearch/components/filters/PersonTags/index.tsx:2]: This causes the lint error

File: src/features/smartSearch/components/filters/PersonTags/index.tsx [hunk 2]
```diff
@@ -51,6 +51,10 @@ const PersonTags = ({
       tags: [],
     });
 
+  const [selected, setSelected] = useState<CONDITION_OPERATOR | 'min_matching'>(
+    filter.config.condition
```
Comment (kaulfield23) [inline src/features/smartSearch/components/filters/PersonTags/index.tsx:55]: The reason the condition is 'any' when editing is that `min_matching` also has the condition 'any'. The key to differentiating between 'any' and 'at least' is the presence of `min_matching`. It would look like this:
- at least : {condition:'any', min_matching:1}
- any : {condition:'any', min_matching:undefined}

**Review by kaulfield23 — DISMISSED** [review]
Nice! Now I can give input using keyboard as well! 😄but I found something to be fixed in codes!

**Comment by kaulfield23** [comment]
I think it should limit the maximum number, otherwise the sentence can be like this 
image
Which looks weird to me

**Comment by awarn** [comment]
The problem is that I can't think of a smart way of explaining the upper limit to the user, and the lack of that is what caused part of the bug report in #1930 to start with. You can't go from left to right - "Add", "at least", [number], [tags...] - you have to go - "Add", "at least", [tags...], [number]. We would have to add some extra note, or rearrange the sentence.

File: src/features/smartSearch/components/filters/PersonTags/index.tsx (hunk 1 above)
Comment (awarn) [reply src/features/smartSearch/components/filters/PersonTags/index.tsx:2]: I'll resolve this, no problem! Don't know why my own linting hook did not catch it.

**Comment by kaulfield23** [comment]
Could you also add this logic to `src\features\smartSearch\components\filters\Journey\index.tsx` when you continue to work on  this? Since journey smart search filter copied the same logic from personTag, it has the same bug.

**Comment by awarn** [comment]
Finally have this in order, I think. Apparently I had some code from July I never properly committed...

**Review by richardolsson — APPROVED** [review]
Nice work on this, everyone involved, and especially @awarn with all the research and trial and error that you've done to both define the bug more clearly and fix it! I think this is ready to merge now. 😊 

I realize that this PR does not "fix" the matter of the max bounds on the number field, but I also don't think that's a huge problem. I do appreciate that it can confuse users, and I think your analysis @awarn of not being able to fill out the fields from left to right raises a reasonable concern.

However, that problem does not have a very simple solution. I think personally the best way to deal with it would be some sort of validation that prevents the filter from being saved until all the fields have been properly filled out. That is possible, but I think it can be considered outside the scope of this PR.

If you want to take a look at the Journeys one as well please do, but I couldn't actually reproduce the issue there. Maybe I'm just doing it wrong. 😊
