### PR TITLE
issue-1687/sorted orgs in menu

### LINKED ISSUE #1687: Organizations not sorted in menu
## Description
In the organization switcher in the left hand side nav menu, the organizations are arbitrarily sorted (seemingly based on when they were created, i.e. their numerical IDs). I think they should be sorted alphabetically.

## Steps to reproduce
1. Go to localhost:3000/organize/1
2. Expand the menu
3. Click on the downward chevron to open the organization list

### Expected Behaviour
Organiations should be sorted alphabetically

### Actual Behaviour
Organizations are arbitrarily sorted

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR sorts organizations alphabetically in menu 

## Screenshots
image

## Changes

* Adds `useMemo` and sort list

## Notes to reviewer
used `useMemo` to prevent the sorting from being triggered every time user moves a cursor to the sidebar.

## Related issues
Resolves #1687

### CODE REVIEW

File: src/features/organizations/components/OrganizationTree.tsx [hunk 1]
```diff
@@ -53,6 +54,10 @@ function OrganizationTree({
   orgId,
 }: OrganizationTreeProps): JSX.Element {
   const theme = useTheme();
+  const sortedTreeItems = useMemo(() => {
+    const sorted = treeItemData.sort((a, b) => a.title.localeCompare(b.title));
+    return sorted;
+  }, [treeItemData.length]);
```
Comment (richardolsson) [inline src/features/organizations/components/OrganizationTree.tsx:60]: Correct me if I'm wrong, but I believe this only sorts the top-level, which is not enough. We also want to sort the children of each organization, and all of the children of those children, etc.

**Review by richardolsson — CHANGES_REQUESTED** [review]

File: src/features/organizations/components/OrganizationTree.tsx (hunk 1 above)
Comment (kaulfield23) [reply src/features/organizations/components/OrganizationTree.tsx:60]: Aaaah yeah you are right. I will add more logic to it!

Comment (richardolsson) [reply src/features/organizations/components/OrganizationTree.tsx:60]: I believe the best solution would be to handle the sorting in the rendering of each "level", rather than here in the top-level.

File: src/features/organizations/components/OrganizationTree.tsx [hunk 2]
```diff
@@ -16,7 +16,11 @@ interface OrganizationTreeProps {
 
 function renderTree(props: OrganizationTreeProps): React.ReactNode {
   const { treeItemData, orgId, onSwitchOrg } = props;
-  return treeItemData.map((item) => (
+  const sortedTreeItem = [...treeItemData].sort((a, b) =>
```
Comment (richardolsson) [inline src/features/organizations/components/OrganizationTree.tsx:19]: I think this variable name should be plural, to indicate that it's a list/array of items, i.e. `sortedTreeItems`.

**Review by richardolsson — APPROVED** [review]
Nice work! The code looks mostly good and I have verified that it works as expected. You can decide if you want to merge or change the variable name issue I've pointed out below.

I foresee this code being refactored in the near future, so you don't have to fix the problem below if you struggle to find the time for it.

**Review by richardolsson — APPROVED** [review]
LGTM!
