### PR TITLE
Issue #3548/multishifteventsfromcreatebutton

### LINKED ISSUE #3548: {Feature}:Missing option to create Multishift events from "Create" button
## Description

When creating a new event there is no option to create a multishift event directly.  
The multishift event can only be created by dragging the mouse within the calendar.

### The feature

The Multishift event is an event that contains multiple shifts that can be individually planned. 

### The bug

-

## Steps to reproduce
Option 1 (Via Projects -> Create)
1. Go to https://app.dev.zetkin.org/organize/1/projects/464
2. Click on 'Create' on the top right

Option 2 (within the event creation)
1. Go to https://app.dev.zetkin.org/organize/1/projects/447/events/614

### Expected Behaviour

Allow to create multishift events from within the single event. Or allow to create a multishift event from the 'Create' Button within a project

### Actual Behaviour

Multishift events can only be created by dragging with the mouse in the calendar.

## Screenshots

Image
Selection to create new events

Image
View from within the Event creation

### PR DESCRIPTION
**Pull request by verpeccatum**
## Description
This PR adds a multishiftevent option under the create button for projects. 

## Screenshots
[Add screenshots here]
New Option for multishift
image
configuration of mutlishiftevent
image

1 Event named Hello with three shifts from 14:00 - 14:20, 14:20-14:40, 14:40-15:00
image

## Changes

* Adds new option to create a multishift event from the 'Create' Button within a project
* Changes  adds createMultiShiftEvent to createButton, 
   handleCreateEvent is now split into to functions handleCreateEvent about 10 lines down and the defaultstart/defaultEnd logic ist done by getDefaultEventDates.

## Related issues
Resolves #3548

### CODE REVIEW

**Comment by sefsh** [comment]
Hi verpeccatum, I think it's the first time I've seen you around. Welcome to Zetkin! This is a great addition for easier access to and exposure of the multi-shift even creation utility. I've a few points that can improve the UX a bit more:
- Because multi-shift events and single events are closely related I propose that its menu item is moved underneath "Events" in the creation menu:
  Group 24
- Let's also use the same text as in its creation modal: 
  `Multishiftevent` → `Multi-shift event`
- When a single event is created the user is taken to its page immediately, which is obviously a strong feedback to the user that the user action was successful. The flow of creating multi-shift events from the menu as introduced in this PR introduces a problem of user feedback, which will vary greatly depending on where in the app the user is currently located when creating a multi-shift event:
  - Project overview:  Feedback through "Upcoming events" section if the new m-s events is within scope of the current week
  - Calendar: Feedback if the m-s event is within current time scope of day, week or month
  - Activities tab: Feedback if the events are within scope of filters (not the default)

  All variations considered I think there needs to be a universal feedback mechanism to ensure the user that the creation was successful, regardless of current app location. I propose the use of the so-called [snackbar component](https://mui.com/material-ui/react-snackbar/) to guarantee feedback visibility:
  image
  If you want a reference for how to add a snackbar component, you can steal it from the delete [join forms](https://app.dev.zetkin.org/organize/1/people/joinforms) action.

Please let me know if you've any questions, at all!

File: src/features/campaigns/components/CampaignActionButtons.tsx [hunk 1]
```diff
@@ -273,6 +291,16 @@ const CampaignActionButtons: React.FunctionComponent<
...
         />
       </ZUIDialog>
+      {shiftModalDates && (
+        <EventShiftModal
+          close={() => {
+            setShiftModalOpen(false);
+            setShiftModalDates(null);
+          }}
+          dates={shiftModalDates}
+          open={shiftModalOpen}
```
Comment (ziggabyte) [inline src/features/campaigns/components/CampaignActionButtons.tsx]: Could this be refactored to use `!!shiftModalDates` as the condition for if the modal is open, and then the `shiftModalOpen` state would not be needed?

File: src/features/campaigns/components/CampaignActionButtons.tsx [hunk 2]
```diff
@@ -273,6 +291,16 @@ const CampaignActionButtons: React.FunctionComponent<
           }}
         />
       </ZUIDialog>
+      {shiftModalDates && (
```
Comment (ziggabyte) [inline src/features/campaigns/components/CampaignActionButtons.tsx]: If we use the `shiftModalDates` to determine if the modal is open or not, then it's not neccessary to also conditionally render it, because there is no risk of mis-match between the states :)

**Review by ziggabyte — CHANGES_REQUESTED** [review]
I think the code is pretty much there, I have a suggestion for a simplification of how to handle the open state of the modal, that's my reason to request for change :) 

If @sefsh approves of the look and then this is updated, we're ready to rock n roll! 

also, i see that the linting is failing in CI. I'd suggest pulling down main and make sure linting passes locally before pushing up the changes (unless you use the pre-commit hook, in that case you will not be able to make commits if linting does not pass )

**Comment by sefsh** [comment]
No Vercel deploy available but I managed to run the changes locally. I think it's fine.

**Comment by verpeccatum** [comment]
@sefsh @ziggabyte thank you guys
I will fix the modals and linter asap

**Review by ziggabyte — APPROVED** [review]
I think this looks and works great now! Well done, happy to have this as part of the platform :D 

Approve!
