### PR TITLE
Remove margin under email write-only alert

### LINKED ISSUE #2154: Email: Redundant margin for sent emails
## Description
After an email has been sent, there is a blue information bar over the editor letting the user know that the email is in read-only mode. The bar has a redundant margin underneith, which 

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects and log in if necessary
3. Go to any project (or create a new one)
4. Create an email
5. Define any targeting and lock the targets
6. Add some content under "Compose" and add a subject line under "Settings"
7. Click "Delivery" and schedule email for tomorrow
8. Go to Compose tab

### Expected Behaviour
There should be a blue banner immediately between the tab bar and the editor UI, letting you know that the email has been scheduled for delivery.

### Actual Behaviour
There is a blue banner, but there is a margin underneath it.

### Example 1
image

### Example 2
The extra margin is more obvious here where there's a background color on the email.
image

### PR DESCRIPTION
**Pull request by ZebastianBjorkqvist**
## Description
This PR removes the margin under the write-only alarm when scheduling an email.

## Screenshots
image

## Changes

* Removes margin

## Notes to reviewer
None

## Related issues
Resolves #2154

### CODE REVIEW

File: src/features/emails/components/EmailEditor/index.tsx [hunk 1]
```diff
@@ -61,7 +61,7 @@ const EmailEditor: FC<EmailEditorProps> = ({ email, onSave }) => {
   return (
     <Box display="flex" flexDirection="column" height="100%">
       {readOnly && (
-        <Alert severity="info" sx={{ marginBottom: 2 }}>
```
Comment (richardolsson) [inline src/features/emails/components/EmailEditor/index.tsx:64]: Just as an FYI (and an opportunity to learn something): In MUI there is a shorthand for `marginBottom` called `mb`. The same is of course true for all other directions (e.g. `mr` for right). There's also `mx` and `my` for horizontal (both left and right) and vertical (both top and bottom) respectively.

**Review by richardolsson — APPROVED** [review]
Great work! This has bothered me for a long time so I will be happy to see this in place. 🙌 

I have reviewed the code and I have tried the preview build to make sure that the PR fixes the problem. I also left a comment below, but only as an FYI because I want to give back something small as a thank you for taking the time and fixing this issue. 🙏 

Let's merge! 🟢
