### PR TITLE
Value tags in data grids

### LINKED ISSUE #1474: How to display value tag in view when there is no value
## description
Currently, if you add a value tag to a person and then display a column for this tag in a view, you don't see if the person has the tag unless it has a value.  

## Questions
Should we allow empty value tags? if yes - differentiate, if no - stop it. Needs design and research.

### Step by step reproduction
- Add a value tag to a person, without giving it a value
- Create a view with the person in it.
- Add a column for the value tag. 

### Expected behaviour
I can see if the person has the tag. If the tag has text, I see the extra text. I can add and remove the tag, and I can add and remove the extra text.

### Actual behaviour
I can’t see if the person has a tag. If the tag has value, I see the value.

### LINKED ISSUE #1475: Cannot add value tag via view column
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
It is currently not possible to add a value tag with a value to a person via a value tag column in a view.

## Steps to reproduce
- create a view
- add a column to display a value tag
- click a person that does not have the tag, in the column for the tag, to add the tag to the person

### Expected Behaviour
To get a dialog where i can add a value to the value tag

### Actual Behaviour
The value tag is added to the person without a value

### LINKED ISSUE #1476: Cannot remove a value tag via a view column
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
It is currently not possible to remove a value tag from a person via a value tag column in a view.

## Steps to reproduce
- Add a value tag to a person
- Create a view
- Add a column to display the tag
- Click the tag to remove it from the person

### Expected Behaviour
To get a warning dialog asking if i want to remove the value tag, and that this is an action that cannot be reversed

### Actual Behaviour
Nothing happens. I cannot remove a value tag this way.

### LINKED ISSUE #1477: Hard to read long values in view value tag column
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
If you have a long value added to a value tag, it displays weirdly in a value tag view column.

## Questions
Info needed - what is the problem? Is this a problem? What is the limit for how long values? How do we display this? What is the context when you want/need to save long values?

## Steps to reproduce
- Add a value tag to a person, and add a long value
- Create a view and add the person
- Put in a column to display the value tag

### Expected Behaviour
To be able to see the full content of the value tag value. Alternatively, to see the beginning of the value, left adjusted. Possibly be able to adjust line breaks. 

### Actual Behaviour
I can see part of the value, but only the middle, as it is centered.

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR solves a bunch of problems related to value tags in data grids (like lists and journeys overview page)

## Screenshots
bild

## Changes
* Renders cell value in a colored box, that has the color of the tag
* Shows if the value of the tag is empty, aka is an empty string or `null`
* Adds functionality to update value of the value tag, in a list
* Truncates long texts for better visibility
* Makes it possible to remove a value tag in a list
* Makes it possible to add a value tag in a list

## Related issues
Resolves #1474 
Resolves #1475 
Resolves #1476 
Resolves #1477

### CODE REVIEW

File: src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx [hunk 1]
```diff
@@ -0,0 +1,270 @@
...
+
+interface CellProps {
+  cellValue: ZetkinTag | undefined;
+  personId: number;
+  tag: ZetkinTag | null;
+}
+
+const Cell: FC<CellProps> = ({ cellValue, personId, tag }) => {
+  if (!tag) {
+    return null;
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx:134]: This breaks "restricted view", because a user with which a list has been shared, who is not an official, won't be able to load the tags standalone. So the cells render nothing.

In restricted mode, the list will never be editable, so just rendering the cells where a tag exists should be fine, and getting the value type from the tag in the row should be fine. See my next comment.

image

File: src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx [hunk 2]
```diff
@@ -0,0 +1,270 @@
...
+    const tagItem = tagList.items.find((item) => item.id == tagId);
+
+    const tagFuture = loadItemIfNecessary(tagItem, dispatch, {
+      actionOnLoad: () => tagLoad(tagId),
+      actionOnSuccess: (tag) => tagLoaded(tag),
+      loader: () =>
+        apiClient.get<ZetkinTag>(`/api/orgs/${orgId}/people/tags/${tagId}`),
+    });
+
+    const tag = tagFuture.data;
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx:60]: Maybe this could be made conditional to only happen when list is not in restricted mode (e.g. based on `accessLevel`) and in restricted mode, the `tag` variable can just be `null` here.

File: src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx [hunk 3]
```diff
@@ -0,0 +1,270 @@
...
+
+    return {
+      align: 'center',
+      editable: !accessLevel && tag?.value_type !== null,
+      headerAlign: 'center',
+      renderCell: (params: GridRenderCellParams<ZetkinViewRow, ZetkinTag>) => (
+        <Cell cellValue={params.value} personId={params.row.id} tag={tag} />
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx:67]: Maybe this (combined with the other comments I've made above)?

```suggestion
        <Cell cellValue={params.value} personId={params.row.id} tag={tag || params.value} />
```

**Review by richardolsson — CHANGES_REQUESTED** [review]
I've looked at the code and the preview build and I think it looks really good. I did find a bug in "restricted mode" however, i.e. when a list is shared with an otherwise unprivileged user. It's a regression so I think it needs to be fixed before merging. See details below.

File: src/features/views/l10n/messageIds.ts [hunk 4]
```diff
@@ -55,6 +55,9 @@ export default makeMessages('feat.views', {
         '{count, plural, =1 {1 solved issue} other {# solved issues}}'
       ),
     },
+    personTag: {
+      emptyValue: m('Empty value'),
```
[the remark this answers is not in the document]
Comment (ziggabyte) [reply src/features/views/l10n/messageIds.ts:59]: I thought about it, went with this, but yes agree it might not be The One. Thought about both "Empty tag" and "No value". Other potential candidates in my head: "No value added", "No value yet".

File: src/features/journeys/l10n/messageIds.ts [hunk 5]
```diff
@@ -79,6 +79,7 @@ export default makeMessages('feat.journeys', {
       title: m('Title'),
       updated: m('Last updated'),
     },
+    emptyValueTag: m('Empty value'),
```
[the remark this answers is not in the document]
Comment (ziggabyte) [reply src/features/journeys/l10n/messageIds.ts:82]: Thank you for catching this!

File: src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx (hunk 1 above)
Comment (ziggabyte) [reply src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx:134]: I completely forgot to test this usecase!! Thank you for catching it! :D

File: src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx [hunk 6]
```diff
@@ -57,14 +57,18 @@ export default class PersonTagColumnType implements IColumnType {
         apiClient.get<ZetkinTag>(`/api/orgs/${orgId}/people/tags/${tagId}`),
     });
 
-    const tag = tagFuture.data;
+    const tag = !accessLevel ? tagFuture.data : null;
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx:60]: I think the `loadItemIfNecessary()` party should also be conditional, so that we don't try to load something that we know that we won't be able to retrieve (and also won't use).

**Review by richardolsson — CHANGES_REQUESTED** [review]
Making good progress! I will do a better review of this tomorrow, but for now I just had one minor thing that I'd like for you to take a look at. Let me know if you disagree!

File: src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx (hunk 6 above)
Comment (ziggabyte) [reply src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType/index.tsx:60]: Makes perfect sense :)

**Review by richardolsson — APPROVED** [review]
This seems to be working perfectly fine now. Nice work! 💯
