### PR TITLE
issue-1849/contact-assign-error

### LINKED ISSUE #1849: Runtime error when adding or removing contact person for event after refreshing page
## Description
When adding or removing a contact person after refreshing an event page it triggers a unhandled runtime error in store.ts

## Steps to reproduce
1. Go to any Event Page.
2. Go to Participants.
3. Refresh the page.
4. Click on 'Select a contact person'
5. Search for a person to add and add that person.
6. Error
7. Refresh page again. (Contact person has been added)
8. Remove the contact person
9. Error
10. Refresh page. (Contact person has been removed)

### Expected Behaviour
Adding or removing the contact person should be performed without triggering an error.

### Actual Behaviour
Adding or removing a contact person triggers an error and performs the action.

## Screenshots (if you have any)
image
image

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR fixes an error where assigning / removing contact triggers run time error

## Changes

* Changes `eventLoaded` reducer - Adds a single event to `eventsByCampaignId` before `eventUpdated` action.

## Related issues
Resolves #1849

### CODE REVIEW

File: src/features/events/hooks/useEventMutations.ts [hunk 1]
```diff
@@ -83,6 +83,7 @@ export default function useEventMutations(
     apiClient
       .patch<ZetkinEvent>(`/api/orgs/${orgId}/actions/${eventId}`, data)
       .then((event) => {
+        dispatch(eventLoaded(event));
```
Comment (richardolsson) [inline src/features/events/hooks/useEventMutations.ts:86]: This action "lies" to the store by saying an event was loaded, when in fact it was just updated.

File: src/features/events/store.ts [hunk 2]
```diff
@@ -166,6 +166,26 @@ const eventsSlice = createSlice({
...
+
+        const eventItem = state.eventsByCampaignId[
+          event.campaign.id
+        ].items.find((item) => item.id == event.id);
+        if (eventItem) {
+          eventItem.data = { ...eventItem.data, ...event };
+          eventItem.mutating = [];
+        }
+        state.eventsByCampaignId[event.campaign!.id].loaded =
+          new Date().toISOString();
```
Comment (richardolsson) [inline src/features/events/store.ts:187]: This is problematic because it's lying and saying that the full list for this campaign has loaded, when that's not the case. Just a single event has loaded, and if some part of the UI requests this list in the future, it needs to load in full. Currently, it would not loaded (because `shouldLoad()` thinks it's already loaded) and it would look in the UI like the campaign has just a single event.

File: src/features/events/store.ts [hunk 3]
```diff
@@ -166,6 +166,26 @@ const eventsSlice = createSlice({
...
+        }
+
+        const eventItem = state.eventsByCampaignId[
+          event.campaign.id
+        ].items.find((item) => item.id == event.id);
+        if (eventItem) {
+          eventItem.data = { ...eventItem.data, ...event };
+          eventItem.mutating = [];
+        }
+        state.eventsByCampaignId[event.campaign!.id].loaded =
```
Comment (richardolsson) [inline src/features/events/store.ts:186]: You're using `event.campaign!` with the non-null assertion operator (`!`). I don't like that, because it means you're telling typescript you know better than typescript, which may or may not be true.

It's probably true that you know better than typescript in this place, right now (because you did an if statement on line 170 that should mean that `event.campaign` is not null). But what happens if some other coder in the future comes and changes that if statement on line 170, so that `event.campaign` no longer guaranteed to be non-null here on line 186? The code would start crashing.

It's better to not rely on "tricking" typescript. That will make the code more reliable long-term.

In this case, the reason why typescript is telling you that `event.campaign` might be `null` is because it's being careful. The `event.campaign` expression is not constant. It could change. In this case, Typescript is being _too_ careful, because I can tell from looking at the code that it could never have changed between line 170 and here. 

But Typescript is being careful because javascript control flow can be difficult to follow. Functions can change variables outside the functions, and there can be multiple levels of closures that are difficult for Typescript to follow. So typescript will act like this unles you store the value in a constant variable that typescript knows won't change.

In this case, change line 169 to do `const campaign = event.campaign`, and use `campaign` both in the if statement on line 170 and here on line 186 and everywhere else in this function.

**Review by richardolsson — CHANGES_REQUESTED** [review]
This works, but I don't really like it because it makes it the responsibility of the this hook to know what the store reducers do (and don't do). The action (`eventUpdated()`) should just be dispatched to indicate what _happened_, not as a way of saying to the store "hey do this". The store reducers should then take necessary steps to update the store state accordingly.

This bug exists because the store is not taking those steps for all actions that relate to loading events. The correct fix would be to make sure that all reducers that respond to such actions add the events to all places:

* The general event list (`state.eventList`)
* The by-date lookup table (`state.eventsByDate`)
* The by-campaign lookup table (`state.eventsByCampaignId`)

This should happen for all relevant actions, which means to me it makes sense to create a function that can be reused in all of those reducers. I would design it so that it has a signature along the lines of `function addEventToState(state, events: ZetkinEvent[]) : void`.

You can take inspiration from the way I've used a reusable function for updating cells in a view both when tagging and untagging a person:

https://github.com/zetkin/app.zetkin.org/blob/a0390b216074643c20d98eb8ad10fb4a0d6362d6/src/features/views/store.ts#L52-L55

File: src/features/events/store.ts (hunk 3 above)
Comment (kaulfield23) [reply src/features/events/store.ts]: Really weird behavior of typescript.. Thank you so much for the explanation!

File: src/features/events/hooks/useEventMutations.ts (hunk 1 above)
Comment (ziggabyte) [reply src/features/events/hooks/useEventMutations.ts:86]: @kaulfield23 I interpret @richardolsson 's comment here to mean that line 86 should be removed or refactored, but it is still here. Is this conscious or just missed?

File: src/features/events/store.ts [hunk 4]
```diff
@@ -578,6 +483,58 @@ const eventsSlice = createSlice({
   },
 });
 
+function addEventToState(state: EventsStoreSlice, events: ZetkinEvent[]) {
```
Comment (ziggabyte) [inline src/features/events/store.ts:486]: Very handy to have this function here, so we know for sure that all the right things are done every time an event needst to be added to the state :)

**Review by ziggabyte — COMMENTED** [review]
I'm putting this as a comment because I asked a question in one of the comments and depending on the answer to that question, i can either approve or ask for changes :)

File: src/features/events/store.ts (hunk 4 above)
Comment (kaulfield23) [reply src/features/events/store.ts:486]: Thank you for pointing out the redundant code!

**Review by richardolsson — APPROVED** [review]

**Comment by richardolsson** [comment]
Nice work @kaulfield23! Feel free to merge. 🟢
