### PR TITLE
Issue-1255/Local person tooltip

### LINKED ISSUE #1255: No way to see full name in `local_person` columns
## Description
A user should be able to see the full name of a person who has been "assigned" a certain row in a view using the `local_person`. Currently there is no way to see it except by editing the cell.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "Create view"
3. In the new view, click "New column" and add a "Assigned person" column
4. Add at least one person to the view, e.g. "Jane Doe"
5. In the "Assignee" column, on the "Jane Doe" row, double click the cell and type in "Jane" to assign Jane
6. Hover the "JD" avatar

### Expected Behaviour
Display the name in a tooltip

### Actual Behaviour
Nothing happens

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by djbusstop**
## Description
This PR displays a tooltip when hovering a person in Views and on the Survey Results. When there is no one assigned, then nothing is displayed on hover.

## Changes
* Adds forwarded ref to `ZUIAvatar` so that it can take a Tooltip
* `ZUIPersonGridCell` now takes a subset of `ZetkinPerson` in order to render the tooltip with the person's name
  * Changes props where this is used 
* Tooltip is an optional prop. It's enabled by default.

## Notes to reviewer
Check it out here
* [Views](http://localhost:3000/organize/7/people/views/8)
* [Surveys](http://localhost:3000/organize/7/projects/standalone/surveys/15/submissions)

## Related issues
Resolves #1255

### CODE REVIEW

**Comment by richardolsson** [comment]
Here is a survey with submissions. There is already a person hover card implemented there, so the tooltip kinda collides with it. I wonder if we should try to use the same approach on both? 

http://localhost:3000/organize/7/projects/standalone/surveys/15/submissions

**Comment by djbusstop** [comment]
@richardolsson What I did was add a new property `tooltip` to the `PersonGridCell` which is default to true, but turned off in the survey submissions list.

File: src/features/surveys/components/SurveySubmissionsList.tsx [hunk 1]
```diff
@@ -141,10 +141,14 @@ const SurveySubmissionsList = ({
         >
           <ZUIPersonGridCell
             onClick={startEditing}
-            personId={row.respondent.id}
+            person={{
+              ...row.respondent,
+              id: row.respondent.id, // Telling typescript that there is an id
```
Comment (richardolsson) [inline src/features/surveys/components/SurveySubmissionsList.tsx:146]: Typescript be typescript!

**Review by richardolsson — APPROVED** [review]
Sure That sounds like a good solution, at least for now. The R42 cycle will be the big "UX harmonization cycle" and there we will hopefully figure out a pattern that works for all of these scenarios, maybe it's this one!
