### PR TITLE
Visual changes to Remind All button for events

### LINKED ISSUE #1482: No visual indication of what's happening after clicking Remind all
## Description
When clicking Remind all in an event, nothing happens for a long time while the server is busy sending emails.

## Steps to reproduce
1. Go to an event with participants
2. Click on Remind all
3. Wait for operation to succeed

### Expected Behaviour
Some visual indication that the server is currently processing the request.

### Actual Behaviour
No visual indication. Nothing happens for several seconds until the client receives a response from the server.

### PR DESCRIPTION
**Pull request by MattettaM**
## Description
This PR adds a Loading Spinner to the Remind All button while the server is sending reminder e-mails. The button remains displayed after the e-mails have been sent and is disabled. If no contact person is assigned the icon is now an exclamation mark instead of a tick.

## Screenshots
image
image
image
image

## Changes
* Adds Loading Spinner while waiting for response that participants have been notified.
* Adds Reminding events to the store to use for when to display the spinner.
* Changes the button to be disabled when sending reminders.
* Changes the icon for no contact person having been assigned
* Changes the button to remain visible after participants having been reminded

## Notes to reviewer
Create or view an Event. Note the icon when no contact person is assigned.
Assign (many) participants to the event. Note the button being clickable and having the icon changed.
Click Remind All. Note the spinner appearing inside the button. Note the button being disabled.
Wait until response. Not icon being changed back to a check mark when done.

## Related issues
Resolves #1482

### CODE REVIEW

File: src/features/events/store.ts [hunk 1]
```diff
@@ -60,6 +60,7 @@ export interface EventsStoreSlice {
   };
   locationList: RemoteList<ZetkinLocation>;
   participantsByEventId: Record<number, RemoteList<ZetkinEventParticipant>>;
+  remindingByParticipantId: Record<number, boolean>;
```
Comment (richardolsson) [inline src/features/events/store.ts:63]:
```suggestion
  remindingByEventId: Record<number, boolean>;
```

File: src/features/events/store.ts [hunk 2]
```diff
@@ -488,8 +490,20 @@ const eventsSlice = createSlice({
...
       state.participantsByEventId[eventId].loaded = new Date().toISOString();
     },
-    participantsReminded: (state, action: PayloadAction<number>) => {
-      const eventId = action.payload;
+    participantsRemind: (state, action: PayloadAction<number[]>) => {
+      const participantIds = action.payload;
+      participantIds.forEach((participantId) => {
+        state.remindingByParticipantId[participantId] = true;
+      });
+    },
```
Comment (richardolsson) [inline src/features/events/store.ts:498]:
```suggestion
    participantsRemind: (state, action: PayloadAction<number>) => {
      const eventId = action.payload;
      state.remindingByEventId[eventId] = true;
    },
```

File: src/features/events/store.ts [hunk 3]
```diff
@@ -488,8 +490,20 @@ const eventsSlice = createSlice({
...
+    participantsReminded: (
+      state,
+      action: PayloadAction<[number, number[]]>
+    ) => {
+      const [eventId, participantIds] = action.payload;
+      participantIds.forEach((participantId) => {
+        state.remindingByParticipantId[participantId] = false;
+      });
```
Comment (richardolsson) [inline src/features/events/store.ts:506]:
```suggestion
    participantsReminded: (
      state,
      action: PayloadAction<number>
    ) => {
      const eventId = action.payload;
      state.remindingByEventId[eventId] = false;
```

File: src/features/events/hooks/useEventParticipantsMutations.ts [hunk 4]
```diff
@@ -15,7 +16,7 @@ export enum participantStatus {
 
 type useEventParticipantsMutationsMutationsReturn = {
   addParticipant: (personId: number) => void;
-  sendReminders: (eventId: number) => void;
+  sendReminders: (eventId: number, participantIds: number[]) => void;
```
Comment (richardolsson) [inline src/features/events/hooks/useEventParticipantsMutations.ts:19]:
```suggestion
  sendReminders: (eventId: number) => void;
```

File: src/features/events/hooks/useEventParticipantsMutations.ts [hunk 5]
```diff
@@ -59,9 +60,10 @@ export default function useEventParticipantsMutations(
       });
   };
 
-  const sendReminders = async (eventId: number) => {
+  const sendReminders = async (eventId: number, participantIds: number[]) => {
+    dispatch(participantsRemind(participantIds));
```
Comment (richardolsson) [inline src/features/events/hooks/useEventParticipantsMutations.ts:64]:
```suggestion
    dispatch(participantsRemind());
```

File: src/features/events/components/ParticipantSummaryCard.tsx [hunk 6]
```diff
@@ -65,6 +67,14 @@ const ParticipantSummaryCard: FC<ParticipantSummaryCardProps> = ({
...
   >(null);
 
+  const participantsReminding = useAppSelector(
+    (state) => state.events.remindingByParticipantId
+  );
+
+  const isRemindingParticipants = Object.values(participantsReminding).some(
+    (participant) => participant
+  );
+
```
Comment (richardolsson) [inline src/features/events/components/ParticipantSummaryCard.tsx:77]:
```suggestion
  const isRemindingParticipants = useAppSelector(
    (state) => state.revents.remindingByEventId[eventId]
  );

```

**Review by richardolsson — CHANGES_REQUESTED** [review]
Great work on this! I realized this could be simplified (my bad!) by storing the state per event instead of per participant, and have suggested edits below.

**Review by richardolsson — APPROVED** [review]
Great work! We have arrived. Sorry about that detour. 🚀
