### PR TITLE
Sorting of booked participants in events

### LINKED ISSUE #1751: Sorting of event participants is not implemented
## Description
On the event participants page, sorting of participants is not implemented.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/calendar?timeScale=week
2. Drag in the calendar to create an event
3. On the event page, go to "Participants" tab
4. Add a number of participants using the "Add person" button (you can search for "Ben")
5. Click any of the table column headers under "booked participants"

### Expected Behaviour
The table should sort based on the clicked header.

### Actual Behaviour
The header highlights with a red border, but nothing happens to the list.

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by MattettaM**
## Description
This PR adds sorting of name, phone number, email, and notified date to the booked participants table.

## Screenshots
image
image
image

## Changes
Adds ascending, descending, and deselection of sorting to Name, Phone, Email, Notified, and Attending fields in the Booked Participants table in Events.
Added header title to Attending column.

## Notes to reviewer
Add participants to event. Notify participants. Add additional participants. Notify again. Click the different columns to sort.

## Related issues
Resolves #1751

### CODE REVIEW

File: src/features/events/components/ParticipantListSection.tsx [hunk 1]
```diff
@@ -236,15 +235,22 @@ const ParticipantListSection: FC<ParticipantListSectionListProps> = ({
...
+      },
     },
     {
       align: 'right',
       disableColumnMenu: true,
       field: 'cancel',
       flex: 1,
-      headerName: '',
-      hideSortIcons: true,
+      headerName: messages.eventParticipantsList.attendance(),
```
Comment (ziggabyte) [inline src/features/events/components/ParticipantListSection.tsx:253]: yay for header name! :D

**Review by ziggabyte — APPROVED** [review]
Hi! 😸 I've tried out this code, and it does what it should! Super nice! I can't see any problems or improvements in the code so I am happy to merge this! 
💯 🥳
