### PR TITLE
Fix console error in MonthCalendar

### LINKED ISSUE #303: console error on MonthCalendar
Steps to reproduce:
visit /calendar, check console error relating to react keys

### PR DESCRIPTION
**Pull request by omidhq**
Resolves #303

### CODE REVIEW

File: src/components/ZetkinCalendar/MonthCalendar/index.tsx [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { grey } from '@material-ui/core/colors';
 import NextLink from 'next/link';
 import { Box, Button, Link, makeStyles, Tooltip, Typography } from '@material-ui/core';
 import { FormattedDate, FormattedMessage as Msg } from 'react-intl';
-import  { useEffect, useRef, useState } from 'react';
+import  React, { useEffect, useRef, useState } from 'react';
```
Comment (richardolsson) [inline src/components/ZetkinCalendar/MonthCalendar/index.tsx:5]: I think another way could be to `import { Fragment, useEffect, useRef, useState }` and to then use `Fragment` directly.

**Review by richardolsson — APPROVED** [review]
Looks good to me! I think we can merge this. 😊
