### PR TITLE
Make local person column filterable

### LINKED ISSUE #2581: Lists: It's not possible to filter a `local_person` ("Assignee") column
### The feature
The "Lists" feature in Zetkin (technically known as "views") allows an organizer user to create a list of people, with configurable columns, similar to a spread sheet.

One column type is the `local_person` (often referred to in the UI as "Assignee"). The purpose of this column is to create a column where the value of the column in each row will be a person. This allows, for example, to "assign" each person (row) in a list to an organizer/mentor/contact.

### The bug
Most columns can be sorted and filtered, but filtering the `local_person` column does not work as expected (or mostly not at all).

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people and sign in as `testadmin@example.com`
2. Create a new list
3. Click "Configure" to configure a Smart Search for the list
4. Change the start value of the Smart Search to "Start with a list of all the people in the organization"
5. Save the Smart Search (a long list of people should appear)
6. Click "New column"
7. In the column gallery, find and add the column type called "Assigned person"
8. Double click a cell in the new column
9. Type the name of any person in the organization (e.g. "Angela" or "Ben")
10. Pick any person from the list to assign
11. Repeat steps 8-10 on several rows, ideally with different assignees
12. Hover the column header and click the ellipsis menu (three dots)
13. Click "Filter"
14. In the filter box that opens, start typing the name of a person added in step 10

### Expected Behaviour
All rows should be hidden except the ones assigned to a person whose name matches whatever you have typed.

### Actual Behaviour
All rows are hidden.

### Three people assigned to Angela (after step 11)

Image

### No one found when filtering

Image

### PR DESCRIPTION
**Pull request by k-nut**
## Description
This PR ensures that column filtering works for the `local_person` (Assignee) cell type in people lists.

## Changes
This change adds the `valueGetter` function which can be used to get a string-representation of the cell to search through with the filter.

## Notes to reviewer
I have noticed that `getSearchableStrings` which is already used for quick *searching* returns even more fields and wondered if it would be consistent to also only return first and last name there to make it consistent. Happy to hear what you think.

## Related issues
Resolves #2581

### CODE REVIEW

File: src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx [hunk 1]
```diff
@@ -24,11 +24,14 @@ import { useMessages } from 'core/i18n';
 
 type LocalPersonViewCell = null | ZetkinPerson;
 
+const makeName = (cell: { first_name: string; last_name: string }) =>
```
Comment (ziggabyte) [inline src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx:27]: We love a little util! :D

File: src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx [hunk 2]
```diff
@@ -52,9 +54,10 @@ export default class LocalPersonColumnType
         if (!v2) {
           return -1;
         }
-        const name1 = `${v1.first_name} ${v1.last_name}`;
-        const name2 = `${v2.first_name} ${v2.last_name}`;
-        return name1.localeCompare(name2);
+        return makeName(v1).localeCompare(makeName(v2));
+      },
+      valueGetter: (params) => {
+        return params.value ? makeName(params.value) : '';
```
Comment (ziggabyte) [inline src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx:60]: niiiice :)

**Review by ziggabyte — APPROVED** [review]
Nice work! 
When I play with the preview build it works as I expect it to, and the code looks neat and functional :)

Regarding your question of `getSearchableStrings`, I think it's fine for now the way it is :) 

I'm gonna merge this now!
