### PR TITLE
Dates in the importer

### LINKED ISSUE #1779: Importer: Swedish "personnummer" is not translated as date
## Description
When importing people, if the organization for example uses swedish "personnummer" as a person's date-of-birth, it is not possible to import this as a date as the importer as it only wants dates that are of a specific shape. 

## Steps to reproduce
1. Start an import by going to `orgs/1/people` and selecting "import people" from the top right corner menu
2. Select a file that has a column containing swedish "personnummer"
3. Select to import this column as "Extra date"
4. Also select an ID so that you can click "Validate" at the bottom right corner

### Expected Behaviour
Recieve no errors

### Actual Behaviour
You get an error message that the values are of the wrong format and cannot be imported as dates.

## Screenshots (if you have any)
bild

## Suggested solution
Use similar logic as in "gen 2" to do a special solution for the swedes.

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR adds interface and logic for the user to pick what formats the dates they want to import are in. They can pick between swedish, norwegian and danish personnumber, a few pre-filled formats, or custom format.

It also contains a pretty significant refactor to the former `useUIDataColumns` hook, splitting it into multiple hooks.

## Screenshots
bild

## Changes
* Refactors `useUIDataColumns` into multiple hooks
* Adds `DateConfig` component to handle selecting date format
* Adds `DatePreview` component to show dates in the preview
* Adds `parseDate` function with tests, to parse values of different formats into dates
* Adds logic and tests to `predictProblems` and `prepareImportOperations` to handle dates

## Notes to reviewer
Create a file with some data that you want to import as dates, and try to import it!

## Related issues
Resolves #1779

### CODE REVIEW

**Review by richardolsson — COMMENTED** [review]
Nice work on this! I'm sorry I haven't finished this review yet, but I started writing some comments before I was sidetracked and became busy with other things. I'm publishing it now because I don't know when I'll find time to finish the review and if you want you can respond to these in the meantime.

File: src/features/import/hooks/useColumn.ts [hunk 1]
```diff
@@ -60,14 +67,25 @@ export default function useColumn(orgId: number) {
...
-    label: field.title,
-    value: `field:${field.slug}`,
-  }));
+
+  const customFieldsOptions: Option[] = customFields.map((field) => {
+    if (field.type === CUSTOM_FIELD_TYPE.DATE) {
+      return {
+        label: field.title,
+        value: `date:${field.slug}`,
+      };
```
Comment (richardolsson) [inline src/features/import/hooks/useColumn.ts:76]: This deviates a little bit from the approach that would feel most natural to me, which is to still consider this a `field` but then handle that field differently elsewhere based on the type of the field. But I haven't tried it so I don't know if that causes problems as it cascades, so I am not suggesting that you change it now.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Amazing work on this, both the refactor of the mega-hook, and the implementation of the new feature. It's going to make organizers very happy!

I found some stuff below that maybe you can fix before we merge? Also see my previous comments. 😊

File: src/features/import/utils/problems/predictProblems.spec.ts [hunk 2]
```diff
@@ -452,4 +445,79 @@ describe('predictProblem()', () => {
...
+        { data: [2, '041231-1473', '201213'] },
+        { data: [3, '650114812', '030307'] },
+      ],
+    });
+
+    const problems = predictProblems(sheet, 'SE', customFields);
+    expect(problems).toEqual([]);
+  });
+
+  it('returns problem when date column is configured but some cells do not have a value', () => {
```
[the remark this answers is not in the document]
Comment (ziggabyte) [reply src/features/import/utils/problems/predictProblems.spec.ts:481]: You are correct, I think i wrote the title string before I cleared up my own misunderstanding and forgot to change the string (another argument to add to the ever-growing pile of  "reasons i dislike strings")

File: src/features/import/utils/parseDate.spec.ts [hunk 3]
```diff
@@ -0,0 +1,68 @@
+import parseDate from './parseDate';
+
+describe('parseDate()', () => {
```
[the remark this answers is not in the document]
Comment (ziggabyte) [reply src/features/import/utils/parseDate.spec.ts:3]: This was solved by a combination of your previous suggestions on changing the cut0off logic and only running `placeInCorrectCentury` when the dateformat has 2-digit year! :)

File: src/features/import/hooks/useColumn.ts (hunk 1 above)
Comment (ziggabyte) [reply src/features/import/hooks/useColumn.ts:76]: The reason for it is that it is how I decide what column kind to create... I think you are right, that it would make more sense to use `field`, but I could not figure out another way to know how to decide what type of data was being imported... 

in `FieldSelect.tsx`
bild

File: src/features/import/components/ImportDialog/Configure/Configuration/DateConfig.tsx [hunk 4]
```diff
@@ -69,7 +69,11 @@ const DateConfig: FC<DateConfigProps> = ({ uiDataColumn }) => {
           </ListSubheader>
           {dateFormats.map((format) => (
             <MenuItem key={format} sx={{ paddingLeft: 4 }} value={format}>
-              {format}
+              <Msg
+                id={
+                  messageIds.configuration.configure.dates.dateFormats[format]
+                }
+              />
```
Comment (richardolsson) [inline src/features/import/components/ImportDialog/Configure/Configuration/DateConfig.tsx:76]: Why localize this? The format is already hard-coded (because that's what we're allowing the user to pick here) so I reckon the examples could also be hard-coded.

File: src/features/import/hooks/useDateConfig.ts [hunk 5]
```diff
@@ -62,7 +62,17 @@ export default function useDateConfig(column: DateColumn, columnIndex: number) {
     personNumberFormats.push('se', 'dk', 'no');
   }
 
-  const dateFormats = ['YYYY-MM-DD', 'YY-MM-DD', 'MM-DD-YYYY'];
+  enum DateFormats {
+    'YYYY-MM-DD' = 'YYYY-MM-DD',
+    'YY-MM-DD' = 'YY-MM-DD',
+    'MM-DD-YYYY' = 'MM-DD-YYYY',
+  }
```
Comment (richardolsson) [inline src/features/import/hooks/useDateConfig.ts:69]: Why make this an enum instead of just keeping the array?

File: src/features/import/utils/parseDate.ts [hunk 6]
```diff
@@ -9,14 +9,11 @@ dayjs.extend(customParseFormat);
 const placeInCorrectCentury = (date: Date) => {
   const thisYear = new Date().getFullYear();
 
-  //This cutoff is to calculate a date window of 100 years,
-  //so we can decide which century a 2-digit year belongs to.
-  //It seems unlikely users will import people who are older than 110 years of age.
-  const cutoff = thisYear - 110;
-
+  //This cutoff is to calculate which century a 2-digit year belongs to.
+  //It seems unlikely users will import people who are younger than 10 years of age.
```
Comment (richardolsson) [inline src/features/import/utils/parseDate.ts:13]: Reading this comment, I realize that we have fixated on age. But a lot of dates are not referring to a person's age, but their join date, date of last activity or things like that. Those are all _more_ likely to be within the last 10 years than 100 years ago.

I wonder what we should do about this? Maybe not solve it now, but note somewhere that this requires some more thinking and potentially UI changes to make this behavior optional for the user?

File: src/features/import/utils/parseDate.ts [hunk 7]
```diff
@@ -49,7 +46,10 @@ export default function parseDate(value: CellData, format: string) {
   }
 
   const date = parsedDate.toDate();
-  placeInCorrectCentury(date);
+
+  if (!dateFormat.includes('YYYY')) {
```
Comment (richardolsson) [inline src/features/import/utils/parseDate.ts:50]: Nice solution!

**Review by richardolsson — DISMISSED** [review]
Nice work! I did find some more issues but none of them are blockers. I'll let you decide what to do!

File: src/features/import/utils/parseDate.ts (hunk 6 above)
Comment (ziggabyte) [reply src/features/import/utils/parseDate.ts:13]: Oh lord this is correct.. how about I change so that anything from 00 to current year gets prefixed with 20, and those above will get 19? that means we might have issues with a few 100-year old members, but if like you say it's more common to use this for just dates in general, then the current way will cause way more problems?

File: src/features/import/components/ImportDialog/Configure/Configuration/DateConfig.tsx (hunk 4 above)
Comment (ziggabyte) [reply src/features/import/components/ImportDialog/Configure/Configuration/DateConfig.tsx:76]: No reason other than my head was spinny I think 😵‍💫 I'll change it :)

File: src/features/import/hooks/useDateConfig.ts (hunk 5 above)
Comment (ziggabyte) [reply src/features/import/hooks/useDateConfig.ts:69]: same as above, probably just a spinny head :)

File: src/features/import/utils/parseDate.ts (hunk 6 above)
Comment (richardolsson) [reply src/features/import/utils/parseDate.ts:13]: I think it's hard to make a choice here, because different types of columns (birth dates vs join dates, for example) will need to be treated differently.

File: src/features/import/utils/parseDate.spec.ts [hunk 8]
```diff
@@ -67,18 +67,18 @@ describe('parseDate()', () => {
   });
 
   it('correctly parses a 2-digit year into the right century', () => {
-    const firstDate = parseDate(230101, 'YYMMDD');
+    const firstDate = parseDate(250101, 'YYMMDD');
```
Comment (richardolsson) [inline src/features/import/utils/parseDate.spec.ts:70]: I love tests! So easy to review changes, and it hopefully also felt easy to confidently make the changes.

**Review by richardolsson — APPROVED** [review]
I think think is ready to merge now! 🎉 

I looked at the updated preview build, and at the code, and all looks good to me.

File: src/features/import/utils/parseDate.spec.ts (hunk 8 above)
Comment (ziggabyte) [reply src/features/import/utils/parseDate.spec.ts]: I just realised that this specific version of this test only has a lifetime of 6 months ish so changed to 29 instead for a bit of an extended longevity lol

Comment (richardolsson) [reply src/features/import/utils/parseDate.spec.ts]: In the future, we can use jest time mocking to fake it such that the tests is always executed at a fixed (fake) point in time. But lets be content with this for now, since this test will last for five years. 😊

**Review by richardolsson — APPROVED** [review]
Lets merge! 🟢 🟢 🟢
