### PR TITLE
Journey data dump

### LINKED ISSUE #583: Journey data dump as CSV
## Description
A user should be able to download all the data displayed in the Journey listing table, i.e. tags, open/close dates, assignees etc.

## Relevant Job Stories
* When I'm making complex reports, I want to be able to download the raw data of all cases, so that I can analyze it in other software

## Prerequisites
Do not start working on this until the following have been closed

* #575 

## Requirements
- [ ] Create ellipsis menu with download link on the [journeyId] page
- [ ] Create ellipsis menu with download link on the journeys page (to download all instances, regardless of type)
- [ ] Download should include all columns specified in #575 

## Possible implementations
Perhaps use the data grid's CSV export functionality (also implemented as solution to #480).

## Design specifications
Let's use ellipsis menus, so no design is required.

## Open questions
None

### LINKED ISSUE #702: "Tags" column visible even if there are no tags
## Description
The "Tags" column in a journey instance list should only be visible if there are ungrouped tags in the data set. When there are no ungrouped tags, the column is redundant.

## Steps to reproduce
1. Go to Journeys
2. Click "Case"
3. Make sure no cases have any ungrouped tags

### Expected Behaviour
Table should not contain a column called "Tags"

### Actual Behaviour
Table contains an empty column called "Tags"

### Screenshots
image

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR adds functionality to download all the instances of a single journey, or any journey, as either CSV or XLSX (Excel) files.

## Screenshots
image

image

## Changes
* Adds utilities in `journeyInstanceUtils` to figure out what columns are needed to display the tags of all instances in a list
* Creates an API route to download journey instances:
  * Can download all journey instances in an organization, regardless of journey
  * Can download all instances of a certain journey
  * Can download as either CSV or XLSX
* Adds download options to ellipsis menus on the journey overview page and the journey instance list page

## Notes to reviewer
Please also see #720, and decide which one is easier to review first. I separated it out as it's unrelated, but uses code from this one. My thought was to review that one first, and then merge it into this one.

## Related issues
Resolves #583 
Resolves #702

### CODE REVIEW

**Comment by richardolsson** [comment]
I want to wait for the conflict to be resolved in #687 before resolving this one, or I will have to do it twice. 😊 

But this can still be reviewed, I reckon!

File: src/pages/api/journeyInstances/download.ts [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+  JourneyTagColumnType,
+} from 'utils/journeyInstanceUtils';
+import { ZetkinJourney, ZetkinJourneyInstance } from 'types/zetkin';
+
+const FORMAT_TYPES = {
+  csv: 'text/csv',
+  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
+};
+
+export default async function handler(
```
Comment (djbusstop) [inline src/pages/api/journeyInstances/download.ts:17]: Cool you ended up doing it this way!

File: src/pages/api/journeyInstances/download.ts [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+      instance.assignees
+        .map((person) => `${person.first_name} ${person.last_name}`)
+        .join(', '),
+    ].concat(
+      columns.map((column) => {
+        if (column.type == JourneyTagColumnType.VALUE_TAG) {
+          return column.valueGetter(instance);
+        } else {
+          return column
+            .tagsGetter(instance)
```
Comment (djbusstop) [inline src/pages/api/journeyInstances/download.ts:109]: It all comes together

File: src/layout/organize/JourneysLayout.tsx [hunk 3]
```diff
@@ -11,6 +11,24 @@ const JourneysLayout: React.FunctionComponent = ({ children }) => {
...
+          onSelect: () => {
+            location.href = `/api/journeyInstances/download?orgId=${orgId}`;
+          },
+        },
+        {
+          label: intl.formatMessage({
+            id: 'layout.organize.journeys.menu.downloadXlsx',
+          }),
+          onSelect: () => {
+            location.href = `/api/journeyInstances/download?orgId=${orgId}&format=xlsx`;
```
[the remark this answers is not in the document]
Comment (richardolsson) [reply src/layout/organize/JourneysLayout.tsx:28]: I'm honestly not sure if there is any difference between doing this and using the router. I did this because I wanted the browser to trigger a download, which it does (it does not navigate, unless there is an error). I didn't use the router because this is completely outside the scope of what the router brings to the table, but it probably would work (and it would just do the same thing internally).

I can give it a try if you want?

**Comment by richardolsson** [comment]
Ready for final review! 😊

**Review by djbusstop — APPROVED** [review]
