### PR TITLE
issue-2655 | Feed includes events from all orgs

### LINKED ISSUE #2655: My Home: Feed includes events even from unfollowed organizations
### The feature
A single user can be connected to multiple organizations in Zetkin, and decide when connecting whether to "follow" them or not. The UI for this was introduced recently in #2636.

Following an organization is supposed to mean that their events show up in your "feed", at /my/feed. 

### The bug
Currently, the feed at /my/feed lists all public events for all organizations that the user is connected to, not just the ones that they follow.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Go to any project, make sure it is published (from the "Edit project" modal in the ellipsis menu, top right)
3. Create an event in the future and publish the event
4. Go to https://app.dev.zetkin.org/o/1
5. Make sure the current user does _not_ "follow" the organization (click "unfollow" if already following)
6. Go to https://app.dev.zetkin.org/my/feed

### Expected Behaviour
There should be no events from organization 1. The event you created should not be in the list.

### Actual Behaviour
All events for organization 1 are in the list. The "follow" does not matter.

## Screenshots
None

## Proposed solution
Respect `membership.follows` in the RPC that loads all events (`getAllEvents`).

### PR DESCRIPTION
**Pull request by Fardad13**
## Description
This PR solves issue #2655 which is described quite thoroughly. Also it changes 

## Screenshots
image

## Changes
* When navigating to [My Feed](https://app.dev.zetkin.org/my/feed) instead of showing the events from all the users organizations, events are only shown if the user follows the organization 
* While loading the events, they are now requested asynchronously grouped by organization 

## Notes to reviewer
A few thoughts here:
* I dont know how the backend is looking, I checked for documentation/a swagger but could not find one (tbh I didnt look very through). It might be sensible to use other endpoints or query parameters (or implement them e.g. GET /api/users/me/memberships?follow=true)
* In regular use cases it should not cause any issues to call GET /api/orgs/{id}/actions async. In most cases it should also not provide huge benfits, but... I like to do it :) Feel free to drop the second commit if you do not like it.

## Related issues
Resolves #2655

### CODE REVIEW

File: src/features/events/rpc/getAllEvents.ts [hunk 1]
```diff
@@ -20,22 +20,25 @@ export const getAllEventsDef = {
...
 
 async function handle(params: Params, apiClient: IApiClient): Promise<Result> {
-  const memberships = await apiClient.get<ZetkinMembership[]>(
-    '/api/users/me/memberships'
-  );
+  const memberships = await apiClient
+    .get<ZetkinMembership[]>('/api/users/me/memberships')
+    .then((memberships) =>
+      memberships.filter((membership) => membership.follow)
+    );
```
Comment (ziggabyte) [inline src/features/events/rpc/getAllEvents.ts:27]: Nice solve of the bug! 🐛 

In the Zetkin code we prefer to no use `.then(...)` but instead `await` something, and then use that thing on the next line. We find it more easy to read and maintain when the action of fetching something is separated from the action of handling that data. 

So, I wonder if you would want to change this to make it in this style instead: 
```
const allMemberships = await apiClient.get...() ;
const filteredMemberships = allMemberships.filter(...);
```

File: src/features/events/rpc/getAllEvents.ts [hunk 2]
```diff
@@ -20,22 +20,25 @@ export const getAllEventsDef = {
...
-    );
-    events.push(...eventsOfOrg);
-  }
-
-  return events.filter((event) => {
-    const state = getEventState(event);
-    return state == EventState.OPEN || state == EventState.SCHEDULED;
-  });
+  return await Promise.all(
+    memberships.map((membership) =>
```
Comment (ziggabyte) [inline src/features/events/rpc/getAllEvents.ts:32]: Nice initiative to change from the `for`-loop to `await Promise.all` :) 

However, I have a couple of thoughts that I'm gonna share with you, and then we can take it from there - mostly because we don't know eachother yet and this is your first contributions to the project. 

In the Zetkin project we like to keep quite strictly to the task at hand when we make commits and PRs. It makes it easier for reviewers to be sure that all the code in the PR is actually related to solving the problem, and for the same reason it makes it easier in the future when looking back to problem-solve. 

Like I mentioned above, we also don't use the `.then(...)` pattern, as it is more complex to read and understand. So even though I totally agree that `await Promise.all(...)` makes sense to use here, this refactor also adds quite some complexity to the code. 

My suggestion to keep it a bit simpler, is to just exchange the `for`-loop to the `await Promise.all(...)`, keeping the logic that was inside the for-loop the same. You can do this by sending in `async` functions as a callback like this 
```
...map(async (membership) => ... 
``` 
Then you can keep it the same, while still exchanging `for`-loop for `await Promise.all(...)`. How does that sound to you?

**Review by ziggabyte — CHANGES_REQUESTED** [review]
So happy to have you making these two contributions spontaneously :) 

I left two comments below that open up into learning more about the style and thought process that we base our code on. I hope it feels interesting to you to learn about us, because we are very happy to learn about you also :) 

Feel free to ask any questions and share your thoughts!

**Comment by Fardad13** [comment]
Thanks for your very detailed feedback! I adapted the code to use async/await. Feel free to give it another look :)

File: src/features/events/rpc/getAllEvents.ts [hunk 3]
```diff
@@ -20,22 +20,27 @@ export const getAllEventsDef = {
...
+      return events.filter((event) =>
+        eventStates.includes(getEventState(event))
+      );
+    })
+  );
+
+  return allEvents.flat();
 }
+
+const eventStates = [EventState.OPEN, EventState.SCHEDULED];
```
Comment (ziggabyte) [inline src/features/events/rpc/getAllEvents.ts:46]: I think this should still change back to where it was in the original code - aka move the filtering to happen outside, and keep the filtering logic the same :) 

Then we have the addition of the `await Promise.all(...)` as the only difference, and we keep it simle by separating the getting of the events and the filtering!

File: src/features/events/rpc/getAllEvents.ts [hunk 4]
```diff
@@ -20,22 +20,27 @@ export const getAllEventsDef = {
 export default makeRPCDef<Params, Result>(getAllEventsDef.name);
 
 async function handle(params: Params, apiClient: IApiClient): Promise<Result> {
-  const memberships = await apiClient.get<ZetkinMembership[]>(
+  const allMemberships = await apiClient.get<ZetkinMembership[]>(
     '/api/users/me/memberships'
   );
+  const filteredMemberships = allMemberships.filter(
+    (membership) => membership.follow
+  );
```
Comment (ziggabyte) [inline src/features/events/rpc/getAllEvents.ts:28]: naiiiiice :)

**Review by ziggabyte — CHANGES_REQUESTED** [review]
Nearly there! 

I have one comment below to make it so that the only update besides adding the filtering, is to change from for-loop to await Promise.all()!

File: src/features/events/rpc/getAllEvents.ts (hunk 3 above)
Comment (Fardad13) [reply src/features/events/rpc/getAllEvents.ts]: Appreciate your guidance on process and styling on this one :) This might be good to go now?

**Review by ziggabyte — APPROVED** [review]
We have arrived! 

It works just as expected when i test it in the Vercel deploy, and the code looks as expected as well - great job!! Hope to see more of your contributions in the future, also sent you a message on slack 📫

File: src/features/events/rpc/getAllEvents.ts (hunk 3 above)
Comment (ziggabyte) [reply src/features/events/rpc/getAllEvents.ts]: So happy to hear that, yes it's great!
