### PR TITLE
remove invalid Some option from UI

### LINKED ISSUE #2314: Invalid operator `some` in survey options Smart Search filter
## Description
Smart Search has a filter for finding people based on survey options (`survey_option`). The UI for configuring this filter has a "some" option, which is not valid and should be removed.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Create a new list
3. Configure the list using Smart Search
4. Click "Add/remove people"
5. Add a filter based on "Responses to checkbox questions"
6. Click the operator dropdown

### Expected Behaviour
The options should be "all", "any" and "none".

### Actual Behaviour
The options are "all", "any", "none" and "some" (the last of which is invalid).

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by helihard**
## Description
This PR removes the invalid "Some" operator in the survey options Smart Search filter from the UI.

## Screenshots
smart-search-wo-some

## Changes

* Remove the invalid operator "Some" from the Smart Search filter of survey option "Responses to checkbox questions".

## Related issues
Resolves #2314

### CODE REVIEW

File: src/features/smartSearch/components/filters/SurveyOption/index.tsx [hunk 1]
```diff
@@ -215,11 +215,13 @@ const SurveyOption = ({
                 onChange={(e) => handleConditionSelectChange(e.target.value)}
                 value={filter.config.operator}
               >
-                {Object.values(CONDITION_OPERATOR).map((o) => (
-                  <MenuItem key={o} value={o}>
-                    <Msg id={localMessageIds.conditionSelect[o]} />
-                  </MenuItem>
-                ))}
+                {Object.values(CONDITION_OPERATOR)
+                  .filter((o) => o !== CONDITION_OPERATOR.SOME)
```
Comment (richardolsson) [inline src/features/smartSearch/components/filters/SurveyOption/index.tsx:219]: This is a nice and quick way of removing it from the UI, but it doesn't remove it from the type or underlying data structures.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! You've solved the issue very quickly, but I realize now that I see the code that this only fixes it on a superficial level. The code still "thinks" that `some` is a valid operator, which is a flaw in how the `SurveyOptionFilterConfig` has been designed.

I think the `some` option should be removed from the type, which probably requires using another enum than the `CONDITION_OPERATOR` currently used. 

I didn't realize the types were this "messy". Do you want to take a look at this bigger change?

File: src/features/smartSearch/components/filters/SurveyOption/index.tsx (hunk 1 above)
Comment (helihard) [reply src/features/smartSearch/components/filters/SurveyOption/index.tsx:219]: Yes, I see the problem. When I read the issue, I interpreted it as a question of simply preventing the regular user from interacting with the invalid operator. I can certainly take a look at it, but might need to bow out, or enlist some help at the next hackathon, if it turns out to be too much for my level.

**Comment by richardolsson** [comment]
@helihard: I think the simplest way to solve this is to copy the `CONDITION_OPERATOR` enum that is currently used by several filters, to a new one that is only used in this filter, and then alter it to remove the "Some" operator. Would you like to have a go at that?

File: src/features/smartSearch/components/types.ts [hunk 2]
```diff
@@ -42,6 +42,12 @@ export enum CONDITION_OPERATOR {
   SOME = 'some',
 }
 
+export enum SURVEY_CONDITION_OP {
+  ALL = 'all',
+  ANY = 'any',
+  NONE = 'none',
+}
```
Comment (richardolsson) [inline src/features/smartSearch/components/types.ts:49]: Nice, so simple! 💯

File: src/features/smartSearch/components/types.ts [hunk 3]
```diff
@@ -217,7 +223,7 @@ export interface SurveyOptionFilterConfig {
   survey: number;
   question: number;
   options: number[] | string[];
-  operator: CONDITION_OPERATOR;
+  operator: SURVEY_CONDITION_OP;
```
Comment (richardolsson) [inline src/features/smartSearch/components/types.ts:226]: This makes the type more correct (in relation to the API, which is the authority)!

**Review by richardolsson — APPROVED** [review]
Nice work resolving this! I have tried the preview build, and reviewed the recent changes to the code, and I think this is ready to merge as is. 💯 👏
