### PR TITLE
Remove broken isAnyOf filter in lists/views

### LINKED ISSUE #1544: Implement "is any of" filter in lists
## Description
Attempting to apply the "is any of" operator when filtering a list creates an error, and the UI does not match other inputs in the filter modal.

## Steps to reproduce
1. Go to a list
2. Click on "Filter"
3A. In "operator" dropdown, select "any of"
3B. Type something into the text input, and "enter" to apply filter

### Expected Behaviour
3A - the text input has the same look as the other text inputs in the filter modal
3B - the list gets filtered by any of the things that has been typed into the text input

### Actual Behaviour
3A - it has the outlined style, not the "standard"
3B - attempting to apply this filter causes an error 

## Screenshots (if you have any)
bild
bild

### PR DESCRIPTION
**Pull request by niklasva82**
## Description
This PR removes the broken isAnyOf filter in lists, and customizes the filter type for the local_bool type. In the future we should probably have the filterOperators based on the type of column, but a lot of these seem to need custom functions because e.g. dates are not stored as dates in the cells.

## Screenshots
image
image

## Notes to reviewer
I tried to solve the underlying issue, which is that `GridFilterInputMultipleValues` sometimes receives a single string rather than an array of strings, which crashes the page. Perhaps this could be solved in the future if we think the "any of" filter is important.

## Related issues
Resolves #1544

### CODE REVIEW

**Comment by richardolsson** [comment]
I'm guessing this is ready for review?

**Comment by niklasva82** [comment]
Yes

Den fre 29 sep. 2023 11:54Richard Olsson ***@***.***> skrev:

File: src/features/views/components/ViewDataTable/index.tsx [hunk 1]
```diff
@@ -93,6 +96,14 @@ const useStyles = makeStyles((theme) => ({
   },
 }));
 
+const getFilterOperators = (col: ZetkinViewColumn) => {
+  if (COLUMN_TYPE.LOCAL_BOOL === col.type) {
+    return getGridBooleanOperators();
+  } else {
+    return getGridStringOperators().filter((op) => op.value !== 'isAnyOf');
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/index.tsx:103]: This means all columns except `local_bool` get handled as strings, regardless of how they've been marked up.

**Review by richardolsson — CHANGES_REQUESTED** [review]
In your PR intro you put:

>  In the future we should probably have the filterOperators based on the type of column, but a lot of these seem to need custom functions because e.g. dates are not stored as dates in the cells.

I agree with this, and it's actually already being done for some column types, e.g. the `local_query` type:

Filtering a local_query column

It can also be achieved quite easily for other column types, e.g. `survey_submitted` which should be interpreted as a date:

```diff
diff --git a/src/features/views/components/ViewDataTable/columnTypes/SurveySubmittedColumnType.tsx b/src/features/views/components/ViewDataTable/columnTypes/SurveySubmittedColumnType.tsx
index c973b302..519b3cee 100644
--- a/src/features/views/components/ViewDataTable/columnTypes/SurveySubmittedColumnType.tsx
+++ b/src/features/views/components/ViewDataTable/columnTypes/SurveySubmittedColumnType.tsx
@@ -29,6 +29,8 @@ export default class SurveySubmittedColumnType
         return <Cell cell={params.value} />;
       },
       width: 250,
+      type: 'dateTime',
+      valueGetter: (params) => new Date(params.value.submitted),
     };
   }
   getSearchableStrings(): string[] {
```

But this PR is actually a step in the _opposite_ direction, because it overrides all filter operators (except `local_bool`), regardless of column data type and other configuration options in the `colDef`, to always use string operators.

In my opinion, this is not a good solution, because it not only removes functionality that currently exists (e.g. boolean filtering of Smart Search columns, screenshot above), but it also makes future changes more difficult by adding this override that whoever comes back to add more flexible filters will have a very hard time finding.

I think another approach to this is needed, and I'd really wish that we could solve the underlying issue. Maybe if you could elaborate on it, we could work it out together?

**Review by richardolsson — APPROVED** [review]
I think this came out good and the diff looks nice and clean to me. I suggest you use the GitHub feature to "squash and merge" as a single commit. 😊
