### PR TITLE
Map gender fields on CSV import

### LINKED ISSUE #2348: Import: Gender field has no mapping configuration
## Description
Zetkin has native fields on person object (e.g. first name and email), that exist in all organizations, and custom fields, which is a way for an organization to create additional fields on a person object. The "gender" field is a native field in Zetkin. It allows four values, `'m'` (male), `'f'` (female), `'o'` (other) and `null` (unknown).

The import feature in Zetkin allows admin users to import data from a CSV or Excel file, usually exported from some other system. Those systems rarely have the exact same conventions for the gender field, so there needs to be some sort of way for users of the importer to map from values in the file to one of the allowed values in Zetkin.

Similar mapping already exists for several other types of data, such as custom fields of the "enum" type, tags and organizations.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Click on "CREATE"
3. Click on "Import people"
4. Drop any small CSV file (see example below)
5. For the "GENDER" column, pick "Gender" from the drop-down

### Sample CSV
```csv
FIRST,LAST,GENDER
Clara,Zetkin,woman
Richard,Olsson,man
Someone,Else,nb
Lesser,Known,unknown
```

### Expected Behaviour
There should be a "Configure" option under the dropdown, and the configuration should open to the right. The configuration should allow the user to map the values that exist in the column ("woman", "man", "nb" and "unknown") to the allowed values in Zetkin. Compare with how the "tag" filter or "extra enum" filter works.

### Actual Behaviour
No configuration on the right hand side.

## Screenshots (if you have any)
image

## Proposed solution
Have a look at how the configuration for tags, organizations and enum fields work.

### PR DESCRIPTION
**Pull request by k-nut**
## Description
This PR allows users to properly map the gender fields form their CSV data to the gender definition that Zetkin understands

## Screenshots
[Add screenshots here]

## Changes
Inspired by the enum and org mappings, this adds config and preview components for the gender field.

## Notes to reviewer
The null handling is pretty ugly right now (just replacing `null` with `"null"` so that it can also be used in translations). I'm also unsure how it should generally be handled and how much translations should be duplicated. Any input is appreciated. 

## Related issues
Resolves #2348

### CODE REVIEW

**Comment by richardolsson** [comment]
@ziggabyte can you have a look at this and provide some feedback to @k-nut? Especially around the handling of `null`, which is an allowed value for `gender` but difficult to use as value in components.

**Comment by k-nut** [comment]
Thank you for your thoughts. I pushed a version inspired by your proposal, let me know what you think!

**Comment by richardolsson** [comment]
This PR is still in draft mode, but I think it's ready for review so I'm going to mark it as such. Let me know if that was a mistake and we can change it back.

**Comment by k-nut** [comment]
Oh yes, I forgot. Thank you!

File: src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+            <Button onClick={() => setMapping(true)}>
+              <Msg
+                id={
+                  messageIds.configuration.configure.genders
+                    .showGenderSelectButton
+                }
+              />
+            </Button>
+          )}
+          {showSelect && (
```
Comment (ziggabyte) [inline src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx:71]: This logic, to have a button in place of the Select, was created in the organization mapping because loading and rendering each Select with organisations took a really really long time. So this button was placed there to only load/render each select "on demand". With genders, since no loading of data is happening and it's a small set of values, i think it would be nice to remove the button and just show the select!

File: src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+                <Select
+                  label={messages.configuration.configure.genders.gender()}
+                  onChange={(event) => {
+                    const { value } = event.target;
+                    if (value === 'm' || value === 'f' || value === 'o') {
+                      onSelectGender(value);
+                    } else if (value === 'unknown') {
+                      // selecting `unknown` is like deselecting
+                      onDeselectGender();
+                    }
```
Comment (ziggabyte) [inline src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx:86]: I am not sure I agree (and I might very well be wrong!) that it should be the same to deselect as to select to import a value as `unknown` (`null`). 

What I mean is, that when selecting `unknown`, I want there to be information added to my object of mapping that says "value x should be mapped to null". But deselecting means removing the information related to "value x" in my object of mapping. This comes with the undesired side effect that if I open the gender mapping, and the first value i want to map i select should map to "unknown" - this is not recognised as me having done any mapping at all. Our validation for the mapping will believe no mapping for gender has happened, and it will be forbidden to move on to the validation step. 

What do you think?

File: src/features/import/components/ImportDialog/Configure/Preview/GenderPreview.tsx [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+        columnHeader={messages.configuration.preview.columnHeader.gender()}
+        emptyLabel={messages.configuration.preview.noValue()}
+        rowValue={null}
+        unmappedRow={false}
+      />
+    );
+  }
+  return (
+    <PreviewGrid
+      columnHeader={'Gender'}
```
Comment (ziggabyte) [inline src/features/import/components/ImportDialog/Configure/Preview/GenderPreview.tsx:42]: I think columnHeader needs to be localised in all the places :)

File: src/features/import/hooks/useGenderMapping.ts [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+            mapping: [...column.mapping, newMap],
+          },
+        ])
+      );
+    } else {
+      // If there is already a map, replace it
+      // Find mappings that are not for this row value
+      const filteredMapping = column.mapping.filter((m) => m.value != value);
+      // New orgId for that row value
+      const updatedMap = { ...map, gender };
```
Comment (ziggabyte) [inline src/features/import/hooks/useGenderMapping.ts:44]: Some little copy-paste mistakes here in the comments, do you wanna updated them to relate to gender mapping and not org mapping? :)

File: src/features/import/l10n/messageIds.ts [hunk 5]
```diff
@@ -63,6 +63,17 @@ export default makeMessages('feat.import', {
...
       },
+      genders: {
+        gender: m('Gender'),
+        genders: {
+          f: m('female'),
+          m: m('male'),
+          null: m('unspecified'),
+          o: m('other'),
+        },
+        header: m('Gender'),
```
Comment (ziggabyte) [inline src/features/import/l10n/messageIds.ts:74]: Here is both a key called `header`, and `gender` on the same level translated to the same thing, "Gender". I'm thinking that both could be using the same one - where I prefer `header` since it communicates better what the transaltion is needed for? 

Also an object strucutre thing - `genders.genders` does not feel like the optimal naming, could the inner object maybe be called "genderSelectLabels" or something like that, to more communicate what they are used for?

I also think the genders need to have uppercase in the first letter to look nice in the Select 

In other parts of the code we use the word "unknown" instead of "unspecified", I think this could be good for consistency.

**Review by ziggabyte — CHANGES_REQUESTED** [review]
Hi! :D Looking nice with some updates! I have given a bit of a more detailed reading of the code and some feedback, if something does not seem right please write your thoughts and we can discuss it! 

I also noticed a little bit of logic is missing, that you need to "hook up to" by including `GENDER` as a configurable column in this array in `MappingRow.tsx`. This will show a button to open the config if you wanna get back to it after going to different fields, and also have a warning message if the mapping is unfinished: 
bild

File: src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx (hunk 2 above)
Comment (richardolsson) [reply src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx:86]: I might be misunderstanding, so please ignore if does not make sense.

I believe that another aspect of this decision is what happens to people for where there is no mapping in the import, but do have gender data in the database.

Not mapping anything doesn't change them in the database (the `data` object will not include `gender`), while mapping to "unknown" will overwrite whatever is already in the database (setting `data.gender` to `null`).

So IMO not mapping, and mapping to unknown is two separate actions where the former is a no-op and the latter is destructive.

File: src/features/import/hooks/useGenderMapping.ts (hunk 4 above)
Comment (richardolsson) [reply src/features/import/hooks/useGenderMapping.ts:44]: I think this is a perfect example of the reasons why I try to avoid comments. They exist to make the code easier to read, but it's so easy to make mistakes like this where the code actually becomes more confusing because of the comment.

Generally, if I feel like a comment is needed, I will try to rewrite the code (and especially _name things_) so that the code itself becomes easier to read and the comment isn't needed.

File: src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx (hunk 1 above)
Comment (k-nut) [reply src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx]: Nice, I thought this was for a nicer UI. Removed 🧹

File: src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx (hunk 2 above)
Comment (k-nut) [reply src/features/import/components/ImportDialog/Configure/Configuration/GenderConfigRow.tsx]: I changed the implementation to something that should now work for any of the "regular" genders, a deliberate "we want to set this to null" and a "ignore this value in the import"

File: src/features/import/components/ImportDialog/Configure/Preview/GenderPreview.tsx (hunk 3 above)
Comment (k-nut) [reply src/features/import/components/ImportDialog/Configure/Preview/GenderPreview.tsx]: Good catch. Added 👍

File: src/features/import/hooks/useGenderMapping.ts (hunk 4 above)
Comment (k-nut) [reply src/features/import/hooks/useGenderMapping.ts]: I think the code was actually way too complicated for what it was doing. I changed the implementation. Let me know what you think!

File: src/features/import/l10n/messageIds.ts (hunk 5 above)
Comment (k-nut) [reply src/features/import/l10n/messageIds.ts]: Good call, I've changed them to be more descriptive I hope.

File: src/features/import/l10n/messageIds.ts [hunk 6]
```diff
@@ -63,6 +63,15 @@ export default makeMessages('feat.import', {
         ),
         value: m('Value'),
       },
+      genders: {
+        label: m('Gender'),
+        selectLabels: {
+          f: m('female'),
+          m: m('male'),
+          o: m('other'),
+          unknown: m('unspecified'),
```
Comment (ziggabyte) [inline src/features/import/l10n/messageIds.ts:72]: Tiny thing here - still in need of uppercase on the options, and I think "unspecified" should be changed to "unknown" as the value! :D

File: src/features/import/l10n/messageIds.ts [hunk 7]
```diff
@@ -197,9 +207,16 @@ export default makeMessages('feat.import', {
...
       columnHeader: {
+        gender: m('Gender'),
         org: m('Organization'),
         tags: m('Tags'),
       },
+      genders: {
+        f: m('female'),
+        m: m('male'),
+        o: m('other'),
+        unknown: m('unspecified'),
```
Comment (ziggabyte) [inline src/features/import/l10n/messageIds.ts:218]: Same here!

**Review by ziggabyte — CHANGES_REQUESTED** [review]
Noticed only a small thing when playing around with it right now - that the values in the select are still all lower case :)

File: src/features/import/l10n/messageIds.ts (hunk 6 above)
Comment (k-nut) [reply src/features/import/l10n/messageIds.ts]: Oops, it did feel like I was forgetting something 🙈

File: src/features/import/l10n/messageIds.ts (hunk 7 above)
Comment (k-nut) [reply src/features/import/l10n/messageIds.ts]: Also changed ✅

**Review by ziggabyte — APPROVED** [review]
Playing with this feels like it behaves the way i expect it to! I'm very happy that you added some very neat simplifications to the code that I wrote for org mapping, it's super fun to have you on board contributing :D 

Giving you the seal of approval: 🦭 !
