### PR TITLE
Remove timezone offset from date

### LINKED ISSUE #2882: Event page: Displayed time is off (timezone problem)
### The feature
Events in Zetkin have a start time and an end time. These were originally designed to be "timezone naive", i.e. to not have any timezone information and to always be displayed as is, while being assumed to be in local time wherever the event is taking place. This is problematic for many reasons, but was an early decision in the v1 API and which will be fixed in the v2 API.

### The bug
The public event pages display events 2hrs off (right now, in CEST), probably because issues with how javascript interprets the times.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects and sign in as `testadmin@example.com`
2. Find any project or create a new one
3. Find any event in the project or create a new one
4. Make sure the project and event are both published
5. Set the start and end time to 15:00 and 17:00 respectively
6. Go to the public event page, at https://app.dev.zetkin.org/o/1/events/<ID> where `<ID>` is the ID of the event you just created

### Expected Behaviour
The event page should display 15:00 and 17:00 as the start and end times respectively.

### Actual Behaviour
The event page displays 17:00 and 19:00 as the start and end times respectively, i.e. offset two hours.

## Screenshots

Image

### PR DESCRIPTION
**Pull request by Jrende**
## Description
This PR fixes event page displaying the incorrect time for an event.

## Screenshots
Screen Shot 2025-06-22 at 11 11 55

## Changes
* Adds removeOffset to start and end times.

## Notes to reviewer
[Add instructions for testing]

## Related issues
Resolves #2882

### CODE REVIEW

File: src/features/organizations/pages/PublicEventPage.tsx [hunk 1]
```diff
@@ -313,6 +314,14 @@ const DateAndLocation: FC<{
...
   const env = useEnv();
   const isMobile = useIsMobile();
+  const startTime = useMemo(
+    () => new Date(removeOffset(event.start_time)),
+    [event]
+  );
+  const endTime = useMemo(
+    () => new Date(removeOffset(event.end_time)),
+    [event]
+  );
```
Comment (richardolsson) [inline src/features/organizations/pages/PublicEventPage.tsx:324]: Personally I would not have used `useMemo()` for this, because the operation is so light. But I don't mind it. 👍

**Review by richardolsson — APPROVED** [review]
Nice work! I have tried the preview build and I reviewed the code. I think this is ready to merge and I look forward to this bug being squashed. 🐛 🥾 

(I'm sorry about the violent analogy)

File: src/features/organizations/pages/PublicEventPage.tsx (hunk 1 above)
Comment (Jrende) [reply src/features/organizations/pages/PublicEventPage.tsx:324]: I've been corrupted by svelte, vue etc. in that I want a function that makes a reactive value depending on other state, (derived in svelte, computed in vue) and i think useMemo is the closest to that. But yeah, it's probably overkill, maybe even slower for a case like this.
