### PR TITLE
Issue 1934/better unexpected errors

### LINKED ISSUE #1934: Better reporting of unexpected errors from the importer
See the comments below.

## Description
When trying to import a file that was exported from another Zetkin organization and after resolving errors related to e.g. phone formatting, I clicked the Validate button and expected to see the validation screen. Instead however nothing happened and the console log printed the `INVALID_COUNTRY` error.

## Steps to reproduce
1. Go to import for organization 978
2. Use the file provided (I will upload it on Slack, it contains some real people as well, search for the issue #)
3. Choose the appropriate fields for all the fields.
4. Click validate

### Expected Behaviour
Any potential errors should be visible or it should say everything is fine and it should give me the option to proceed with the import.

### Actual Behaviour
Nothing happens in the UI. Instead `INVALID_COUNTRY` is printed. This is also printed if Country is not imported.

## Other information
This appears to be a frontend validation issue, because no upload of the data to `/preview` was triggered.

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR adds a more user-friendly flow when the Import has unexpected errors. 

## Screenshots
image

## Changes
* Adds a new type of problem called "UNEXPECTED_ERROR" and it's definition.
* Adds try/catch clauses in `useConfigure ` hook to report the unexpected error as a message for the user.

## Notes to reviewer
None

## Related issues
Resolves #1934

### CODE REVIEW

File: src/features/import/l10n/messageIds.ts [hunk 1]
```diff
@@ -285,6 +285,12 @@ export default makeMessages('feat.import', {
         ),
         title: m('You have not configured identifying columns'),
       },
+      unexpectedError: {
+        description: m(
+          'No people have been imported. You can go back and check the import settings or select a new file to import. There were errors in the form you submitted. Please try again and make sure you fill in all the necessary information. If the error persist you can contact support at info@zetkin.org'
```
Comment (ziggabyte) [inline src/features/import/l10n/messageIds.ts:290]: Thinking a bit about this text... I think it could be a bit shorter. my suggestion: 

"Please go back and check the settings you've made, or select a new file to import. If the error persist you can contact support at info@zetkin.org"

**Review by ziggabyte — DISMISSED** [review]
Nice work! 
But, in Kika & Käka, was it not decided to also add a timestamp to the header, like this? 
bild

**Comment by richardolsson** [comment]
> Nice work! 
> But, in Kika & Käka, was it not decided to also add a timestamp to the header, like this? 
> bild
> 

I told @rebecarubio not to do this because we need to think about it some more IMO. Was that your only concern @ziggabyte ?

**Comment by ziggabyte** [comment]
> I told @rebecarubio not to do this because we need to think about it some more IMO. Was that your only concern @ziggabyte ?

That was my only thought, that I rememberd the conversation about it and didn't see it in the PR!

File: src/features/import/hooks/useConfigure.ts [hunk 2]
```diff
@@ -36,44 +63,46 @@ export default function useConfigure(orgId: number) {
...
-        ops: importOperations,
-      });
+      let importOperations;
+      try {
+        importOperations = prepareImportOperations(
+          configuredSheet,
+          countryCode
+        );
+      } catch (error) {
+        addUnexpectedErrorToProblems();
```
Comment (richardolsson) [inline src/features/import/hooks/useConfigure.ts:77]: Don't we have to return here? If we catch this error and then proceed, `importOptions` should be undefined but on line 81 we will still try to submit it to the server. I think we need to stop here by returning.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work on this! This will be a great improvement. I've looked at the code now and it looks mostly great, but I _think_ I found a potential bug. Can you confirm @rebecarubio?

File: src/features/import/hooks/useConfigure.ts (hunk 2 above)
Comment (rebecarubio) [reply src/features/import/hooks/useConfigure.ts:77]: I agree! I will make the change!

File: src/features/import/hooks/useConfigure.ts [hunk 3]
```diff
@@ -36,44 +63,46 @@ export default function useConfigure(orgId: number) {
...
-        ops: importOperations,
-      });
+      let importOperations;
+      try {
+        importOperations = prepareImportOperations(
+          configuredSheet,
+          countryCode
+        );
+      } catch (error) {
+        return addUnexpectedErrorToProblems();
```
Comment (richardolsson) [inline src/features/import/hooks/useConfigure.ts:77]: To me, the way you have done this is confusing, because it implies to me that `addUnexpectedErrorToProblems()` is a function that returns _something_ and that we want to pass that _something_ on by returning it again from here.

But in reality. `addUnexpectedErrorToProblems()` is a void function, it returns nothing. And that's also true for this (unnamed) function, where this code exists. So I think it would be better to explicitly return nothing, and to not do anything with the (nonexistent, empty, undefined) return value from `addUnexpectedErrorToProblems()`. Like so:

```suggestion
        addUnexpectedErrorToProblems();
        return;
```

**Review by richardolsson — CHANGES_REQUESTED** [review]
Ok, almost there, but I think the return should be done differently to make the code less ambiguous. See comment below.

**Review by richardolsson — APPROVED** [review]
Ok cool! It's time to merge. 💯 

Nice work @rebecarubio and @ziggabyte!
