### PR TITLE
fix (smartSearch): filter available lists by the selected traget org

### LINKED ISSUE #3475: {SmartSearch}: when looking for people in a sub organization, all lists from parent are retrieved instead of lists from the child
### The feature

Smart Search option to add people based on their belonging to another list (Add people / Cross referencing / People from a list)

### The bug

When selecting people from a specific organisation, then the lists drop down menu offers all lists from the current organisation, instead of lists of the targeted organisation, making the function very hard to use, especially for very big organisations with lots of sub orgs

Image

## Steps to reproduce

**Be detailed, volunteers need to know exactly how to reproduce!**

1. Go to https://app.dev.zetkin.org/organize/1/people/lists/730
2. Click on Add People 
3. Cross referencing
4. People form a list
5. Select on the top left "specific organisation"
6. Select an org 
7. In the drop down "Add people who are in the list...": all of the lists are mentioned instead of the ones from the one of the suborg

### Expected Behaviour

Only lists of the selected org should be displayed

### PR DESCRIPTION
**Pull request by theozanchi**
## Description
This PR allows organisers to only see the lists of a specific target organisations when filtering a smart search module

## Screenshots
Before: all lists of the current organisation are showed within a smartSeach dialog: 
Screenshot 2026-02-15 at 10 56 47

After: only the lists of the selected orgs on the top left box are dispalyed within the smartsearch
Screenshot 2026-02-15 at 16 38 00

## Changes

* Adds a new hook `useSubOrgsViewTrees` within the views hooks 
* Uses this hook within the SmartSearch PersonView index.tsx

## Related issues
Resolves #3475

### CODE REVIEW

**Review by ziggabyte — CHANGES_REQUESTED** [review]
This is super cool and it will be a great addition for the organisers :D 

There are two improvements I'm going to ask you to make. 

The first one is about using the `ViewTreeData` type and getting data from that endpoint. That type was created when building the `ViewBrowser` - aka the page with the list of folders and individual lists. 

For your purposes here it would be much simpler (and get you the same result) to just call `api/orgs/[orgId]/people/views` which will get you all the views of that org, of the type `ZetkinView`

This also means that the `Record<number, ViewTreeData>` on the store should change to `Record<number, ZetkinVeiw>`. 

The second feedback is commented below! 

Does this make sense?

**Review by ziggabyte — APPROVED** [review]
To me this looks great, and when I play with it it works just as expected! 

It also paves the way for making these upgrades to using records instead of lists in a bunch of places across the code. 

The only feedback I think of is that you are using the `then`-pattern, and we generally prefer the `async/await` pattern in `useSubOrgViews`, but i absolutely do not think this is a blocking thing, but if you want to you can ofc update it :)

**Review by ziggabyte — CHANGES_REQUESTED** [review]
I looked into why the tests are failing, and this is the console output when I run the `add-row` test (I just picked one of the failing tests, no particular reason this one). `items` is undefined, i think.

Image

Do you want to look into how to initialise `items` so they are not undefined?

**Review by ziggabyte — APPROVED** [review]
Great job getting all of this done! It's been so needed and it's wonderful that you took the time to do all this :D 

From having played with this, to me it seems to do everything as it should. Since it's a very important feature, I just want to let one more person play with it to see if they can provoke any bugs, but I'll press approve now and merge as soon as i have!

**Review by ziggabyte — CHANGES_REQUESTED** [review]
A bug was found by @laurablum and has been communicated!

File: src/features/smartSearch/components/filters/PersonView/index.tsx [hunk 1]
```diff
@@ -47,10 +47,10 @@ const PersonView = ({
   const filterScope = filter.config.organizations || [orgId];
 
   const orgIds = useOrgIdsFromOrgScope(orgId, filterScope);
-  const viewsFuture = useSubOrgViews(orgIds, filterScope);
+  const viewsFuture = useSubOrgViews(orgIds);
 
   const personViews = viewsFuture.data || [];
-  const personViewsSorted = personViews.sort((pv1, pv2) => {
+  const personViewsSorted = [...personViews].sort((pv1, pv2) => {
```
Comment (ziggabyte) [inline src/features/smartSearch/components/filters/PersonView/index.tsx]: `personViews` is already an array here, so `[...]` adds a bit of confusion i think :)
