### PR TITLE
Persistence of view column ordering.

### LINKED ISSUE #1039: View column order changes not persistent
Changing view column order is not persistent.

## Steps to reproduce
1. Create a new view
2. Drag "First name" column to the right of the "Last name" column
3. Reload

### Expected Behaviour
Expected "Last name" column to still be to the right the "First name" column.

### Actual Behaviour
The "First name" column is on the left of the "Last name" column after reloading. Changing the column order does not make a PATCH to `/orgs/{org_id}/people/views/{view_id}/column_order` which is the resource responsible for maintaining column order. 

The resource takes data in the following format:
```
{
  order: [2, 1, 3]
}
```
where the numbers are the ids of the columns, and the order of the ids is the order of the columns.

### PR DESCRIPTION
**Pull request by niklasva82**
## Description
This PR adds persistence to column ordering by PATCHing the column_order of the view/list.

## Screenshots
[Screencast from 2023-09-18 22-26-31.webm](https://github.com/zetkin/app.zetkin.org/assets/14962107/59dbd980-615e-44a5-a2a2-ea3b7406a257)

## Changes
* Adds a PATCH to `people/views/{view_id}/column_order` every time a column is moved.

## Notes to reviewer
Originally, the column order was changed in the state as well, but this resulted in problems with rendering (see https://github.com/mui/mui-x/issues/5704), so now the redux state is not updated. This also means the bug where sorting resets the order persists. Not sure how to fix this issue.

Additionally, debouncing could be a good thing to add, this is because it seems there is no event for when the column dragging is finished, instead it's fired on each step, so if you're dragging the column multiple columns over, this will update the column once for every step. This seems unnecessary and could cause a race condition if the events are fired in fast succession and something causes the first request to be slower than the second.

## Related issues
Resolves #1039

### CODE REVIEW

**Comment by niklasva82** [comment]
Added debouncing to keep requests to a reasonable level. But there was still a problem with the rendering when changing the columns in the redux state. So instead I chose to keep track of the new column order in the component. Of course when the page is reloaded, the columns from the redux state (provided as a prop to the ViewDataTable) are again in the correct order according to the new order.

**Review by ziggabyte — DISMISSED** [review]
This is a tricky one to crack!

I have began testing it to see how it works, and I am having some unexpected behaviour: the first time I move a column it works fine, but when dropping the second column the first moves back to it's original place. Not sure what causes it, but I think it should be fixed before further review.

https://github.com/zetkin/app.zetkin.org/assets/58265097/71075ba0-c54e-471a-890b-e881f70f55f4

**Comment by niklasva82** [comment]
I believe I know what's wrong. The "origin" is the order of the columns in the redux state, and I don't think it checks for a local state order when it creates the new order array, so it's reset when a second column reordering is made. This should be a simple fix, I will get to it tomorrow.

**Comment by niklasva82** [comment]
The bug above has been fixed and the typing error that the CI caught.

**Review by richardolsson — CHANGES_REQUESTED** [review]
I get this error when I try to move a column (in a view/list that has many different kinds of columns).

image

Also, it seems like these changes have introduced another bug, which is that when I add a column, it content of the view does not reload to reflect the new column. I have to refresh the page to see the newly added column.

File: src/features/views/repos/ViewDataRepo.ts [hunk 1]
```diff
@@ -174,6 +174,17 @@ export default class ViewDataRepo {
...
 
+  async updateColumnOrder(
+    orgId: number,
+    viewId: number,
+    columnOrder: number[]
+  ) {
+    await this._apiClient.patch<{ order: number[] }>(
+      `/api/orgs/${orgId}/people/views/${viewId}/column_order`,
+      { order: columnOrder }
+    );
```
Comment (richardolsson) [inline src/features/views/repos/ViewDataRepo.ts:185]: This makes the correct API request, but it does not in any way affect the local store. I reckon the state in the local store needs to either be modified to reflect the new state, or marked as stale so that it's reloaded, right? Otherwise I think this would explain the quirky behavior.

Comment (niklasva82) [reply src/features/views/repos/ViewDataRepo.ts:185]: Actually no, I don't use the local store. The reason for this is that I figured syncing two different persistent states would make things just that much more difficult. Instead I use the local state for the temporary order of columns. But yes, it appears that I failed to take new columns into account, I need to check for new columns and integrate the new column into the columnOrder.

**Comment by niklasva82** [comment]
Reimplemented using redux store. Everything seems to work now!
[Screencast from 2023-09-30 04-09-21.webm](https://github.com/zetkin/app.zetkin.org/assets/14962107/ca9bb3f5-8880-4815-abeb-d0f9697728fa)

File: src/features/views/store.ts [hunk 2]
```diff
@@ -152,12 +152,10 @@ const viewsSlice = createSlice({
...
     },
     columnAdded: (state, action: PayloadAction<[number, ZetkinViewColumn]>) => {
-      const [viewId, column] = action.payload;
+      const [viewId] = action.payload;
       const colList = state.columnsByViewId[viewId];
       if (colList) {
-        colList.items = colList.items.concat([
-          remoteItem(column.id, { data: column }),
-        ]);
+        colList.isStale = true;
```
Comment (richardolsson) [inline src/features/views/store.ts:158]: Why is this necessary? Adding a column was working before this PR, right? So why not keep the old logic for just concatenating it to the end of the list of columns?

File: src/features/views/store.ts [hunk 3]
```diff
@@ -180,6 +178,46 @@ const viewsSlice = createSlice({
...
+      const [viewId, columnOrder] = action.payload;
+      // Re-arrange columns
+      const colList = state.columnsByViewId[viewId];
+      if (colList) {
+        const newColListItems = columnOrder.map((colId) => {
+          const col = colList.items.find((col) => col.id == colId);
+          if (col) {
+            return col;
+          } else {
+            throw new Error('Could not find column!');
```
Comment (richardolsson) [inline src/features/views/store.ts:191]: This should never happen, but if it does, it will now crash the app. Instead of throwing an error and crashing, wouldn't it be better to just mark the column list as stale and force it to reload?

File: src/features/views/store.ts (hunk 2 above)
Comment (richardolsson) [reply src/features/views/store.ts:158]: I tried changing back to the previous code and it still worked fine. So if you can please explain why you found this change to be necessary I'd appreciate that.

File: src/features/views/store.ts [hunk 4]
```diff
@@ -180,6 +178,46 @@ const viewsSlice = createSlice({
...
+                },
+              };
+            } else {
+              return row;
+            }
+          });
+          state.columnsByViewId[viewId].items = newColListItems;
+          state.rowsByViewId[viewId].items = newRowListItems;
+        }
+      }
```
Comment (richardolsson) [inline src/features/views/store.ts:219]: Beautiful! This is a big improvement over Gen2 where the data had to be reloaded after reordering columns. Nice work!

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work on the new redux store logic! I only question two minor parts of it. If you can respond to this asap that would be great, so that we can get this in the release this weekend.

**Comment by niklasva82** [comment]
The colList isStale is because I discovered that if you have the view in
two browser tabs, add a tab in one tab and then add a tab in the other, it
will fech more columns for the data than the number of columns in the
header. Very specific I know, but I figured there was no harm in refreshing
the columns when you were already refreshing the data.

Good idea about the install on error, I will fix that.


Den lör 30 sep. 2023 06:37Richard Olsson ***@***.***> skrev:

**Comment by richardolsson** [comment]
> The colList isStale is because I discovered that if you have the view in two browser tabs, add a tab in one tab and then add a tab in the other, it will fech more columns for the data than the number of columns in the header. Very specific I know, but I figured there was no harm in refreshing the columns when you were already refreshing the data. Good idea about the isStale on error, I will fix that.

I accept the motivation behind `colList.isStale` even if it feels to me like there should be some better solution available (e.g. marking as `isStale` only after a failure or unexpected response) but this is good enough for the time we have.

I will push a fix to the error handling, and then proceed and merge.

**Review by richardolsson — APPROVED** [review]
I feel like this is ready to merge now! I enjoyed the teamwork!
