### PR TITLE
Issues 538 & 539:  hide watch video task type, fix bug not sending config

### LINKED ISSUE #539: Hide `watch_video` task type
We need to hide the `watch_video` task type for R30 because it will not make it into the front-end in time.

### PR DESCRIPTION
**Pull request by djbusstop**
## Changes
- Removes `TASK_TYPE.WATCH_VIDEO` from list of available task types in the task details form
- Fixes bug that sends an empty config when creating a new task
  - Adds playwright test to confirm that config is sent in the post request when creating a task.
  - Uses updated moxy. This moxy PR has been merged and published: https://github.com/zetkin/moxy/pull/9

## Related issues
Resolves #539, #538

### CODE REVIEW

File: src/components/ZetkinSpeedDial/actions/createTask.tsx [hunk 1]
```diff
@@ -21,7 +21,6 @@ const DialogContent: React.FunctionComponent<DialogContentBaseProps> = ({ closeD
         // Set defaults for config and target_filters
         const body: ZetkinTaskRequestBody = {
             ...task,
-            config: {},
```
Comment (richardolsson) [inline src/components/ZetkinSpeedDial/actions/createTask.tsx:24]: Oh, this was it!?

**Review by richardolsson — APPROVED** [review]
How annoying with this little `config` bug, but great fix with the test. 🙌

File: src/components/ZetkinSpeedDial/actions/createTask.tsx (hunk 1 above)
Comment (djbusstop) [reply src/components/ZetkinSpeedDial/actions/createTask.tsx:24]: lol yep but now it's tested :D
