### PR TITLE
fix: load avatars, while also allowing for filtering, in LocalPerson

### LINKED ISSUE #2631: Lists: Person id is `undefined` when getting avatar in LocalPerson column
### The feature

Lists are a central feature of the Zetkin platform. This is where the organizers keep track of their activists, and add different types of columns based on data they want to see or actions they want to take. 

One column type an organizer can add to a list of activists is a column for "Assigned person", where the organizer can type into each cell in the column and select a person to be displayed as "assigned". The column shows a grey "anonymous" avatar in cells without an assigned person, and a colored in avatar with initials when a person has been assigned in that cell. 

### The bug

When an organizer selects a person to be assigned in that cell, currently the api request to get the avatar fails, so even though the organizer has assigned a person, they still see the grey "anonymous" avatar instead of the avatar of the assigned person. Meaning, they don't get any visual feedback that a person has been assigned, even though someone has.

NOTE: this bug does only seem to be reproducable on `app.dev.zetkin.org`, because when I do it locally on `localhost:3000` things seem to work as they should

## Steps to reproduce

1. Go to a list, http://app.dev.zetkin.org/organize/1/people/lists/2
2. Click on "New column" 
3. In the dialog that opens, select "Assigned person" in the "Outreach" section.
4. See that the new column has been added to the list, and that it displays an "anonymous" avatar in each cell
5. Double-click in one of the cells and start typing to search for a person ("Anna" for example)
6. Click on one of the people in the search results to select them as assigned 

### Expected Behaviour
- The avatar of the person you just selected is immidiately visible in the cell

### Actual Behaviour
- The anonymous avatar is still visible
- Looking in the network panel when adding an assigned person, you get 404 from the `GET` request to get the avatar because the id of the person is `undefined`:  `/api/orgs/1/people/undefined/avatar`

## Screenshots

Image

### PR DESCRIPTION
**Pull request by ajoensson**
## Description
Before these changes, avatars would not load properly in LocalPerson, because when we added the valueGetter to make filtering work, the properties that the other functions relied on disappeared. In an ideal world, this would be caught by the Typescript types, but I wasn't able to get them to work. Instead, this commit alters the valueGetter so that it keeps all existing properties, and adds a toString-method, which works with the filter functionality.

## Screenshots
Both filter and avatar works:
image

## Changes
* Modify the `valueGetter` to add a `toString`-method rather than overwrite the entire value.

## Related issues
Resolves #2631
Relates to #2581

### CODE REVIEW

File: src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx [hunk 1]
```diff
@@ -57,7 +57,15 @@ export default class LocalPersonColumnType
         return makeName(v1).localeCompare(makeName(v2));
       },
       valueGetter: (params) => {
-        return params.value ? makeName(params.value) : '';
+        // we add a `toString`-method, which will be used when filtering for LocalPersons
+        return params.value
+          ? {
+              ...params.value,
+              toString() {
```
Comment (ziggabyte) [inline src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx:64]: This is such a smart solution! How did you figure out to do it this way? It's so neat!

**Review by ziggabyte — APPROVED** [review]
This works just as expected, and is a million times better than  my stress-suggested solution of 3000 lines of code 😅 

I'm gonna merge this now, but I would be so curious to learn how you came up with this solution!
