### PR TITLE
issue-1686/navigate event

### LINKED ISSUE #1686: Navigating to event page after creating it
## Description
Creating an event from the "Create activity" menu creates the event but does not navigate to the event page the way that creating a call assignment or survey from the same menu does.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/1
2. Click on "Create activity"
3. Click on "Create event"

### Expected Behaviour
An event should be created, and the user should be redirected to the page of the new event

### Actual Behaviour
The event is created, and it shows up in the "Tomorrow" box, but no redirection is happening so the user must click the event to navigate to it and fill out all the missing data.

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR fixes a bug that page doesn't navigate to newly created event page.

## Screenshots

https://github.com/zetkin/app.zetkin.org/assets/77925373/603133e5-2baf-4131-9584-31cb2f4ab808

## Changes

* Adds `listenerMiddleware`

## Related issues
Resolves #1686

### CODE REVIEW

File: src/core/store.ts [hunk 1]
```diff
@@ -103,6 +106,16 @@ listenerMiddleware.startListening({
   },
 });
 
+listenerMiddleware.startListening({
+  actionCreator: eventCreated,
+  effect: (action) => {
+    const event = action.payload;
+    Router.push(
+      `/organize/${event.organization?.id}/projects/${event.campaign?.id}/events/${event.id}`
```
Comment (richardolsson) [inline src/core/store.ts:114]: This breaks when creating an event that isn't part of a project, like this:

1. Go to calendar
2. Go to week view
3. Drag to create a block in the calendar
4. Click "Create single event"

Expected results:
Should navigate to new event page.

Actual results:
Navigates to new event page, but then also quickly after navigates to URL where campaign ID is `undefined` (e.g. /organize/1/projects/undefined/events/82).

There is already code on `main` to redirect to a newly created event after creating it in the calendar. That code does not use this middleware approach. I'm not sure which I prefer, but regardless, there should only be one piece of code that does the same thing (right now two redirects are happening).

And regardless of where the redirect happens, it needs to account for events outside of projects. The easiest way to do that is to use the `getEventUrl()` utility function.

**Review by richardolsson — CHANGES_REQUESTED** [review]
This fixes the bug which is nice, but it also introduces another bug. More details in my comment below. Message me if you're not sure what I'm trying to get across in my message, because I'm struggling to explain it well. 😊

File: src/core/store.ts (hunk 1 above)
Comment (kaulfield23) [reply src/core/store.ts:114]: Aha that was why there was no middleware for eventCreated! Thank you!

File: src/features/events/hooks/useCreateEvent.ts [hunk 2]
```diff
@@ -20,6 +21,10 @@ export default function useCreateEvent(orgId: number): useCreateEventReturn {
       eventBody
     );
     dispatch(eventCreated(event));
+    env.router.push(
+      `/organize/${orgId}/projects/${event.campaign?.id}/events/${event.id}`
```
Comment (richardolsson) [inline src/features/events/hooks/useCreateEvent.ts:25]: I think we should always use the `getEventUrl()` utility to generate event URLs.

**Review by richardolsson — CHANGES_REQUESTED** [review]

File: src/features/events/hooks/useCreateEvent.ts (hunk 2 above)
Comment (kaulfield23) [reply src/features/events/hooks/useCreateEvent.ts:25]: okay!

**Review by richardolsson — APPROVED** [review]
LGTM now!
