### PR TITLE
Issue 974/error when adding columns

### LINKED ISSUE #974: Error when adding columns
## Description
Adding some columns to a view raises an exception. Refreshing the page solves it, and I think the reason the error is occurring is that if the column is added before the updated view rows are able to reload, the cells in the new column will try to render without any data, throwing an exception.

## Steps to reproduce
1. Go to any view that contains only the most basic columns (first name and last name)
2. Add a `survey_options` column

### Expected Behaviour
Should add the column and render it's contents

### Actual Behaviour
Throws an exception

## Screenshots
image

## Proposed solution
Every column type must handle the case where it's cell is `undefined`. Change the types in all `IColumnType` implementations so that `cell` can be `undefined`, and handle the typescript errors. The simplest (and entirely acceptable) solution should be to just do this in every cell renderer where typescript complains:

```ts
if (!cell) {
  return null;
}
```

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR fixes the bug when adding the new column types in Views, handling the exception when the cell is undefined. It also fixes another bug in `SurveyOptionsColumnType` allowing the array `cell `to be concatenated before it´s sorted.

## Screenshots
https://user-images.githubusercontent.com/36491300/217559963-ff1bf3a4-7d68-4c97-9f31-38a5a47b81a7.mp4

## Changes
* Adds type `undefined ` in cell in the IColumnType implementations
* Adds function to checked of if cell is undefined and handles the exception (in the Column types that are necessary)
* Adds concat() function in the cell array in  `SurveyOptionsColumnType` before it´s sorted.

## Notes to reviewer
[Add instructions for testing]

## Related issues
Resolves #974

### CODE REVIEW

File: src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx [hunk 1]
```diff
@@ -75,18 +75,21 @@ const useStyles = makeStyles((theme) => ({
...
+  cell: SurveyOptionsViewCell | undefined;
 }> = ({ cell }) => {
   const { orgId } = useRouter().query;
   const styles = useStyles();
   const [anchorEl, setAnchorEl] = useState<HTMLElement | null>(null);
   const { openPane } = usePanes();
 
+  if (!cell) {
+    return null;
+  }
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx:87]: Instead of adding a separate if statement like this, the next one could be `if (cell?.length == 0)`, thereby catching if `cell` is falsy, or if it has zero length.

File: src/features/views/components/ViewDataTable/columnTypes/SurveyResponseColumnType.tsx [hunk 2]
```diff
@@ -55,12 +55,16 @@ const useStyles = makeStyles({
...
 });
 
-const Cell: FC<{ cell: SurveyResponseViewCell }> = ({ cell }) => {
+const Cell: FC<{ cell: SurveyResponseViewCell | undefined }> = ({ cell }) => {
   const { orgId } = useRouter().query;
   const styles = useStyles();
   const [anchorEl, setAnchorEl] = useState<HTMLElement | null>(null);
   const { openPane } = usePanes();
 
+  if (!cell) {
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/SurveyResponseColumnType.tsx:64]: Same thing here as commented above, regarding the optional chaining operator.

File: src/features/views/components/ViewDataTable/columnTypes/SurveySubmittedColumnType.tsx [hunk 3]
```diff
@@ -34,10 +34,14 @@ export default class SurveySubmittedColumnType
   }
 }
 
-const Cell: FC<{ cell: SurveySubmittedViewCell }> = ({ cell }) => {
+const Cell: FC<{ cell: SurveySubmittedViewCell | undefined }> = ({ cell }) => {
   const { orgId } = useRouter().query;
   const { openPane } = usePanes();
 
+  if (!cell) {
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/SurveySubmittedColumnType.tsx:41]: Same thing again concerning the optional chaining operator.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Looking great! As usual, I have some annoying little code style comment, and this time it's about how the code could be simplified in three places using the optional chaining operator.

File: src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx (hunk 1 above)
Comment (rebecarubio) [reply src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx:87]: ahhh so much nicer! I´ll change it asap

File: src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx [hunk 4]
```diff
@@ -75,18 +75,18 @@ const useStyles = makeStyles((theme) => ({
...
-  cell: SurveyOptionsViewCell;
+  cell: SurveyOptionsViewCell | undefined;
 }> = ({ cell }) => {
   const { orgId } = useRouter().query;
   const styles = useStyles();
   const [anchorEl, setAnchorEl] = useState<HTMLElement | null>(null);
   const { openPane } = usePanes();
 
-  if (cell.length == 0) {
+  if (!cell || cell?.length == 0) {
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx:85]: I see that the change you made is not what I suggested, which is probably because you got a type error when trying to compare something that may be `undefined` (`cell?.length`) with something that is a number (`0`).

That was my mistake when I wrote my suggestion freehand. You would likely need to do this:

```
if (!cell?.length) {
```

Because that is the equivalent of doing `if (!(cell && cell.length)))`.

If that works, I think it would be nicer, but it doesn't really matter, so I'll merge this now to avoid some other merge conflicts.

**Review by richardolsson — APPROVED** [review]
I've clarified something in my comment below, but the code looks fine and I see no reason not to merge it!
