### PR TITLE
Issue 1299/add breadcrumbs to no title events

### LINKED ISSUE #1299: Event breadcrumb disappears when event has no title
## Description
Events don't have to have a custom (user-submitted) title. When they don't, they should fall back to use the title of the event type (`event.activity.title`).

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/1/events/115
2. If there is a title other than the type, click the title (currently "Jump") and erase it
3. Refresh the page and look at the breadcrumbs

### Expected Behaviour
Should end with the word "Jump", which is the de facto title of the event when no custom title is assigned.

### Actual Behaviour
Ends with "Events", the segment before the actual event. If the event has a title, it's displayed here.

## Screenshots
image

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR adds the event activity title as breadcrumbs when the event doesn't have set a custom title.

## Screenshots
image

## Changes
* Adds the `event.data.activity.title` to be displayed when the event doesn't have a custom title setted.

## Notes to reviewer
This PR contains other commits made by a volunteer because I checkout from his opened branch.

## Related issues
Resolves #1299

### CODE REVIEW

File: src/pages/api/breadcrumbs.ts [hunk 1]
```diff
@@ -182,7 +182,7 @@ async function fetchElements(
     return [
       {
         href: basePath + '/' + fieldValue,
-        label: event.data.title,
+        label: event.data.title || event.data.activity.title,
```
Comment (richardolsson) [inline src/pages/api/breadcrumbs.ts:185]: Simple! 🎯

**Review by richardolsson — APPROVED** [review]
Confirmed to work! Nice fix. 😊
