### PR TITLE
Use hooks and redux for breadcrumbs

### LINKED ISSUE #524: Breadcrumbs not updated when title of view changes
## Description
The breadcrumbs are not updated when a view is renamed. The same is probably true for other types of objects.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Create a new view
3. Click the title to edit it
4. Change the title (e.g. to "Renamed view") and press enter to save

### Expected Behaviour
Title should update both in the headline and in the breadcrumbs.

### Actual Behaviour
Title is only updated in the headline, but not in the breadcrumbs.

## Proposed solution
The wireframes don't actually include the title of the current page in the breadcrumbs, since it's already displayed right below it. I think that makes sense, and maybe it's easier to just remove it than to try and update it.

But then we also need to make sure the title makes a comeback in the breadcrumbs when the header is collapsed.

## Screenshots
image

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR migrates the breadcrumbs to use a redux store and hooks.

## Screenshots
None

## Changes
* Moves the breadcrumbs to a feature directory
* Replaces legacy `react-query` loading for breadcrumbs with store
* Invalidates breadcrumbs when any "updated" action is dispatched (resolves #524)

## Notes to reviewer
None

## Related issues
Related to #1542
Resolves #524

### CODE REVIEW

File: src/features/breadcrumbs/hooks/useBreadcrumbs.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+import { crumbsLoad, crumbsLoaded } from '../store';
+import { NextRouter, useRouter } from 'next/router';
+import { useApiClient, useAppDispatch, useAppSelector } from 'core/hooks';
+
+export default function useBreadcrumbElements() {
+  const apiClient = useApiClient();
+  const dispatch = useAppDispatch();
+  const router = useRouter();
+  const path = router.pathname;
+  const item = useAppSelector((state) => state.breadcrumbs.crumbsByPath[path]);
```
Comment (ziggabyte) [inline src/features/breadcrumbs/hooks/useBreadcrumbs.ts:12]: i'm being very specific now, but I would love for this to have a more clear name to say what type of item it is!

File: src/features/breadcrumbs/hooks/useBreadcrumbs.ts [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+      return { elements, id: path };
+    },
+  });
+
+  return future.data?.elements ?? [];
+}
+
+const getQueryString = function (router: NextRouter): string {
+  // Only use parameters that are part of the path (e.g. [personId])
+  // and not ones that are part of the actual querystring (e.g. ?filter_*)
```
Comment (ziggabyte) [inline src/features/breadcrumbs/hooks/useBreadcrumbs.ts:33]: This is also being very detailed, but I'm finding the name of this function contradictory to what the comment says - the name is `getQueryString` but the comment says "..not ones that are part of the actual querystring". Would it not be more clear to name the function something like `getPathParameters`?

File: src/features/breadcrumbs/store.ts [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+
+function isUpdatedAction(action: Action<string>) {
+  return action.type.endsWith('Updated');
+}
+
+const breadcrumbsSlice = createSlice({
+  extraReducers: (builder) => {
+    builder.addMatcher(isUpdatedAction, (state) => {
+      // In lieu of a general-purpose way of identifying what changed, when
+      // anything is updated, we invalidate all breadcrumbs.
```
Comment (ziggabyte) [inline src/features/breadcrumbs/store.ts:26]: Would this be something to mark as a "TODO" comment? Or is the need for this type of identification noted somewhere else?

File: src/features/breadcrumbs/hooks/useBreadcrumbs.ts [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+
+  const future = loadItemIfNecessary(item, dispatch, {
+    actionOnLoad: () => crumbsLoad(path),
+    actionOnSuccess: (item) => crumbsLoaded([path, item]),
+    loader: async () => {
+      const elements = await apiClient.get<BreadcrumbElement[]>(
+        `/api/breadcrumbs?pathname=${path}&${query}`
+      );
+
+      return { elements, id: path };
```
[the remark this answers is not in the document]
Comment (kaulfield23) [reply src/features/breadcrumbs/hooks/useBreadcrumbs.ts:24]: Wow this one looks so nice!

File: src/features/breadcrumbs/hooks/useBreadcrumbs.ts (hunk 2 above)
Comment (richardolsson) [reply src/features/breadcrumbs/hooks/useBreadcrumbs.ts:33]: Yes, I agree! I just reused it from the old code but you're right that it's a bad name. Will fix!

File: src/features/breadcrumbs/store.ts (hunk 3 above)
Comment (richardolsson) [reply src/features/breadcrumbs/store.ts:26]: I don't consider this a TODO (because I don't think it needs to be done). It wouldn't be bad to have it, but I'm not sure how we would solve it so the cost/benefit for me means I don't think we need to do anything about it.

**Review by ziggabyte — APPROVED** [review]
Let's gooooooooo!!!
