### PR TITLE
Issue-1067: add personHoverCard to person grid cell to display on hover

### LINKED ISSUE #1067: Polish, bugs and tweaks
- [ ] Research why it’s slow to retrieve projects on live data
- [ ] Lots of little problems with the linking widget that have made apparent in submissions tab @rebecarubio 
- [x] Solve the Pane height isssue
- [x] Link in activities tab to archive when there are no live activities but there are archived ones
- [x] Fix missing internationalization for "Share" and "Download" tabs in View share dialog
- [x] Niklas comment about “Activities” in All Projects - a header? renaming the Activities tab here to something like “uncategorized activities” etc.
- [x] Add an Archives tab for activities
- [x] Question / Text blocks cover the calendar in survey
- [x] Should we add a _beta_ label somewhere, e.g. over the logo?
- [x] Consider redirecting "campaign" URLs to the equivalent "project" URLs
- [x] Do the little things left from MU5 migration polish task
- [x] Loading state on Overview and Activities tabs before data is fetched 
- [x] Make sure that all surveys created are configured to disallow anonymous submissions
- [x] In /organize landing page substitute the ZUIList by a regular List 
- [x] MUI4 remove completely?
- [x] It looks like the small status bars (in overview) for tasks show the wrong numbers (green and blue mixed up) 
- [x] We should probably collapse options in the survey editor when there are many?
- [x] Call assignment instructions are not formatted correctly
- [x] Drag and drop can't drag a short questions past the bottom one if it's taller 
- [x] Change colors of `ZUIStackedStatusBar` in call assignment to be orange, blue, green (instead of orange, green, blue)
- [x] Weirdness on the Conversation tab of Call Assignments: wrong font + no padding  in subheader, and title has that old EditTextInPlace width problem
- [x] Linking the last unlinked submission needs to take you out of filtering
- [x] ZUIHoverCard hovers over avatar in SurveySubmissionList, preventing click to change linked person
- [x] The survey submission pane (and any other pane) does not respect height of window, but height of page
- [x] Add CTA to `ZUIEmptyState` and use on project overview to direct to activities tab if no activities this week
- [x] Remove space at top of survey overview page
- [x] There should be a placeholder when bulk-adding options to explain how it works
- [x] Invalidate survey stats (set `isStale = true`) after linking a submission
- [x] Ziggi, fix this: 

Image

- [x] The house icon in the nav menu should lead to the /organize page 
- [x] There should be no menu on the /organize page 
- [x] `PersonHoverCard` is not showing up when hovering the linked person in the survey submissions list 
- [x] Can't edit folder title with edit text in place
- [x] The avatar column in a view should be "frozen" (I think?)
- [x] Some view column causes view to crash (probably unexpected null?)
- [x] Tag view columns are not downloaded correctly
- [x] #1077 
- [x] #1078
- [x] #1079
- [x] #1080
- [x] #1080

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR adds a personHoverCard to person grid cell to display the person details when the user hovers in the cell insubmission page.

## Screenshots
https://user-images.githubusercontent.com/36491300/225364052-9ee1d3ad-ba9a-495c-8011-b0e3feefc8cb.mp4

## Changes
* Adds `ZUIPersonHoverCard `component in `personGridCell `in `SubmissionsListpage`.

## Notes to reviewer
None

## Related issues
Part of #1067

### CODE REVIEW

**Comment by richardolsson** [comment]
When you put "resolves" before the ID in a PR, merging it closes this issue, which is not correct because the issue is not done just because one part of it is done. I have edited this issue, and reopened #1067.

**Comment by rebecarubio** [comment]
> When you put "resolves" before the ID in a PR, merging it closes this issue, which is not correct because the issue is not done just because one part of it is done. I have edited this issue, and reopened #1067.

Oh sure! I didn't though about that 😓 thanks for reopening!

File: src/features/surveys/components/SurveySubmissionsList.tsx [hunk 1]
```diff
@@ -124,10 +125,12 @@ const SurveySubmissionsList = ({
 
     if (row.respondent?.id) {
       return (
-        <ZUIPersonGridCell
-          onClick={startEditing}
-          personId={row.respondent.id}
-        />
+        <ZUIPersonHoverCard personId={row.respondent.id}>
```
Comment (richardolsson) [inline src/features/surveys/components/SurveySubmissionsList.tsx:128]: Nice solution! Another option would have been to put the `ZUIPersonHoverCard` inside the `ZUIPersonGridCell` so that it would also work for views, but on the other hand that might be error-prone, so I like this. 💯

**Review by richardolsson — APPROVED** [review]
Tried the feature, looked at the code, all looks great!
