### PR TITLE
Issue 1361/today tomorrow

### LINKED ISSUE #1361: "Today" and "Tomorrow" are showing yesterday and today
## Description
The `ActivitiOverview` component is showing events on the wrong days. The same may be true with other activities as well (not sure).

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects
2. Create a new event tomorrow
3. Go back to http://localhost:3000/organize/1/projects

### Expected Behaviour
The new event should be listed under "Tomorrow"

### Actual Behaviour
The event is listed under "Today"

## Screenshots
None

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR updates the logic for determining which events should go in the Today and Tomorrow columns in the project overview.

## Screenshots
bild

## Changes
* Adds logic to filter events on different criteria than other activities
* Changes start date property to use publish date, to get correct status dot color for events.

## Related issues
Resolves #1361

### CODE REVIEW

File: src/features/campaigns/models/CampaignActivitiesModel.ts [hunk 1]
```diff
@@ -102,17 +102,30 @@ export default class CampaignActivitiesModel extends ModelBase {
...
+      overview.today = currentActivities.filter((activity) => {
+        if (activity.kind == ACTIVITIES.EVENT) {
+          const startDate = new Date(activity.data.start_time);
+          return isSameDate(startDate, todayDate);
+        } else {
+          return (
+            (activity.startDate && isSameDate(activity.startDate, todayDate)) ||
+            (activity.endDate && isSameDate(activity.endDate, todayDate))
+          );
+        }
```
Comment (richardolsson) [inline src/features/campaigns/models/CampaignActivitiesModel.ts:114]: I guess, looking at it again, that this code could have been simplified just a little bit, but this is totally fine IMO.

**Review by richardolsson — APPROVED** [review]
This looks good to me! Let's go ahead and merge. 💯
