### PR TITLE
Blocks home/end in ZUIPersonSelect when shift-key is pressed

### LINKED ISSUE #1157: Cannot select entire text of ZUIPersonSelect
## Description
When typing to search for a person in the ZUIPersonSelect, e.g. to add new person to a view, it's not possible to hold shift and press home in order to select the entire text (in order to delete it).

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people/views
2. Click a view
3. Search for a new person at the bottom of the screen.
4. Hold shift and press Home

### Expected Behaviour
Select entire text.

### Actual Behaviour
Go to first/last person in list.

### Screenshot
bild

### Possible fix
Ignore the home/end buttons when the Shift button is pressed.

### PR DESCRIPTION
**Pull request by theo8theo8**
## Description
This PR fixes a problem where the text in ZUIPersonSelect was not able to be marked using shift+home (or end).
I chose to keep home/end being pressed without shift to still choose the first and last entry in the results. This is possible to change so that home/end only affects the input box. LMK if you'd rather have this.

## Changes
* Adds logic for detecting when shift is held down
* Uses this logic to send a prop to MUIAutocomplete choosing whether it should gain control of home/end or not.

## Related issues
Resolves #1157

### CODE REVIEW

File: src/zui/ZUIPersonSelect.tsx [hunk 1]
```diff
@@ -170,13 +194,14 @@ const MUIOnlyPersonSelect: FunctionComponent<ZUIPersonSelectProps> = (
...
-  const { name, placeholder, inputRef, ...restProps } = autoCompleteProps;
-
+  const { name, placeholder, inputRef, shiftHeld, ...restProps } =
+    autoCompleteProps;
   delete restProps.getOptionValue;
 
   return (
     <MUIAutocomplete
       {...restProps}
+      handleHomeEndKeys={!shiftHeld}
```
Comment (richardolsson) [inline src/zui/ZUIPersonSelect.tsx:204]: Nice find!

**Review by richardolsson — COMMENTED** [review]
I think the code looks good! @niklasva82 can you verify that this works for you?

**Review by niklasva82 — APPROVED** [review]
Great work! Verified to be working and fixing this annoying issue :)
