### PR TITLE
Fix pending signups number in Calendar Day View

### LINKED ISSUE #1353: Pending signups not correctly rendered in calendar day view
## Description
Events in the 

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/calendar?timeScale=week
2. Create an event by dragging in the calendar
3. Once on the event page, go to participants
4. Add two participants
5. Navigate back to the calendar
6. Switch to the day view and locate the event

### Expected Behaviour
The event should not indicate that there are any pending signups

### Actual Behaviour
The "raised hand" icon is shown, indicating that there are pending signups.

## Screenshots
image

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR fixes the bug in Calendar Day View by showing the pending sign-ups icon only when there is a pending sign-up.

## Screenshots
https://github.com/zetkin/app.zetkin.org/assets/36491300/7469be00-6f7b-47b7-a0f8-43c21db67ff8

## Changes
* Changes the number of sign-ups by calling the method `getPendingSignUps`
* Changes the condition to show the pending sign-up icon by getting it displayed if it's more than 0

## Notes to reviewer
None

## Related issues
Resolves #1353

### CODE REVIEW

File: src/features/events/components/EventWarningIcons.tsx [hunk 1]
```diff
@@ -32,7 +31,7 @@ const EventWarningIcons: FC<EventWarningIconsProps> = ({ compact, model }) => {
       numRemindersSent={
         participants.data?.filter((p) => !!p.reminder_sent).length ?? 0
       }
-      numSignups={data.num_participants_available}
+      numSignups={model.getPendingSignUps().length ?? 0}
```
Comment (richardolsson) [inline src/features/events/components/EventWarningIcons.tsx:34]: Same comment here as in #1358:

The `??` does nothing here, I don't think. According to the types, `model.getPendingSignUps()` always returns an array, and there are no optional chaining operators (`?`), so the nullish coalescing operator (`??`) has no effect. It should be possible to just do:

```suggestion
      numSignups={model.getPendingSignUps().length}
```

**Review by richardolsson — CHANGES_REQUESTED** [review]
Se comment below (same as your other current PR):

File: src/features/events/components/EventWarningIcons.tsx (hunk 1 above)
Comment (rebecarubio) [reply src/features/events/components/EventWarningIcons.tsx:34]: True, I will make the changes asap! Thanks!

**Review by richardolsson — APPROVED** [review]
Ready to merge! 💯
