### PR TITLE
Issue 1184 - Add start and end date & time, fix focus and styles in Event Overview Card

### LINKED ISSUE #1184: Add date and time in Event Overview Card (preview and edit state) 👀
## Description
A user should be able to select a start time and end time for the event, modify it and see them displayed in the preview.

Most events will start and end on the same day, so in the normal case we only display one date field.

## Relevant Job Stories
- When I’m organizing an event that spans over a full weekend, I want to be able to set the start and end times on different days, so that there are no misconception about the duration of the event

## Prerequisites
None

### Edit mode
- [x] Shows fields as indicated by design specifications below
  - [x] Date fields are MUI date pickers
  - [x] Time fields are MUI time fields (without popover pickers)
- [x] If event starts and ends on same day
  - [x] Shows only one date fields
  - [x] Shows a text button to toggle the second date field visible
    - [x] When clicked, shows the second date field, prefilled with date from `end_time`
- [x] Shows both date fields if event starts and ends on different days
- [x] If user tries to change the end date to before the start date, change the start date to match
- [x] When saving, set `start_time` and `end_time` of the event to the correct ISO datetimes

### Preview mode
- [x] Displays "Start" column on left hand side
  - [x] Includes date on first line
  - [x] Includes time on second line
- [x] Displays "End" column next to "Start" column
  - [x] Includes date on first line if different than start, otherwise empty
  - [x] Includes time on second line
- [x] Displays location and link on the right hand side

## Possible implementations
To be discussed with @yusf and @Bagera 

## Design specifications
🚨 **WARNING**: The designs for this have recently changed, resulting in the mockups below being somewhat contradicting. Please read the "Requirements" section above for the most up to date directions, and ask if unsure!

### Edit state
image
image

### Preview state
image

## Open questions
None

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR adds the start and end inputs to handle dates and times in events, in the preview and edit stage. It also fixes the styles to fit the design requirements and adds the focus logic to the different fields in edit stage. 
* Location field autofocus doesn´t work. It will be fixed in the issue -->  #1224

## Screenshots
**Preview mode**
- All fields completed
image

- Empty description and link
image

- Same start and end date
image

**Edit mode**
- Same start and end date
image

- Different start and end date
image

## Changes
**Edit mode**
- Adds date picker component for start and end date
- Adds timepicker (without popover) for start and end time
- When start date is the same as end date, we show a button that says "end date"
- Adds a validation check with a new function (isValidDate)
- Adds a function to check if end date is before start date called `endDateIsBeforeStartDate`

**Preview mode**
- Adds start and end date info (if they are different, otherwise we only show start date)
- Adds start and end time info
- Changes localization icon for Map

## Notes to reviewer
Some things are still to be discussed, like how to localize date formats etc.

## Related issues
Resolves #1184

### CODE REVIEW

File: src/utils/dateUtils.ts [hunk 1]
```diff
@@ -66,3 +66,14 @@ export function isInFuture(datestring: string): boolean {
...
 }
+
+export function isValidDate(date: Date): boolean {
+  if (date && !isNaN(date.getTime())) {
+    return true;
+  } else {
+    return false;
+  }
+}
+export function endDateIsBeforeStartDate(first: Date, second: Date): boolean {
```
Comment (richardolsson) [inline src/utils/dateUtils.ts:77]: I think this should just be called `dateIsBefore` or `dateIsAfter`, because this can be used for other things than start/end dates.

File: src/features/events/components/EventOverviewCard/index.tsx [hunk 2]
```diff
@@ -237,14 +638,14 @@ const EventOverviewCard: FC<EventOverviewCardProps> = ({
...
-                  sx={{ marginBottom: 2 }}
+                  sx={{ marginBottom: 2, marginLeft: 1, paddingRight: 2 }}
                   value={infoText}
                 />
               )}
               renderPreview={() => {
                 if (eventData.info_text !== '') {
                   return (
-                    <Box>
+                    <Box mb={2} ml={2}>
```
Comment (richardolsson) [inline src/features/events/components/EventOverviewCard/index.tsx:648]: Why are there only margins on the left and bottom sides? I would say that in general margins should be consistent around a block. There are of course many exceptions, but when design (styling) and semantics (HTML/DOM) align well, it should be rare to have to have different margins on different sides.

I would just do `<Box m={2}>` in this case, unless you know of some reason not to?

File: src/features/events/components/EventOverviewCard/index.tsx [hunk 3]
```diff
@@ -237,14 +638,14 @@ const EventOverviewCard: FC<EventOverviewCardProps> = ({
                   multiline
                   onChange={(ev) => setInfoText(ev.target.value)}
                   rows={4}
-                  sx={{ marginBottom: 2 }}
+                  sx={{ marginBottom: 2, marginLeft: 1, paddingRight: 2 }}
```
Comment (richardolsson) [inline src/features/events/components/EventOverviewCard/index.tsx:641]: Same goes here, I see no reason to not just use a consistent margin (and no padding).

File: src/features/events/components/EventOverviewCard/index.tsx [hunk 4]
```diff
@@ -76,157 +114,520 @@ const EventOverviewCard: FC<EventOverviewCardProps> = ({
...
+                        }
+                      }}
+                      value={link || ''}
+                    />
+                  </Grid>
+                </Grid>
+              </Grid>
+            </Grid>
+          </Grid>
+          <Box>
```
Comment (richardolsson) [inline src/features/events/components/EventOverviewCard/index.tsx:630]: Maybe you could even put the margin here? Or on the container that contains all of the card contents (in which case it would probably be `padding` instead)?

File: src/features/events/components/EventOverviewCard/index.tsx [hunk 5]
```diff
@@ -42,16 +56,40 @@ const EventOverviewCard: FC<EventOverviewCardProps> = ({
...
+
+  const [startDate, setStartDate] = useState<Dayjs | undefined>(
+    eventData?.start_time
+      ? dayjs(removeOffset(eventData.start_time))
+      : undefined
+  );
+  const [endDate, setEndDate] = useState<Dayjs | undefined>(
+    eventData?.end_time ? dayjs(removeOffset(eventData.end_time)) : undefined
+  );
+  const [openButton, setOpenButton] = useState(false);
```
Comment (richardolsson) [inline src/features/events/components/EventOverviewCard/index.tsx:68]: Am I right in my understanding of the code that this is the state that controls whether there should be an end date input visible? If that's the case, I think the name for this state is not communicating very well what it's fore. It took me a while to figure it out. Maybe call it `showEndDate` or `endDateVisible` or something like that?

**Review by richardolsson — CHANGES_REQUESTED** [review]
Great work on a big task! I've left some comments below, and would also like to give some visual feedback that is easier to do over zoom. I had to finish now because I ran out of time, there might be more stuff in the code that I would like to look at, but let's start here?

File: src/features/events/components/EventOverviewCard/index.tsx (hunk 5 above)
Comment (rebecarubio) [reply src/features/events/components/EventOverviewCard/index.tsx:68]: You´re right! I'll change it!

File: src/features/events/components/EventOverviewCard/index.tsx [hunk 6]
```diff
@@ -42,16 +56,40 @@ const EventOverviewCard: FC<EventOverviewCardProps> = ({
...
+      onEditModeExit: () => {
+        setEditable(false);
+        setOpenButton(false);
+      },
       save: () => {
         dataModel.updateEventData({
+          end_time: dayjs(endDate)
+            .hour(endDate ? endDate.hour() : 0)
+            .minute(endDate ? endDate.minute() : 0)
+            .format(),
```
[the remark this answers is not in the document]
Comment (rebecarubio) [reply src/features/events/components/EventOverviewCard/index.tsx:85]: dayjs().format() 
// current date in ISO8601, without fraction seconds e.g. '2020-04-02T08:02:17-05:00'

File: src/features/events/components/EventOverviewCard/index.tsx [hunk 7]
```diff
@@ -42,16 +56,40 @@ const EventOverviewCard: FC<EventOverviewCardProps> = ({
   const [locationId, setLocationId] = useState(
     eventData?.location.id ?? undefined
   );
+
+  const [startDate, setStartDate] = useState<Dayjs | undefined>(
```
[the remark this answers is not in the document]
Comment (rebecarubio) [reply src/features/events/components/EventOverviewCard/index.tsx]: image

I´ve tried to leave it at Dayjs only but as `EventData ` can be `null` I got errors, so my proposal is type the `startDate `as `<Dayjs | null>`

[the remark this answers is not in the document]
Comment (richardolsson) [reply src/features/events/components/EventOverviewCard/index.tsx]: This component will not be shown if `eventData` is null. I understand that typescript thinks that it can be null, because it's coming from a future, which is typed as potentially null. But that's not a realistic typing. Use `ZUIFuture` to make sure that typescript understands that it is always true, or change the component structure such that you can do `if (!eventData) return null` before you start rendering (which will be problematic now because that would make hooks conditional with the current setup).

**Review by richardolsson — APPROVED** [review]
Nice work! I think this is good enough to merge. I see some issues with margins still, especially the vertical centering of the button. But I tried to give an easy recommendation for how to fix it, which is when I noticed that _how_ margins have been set up is more complicated than it should need to be.

I think there is something here worth practicing in the future, which is how to work _with_ the CSS layout model instead of against it. It's something we can look at together later in the week or when you get back from Barcelona!
