### PR TITLE
Issue-1610/ Fix pane when url changes

### LINKED ISSUE #1610: Calendar filter stays after tab switch
## Description
When using the filter popper in a project calendar view and change view the filter popper remains but is unusable.

## Steps to reproduce
1. Go to a calendar view
2. Click "Filter" button
3. Choose "Activities"

### Expected Behaviour
Filter popper close on tab switch

### Actual Behaviour
Filter popper stays on tab switch

## Screenshots (if you have any)
bild

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR fixes a bug and closes the pane when the user navigates to another url instead of leave the pane open.

## Screenshots

https://github.com/zetkin/app.zetkin.org/assets/36491300/0c99560c-6767-44f1-a2e7-c40a04c37b06

https://github.com/zetkin/app.zetkin.org/assets/36491300/8c436386-9680-46b9-bff1-ace855d0be32

## Changes
* Adds a `useEffect ` in `PaneProvider ` component to set `open ` variable to false when `pathname `changes.

## Notes to reviewer
I'm using pathname from useRouter() instead of router.events because it looks like will be deprecated in [Next 13](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#step-5-migrating-routing-hooks) and it also requires more code and I think this solution is cleaner and will work with the next versions. 

## Related issues
Resolves #1610

### CODE REVIEW

File: src/utils/panes/index.tsx [hunk 1]
```diff
@@ -57,10 +59,15 @@ export const PaneProvider: FC<PaneProviderProps> = ({
...
   const styles = useStyles();
   const [key, setKey] = useState(0);
+  const { pathname } = useRouter();
 
   const { paneContainerRef, slideRef, updatePaneHeight } =
     useResizablePane(fixedHeight);
 
+  useEffect(() => {
+    setOpen(false);
+  }, [pathname]);
```
Comment (richardolsson) [inline src/utils/panes/index.tsx:69]: Great solution!

**Review by richardolsson — APPROVED** [review]
Thanks @ziggabyte for verifying that it works. Go team!
