### PR TITLE
Issue 730/tooltip journey created column relative today

### LINKED ISSUE #730: Values in the "created" column in the journey instance table does not have a tooltip, the way other date columns do.
## Description
Not all date columns in the journey instance table show dates consistently. 

## Steps to reproduce
1. Go to http://localhost:3000/organize/7/journeys/6
2. Scroll until you see the "Last updated" column
3. Scroll until you see the "Created" column

### Expected Behaviour
Both should use the same format (a relative time, like the "Last updated" column does)

### Actual Behaviour
The "created" column uses a timestamp format instead.

## Screenshots
image

## Proposed solution
Use `<ZUIRelativeTime>` in the _Created_ column (same as _Last updated_) which has tooltip builtin.

### PR DESCRIPTION
**Pull request by dothelooping**
## Description
Shows relative time in "Creative" column in Journeys.

## Screenshots
[Add screenshots here]

## Changes
[Add a list of features added/changed, bugs fixed etc]

* Adds…
* Changes…

## Notes to reviewer
Try http://localhost:3000/organize/7/journeys/6

## Related issues
Resolves #730

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -38,5 +38,8 @@ yarn-error.log*
 # vs code
 .vscode/
 
+# intellij
+.idea
```
Comment (richardolsson) [inline .gitignore:42]: Great addition for our IntelliJ comrades!

File: src/features/journeys/components/JourneyInstancesDataTable/getStaticColumns.tsx [hunk 2]
```diff
@@ -211,7 +210,11 @@ export const getStaticColumns = (
     {
       field: 'created',
       renderCell: (params) => (
-        <ZUIDateTime convertToLocal datetime={params.value as string} />
+        <ZUIRelativeTime
```
Comment (richardolsson) [inline src/features/journeys/components/JourneyInstancesDataTable/getStaticColumns.tsx:213]: Much better! 💯

**Review by richardolsson — APPROVED** [review]
Great work! Code looks good, interface looks good, and all tests pass. Green light to merge! 🟢 🟢 🟢
