### PR TITLE
issue 1590/remove json type fields

### LINKED ISSUE #1590: Fix display of "Extra data" in lists
## Description
When I chose to add a custom field called "Extra data" to my list it renders the object instead of the value

## Steps to reproduce
1. Go to 'http://app.dev.zetkin.org/organize/1/people/views/112'
2. See how the Custom Field column "Extra data" doesn't render the value.

### Expected Behaviour
Extra data column displays the human readable value

### Actual Behaviour
Extra data column displays the object

## Screenshots (if you have any)

Image

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR fixes a bug where it displays JSON data to cell as "[object object]".

## Screenshots

https://github.com/zetkin/app.zetkin.org/assets/77925373/15cbb610-f33d-4f7b-b052-91f6c23bc526

## Changes

* Adds if condition for filtering field type "json"

## Notes to reviewer
Extra text of Casey warren is "[object object]" because the its value is literally "[object object]" 
image

## Related issues
Resolves #1590

### CODE REVIEW

File: src/features/views/components/ViewColumnDialog/PersonFieldConfig.tsx [hunk 1]
```diff
@@ -46,12 +46,14 @@ const PersonFieldConfig = ({
 
   const fields: Field[] = [];
 
-  customFields.map((field) =>
-    fields.push({
-      slug: field.slug,
-      title: field.title,
-    })
-  );
+  customFields.map((field) => {
```
Comment (richardolsson) [inline src/features/views/components/ViewColumnDialog/PersonFieldConfig.tsx:49]: I think this is a good opportunity to move away from using `map` here, and use `forEach` instead. Because `map` only makes sense to me when the return value is used, and it's not here.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! I have only a very minor request.

File: src/features/views/components/ViewColumnDialog/PersonFieldConfig.tsx (hunk 1 above)
Comment (kaulfield23) [reply src/features/views/components/ViewColumnDialog/PersonFieldConfig.tsx:49]: So sloppy of me to miss this. Will fix it right away

**Review by richardolsson — APPROVED** [review]
LGTM!
