### PR TITLE
Display title of current organization in confirmation dialog 

### LINKED ISSUE #2400: "The whole organization" misleading when deleting type
## Description
Since #2219, it's possible to delete event types via the drop down under the event title. The confirmation dialog that opens warns that types will be deleted "for the whole organization", which is misleading because it could just as easily be interpreted as the entire organization tree.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Go to any event
3. In the event type/category dropdown, type "my new type" and create a new type
4. Open the dropdown again and click the small garbage can

### Expected Behaviour
A dialog should open asking the user to confirm that they want to delete the type. The message should say that the type will be deleted for "all of {org}" where `{org}` is the title of the current organization.

### Actual Behaviour
The dialog opens, but it implies that the type will be deleted for the entire tree, which is misleading.

### Creating a new type (step 3)
image

### Garbage can to delete (step 4)
image

### Current message (actual behavior)
image

### PR DESCRIPTION
**Pull request by helihard**
## Description
This PR displays the name of the current organization in the confirmation dialog on selecting delete event type from an event. 

## Screenshots
confirmation-dialog-1
confirmation-dialog-2

## Changes
* Displays the name of the current organization in the confirmation dialog.
* Displays a default message should the name of the current organization be null or undefined.

## Notes to reviewer
Not at all sure this is a good solution, even if it seems to work as intended on my end. If not, I would be happy for a hint about the right direction.

## Related issues
Resolves #2400

### CODE REVIEW

File: src/features/events/l10n/messageIds.ts [hunk 1]
```diff
@@ -282,8 +282,9 @@ export default makeMessages('feat.events', {
   tooltipContent: m('Untitled events will display type as title'),
   type: {
     createType: m<{ type: string }>('Create "{type}"'),
-    deleteMessage: m<{ eventType: string }>(
-      'Are you sure you want to delete the "{eventType}" event type for the whole organization?'
+    currentDefaultOrgMsg: m('the current organization'),
+    deleteMessage: m<{ eventType: string; orgTitle: string }>(
```
Comment (richardolsson) [inline src/features/events/l10n/messageIds.ts:286]: Changing a message like this (adding properties) is risky, because there might be translations that don't include the property. I think we should give the message a new name.

File: src/features/events/components/EventTypeAutocomplete.tsx [hunk 2]
```diff
@@ -250,6 +253,7 @@ const EventTypeAutocomplete: FC<EventTypeAutocompleteProps> = ({
                         },
                         warningText: messages.type.deleteMessage({
                           eventType: option.title,
+                          orgTitle: orgTitle ? orgTitle : currentDefaultOrgMsg,
```
Comment (richardolsson) [inline src/features/events/components/EventTypeAutocomplete.tsx:256]: Under no normal circumstances should `orgTitle` be `undefined` on this page. If it is, it should be temporary (while loading) and I'm thinking we can fallback to an empty string or something. That way, we don't need to have two separate messages.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! I think your solution is very clever, but I don't think we need to be that clever. Could we try to simplify the solution?

**Review by richardolsson — APPROVED** [review]
The preview build works as expected and the code looks good as well. Nice work! 💯
