### PR TITLE
issue-1442/disable-print

### LINKED ISSUE #1442: "Print schedule" does nothing
## Description
There is a "Print schedule" option in the event bulk actions that does nothing. It should be hidden until #412 is done.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/calendar
2. Hover any event and click it's checkbox
3. In the selection bar that appears in the bottom right, click the ellipsis menu

### Expected Behaviour
The "Print schedule" option should not be there

### Actual Behaviour

One of the options is "Print schedule"

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR disable "print schedule" option in ellipsis menu

## Screenshots

image

## Changes

* Adds `textColor` for preventing type error

## Related issues
Resolves #1442

### CODE REVIEW

File: src/features/events/components/SelectionBarEllipsis.tsx [hunk 1]
```diff
@@ -100,6 +99,7 @@ const SelectionBarEllipsis = () => {
       onSelect: () => {
         model.updateEvents(selectedEventIds, true, false);
       },
+      textColor: '',
```
Comment (richardolsson) [inline src/features/events/components/SelectionBarEllipsis.tsx:102]: IMO a better solution to this would have been to add a type to the array on line 50, so that Typescript would know that not all objects have to look exactly the same (i.e. that the `textColor` property is optional).

**Review by richardolsson — APPROVED** [review]
Simple fix! Will merge (with some feedback below).
