### PR TITLE
Activist portal: Register flow

### LINKED ISSUE #3120: ZUI: Align checkbox to top in relation to its label
### The bug

Long `ZUICheckbox` checkboxes aligns to the relative middle of the label length.

## Steps to reproduce

1. Go to https://app.dev.zetkin.org/storybook/index.html?path=%2Fdocs%2Fcomponents-zuicheckbox--docs
2. Add alot of content to the `label` variable

### Expected Behaviour
The checkbox remains at the top

### Actual Behaviour
The checkbox vertically aligns to the overall center

## Screenshots

Yes-yes:

Image

No-no:
Image

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR adds the necessary components to allow users to register via url `/register`

## Screenshots
image
image

image

image

image

## Changes
* Add RegisterPage.
* Add VerifyPage.
* Add hook `useCreateNewAccount()`.
* * Add hook `useSendVerification()`.
* Add localized strings for registration.
* Add `RegisterSuccessSection` component.
* Add `mui-tel-input` library (dependency).
* Add `MuiTelInput` field and phone-number validation.
* Change `minHeight` and `maxWidth` in `layout`

## Notes to reviewer
Review after https://github.com/zetkin/app.zetkin.org/pull/3077

## Related issues
Resolves #3120 (but that's not the main task of the pr)

### CODE REVIEW

File: src/features/account/components/RegisterFormSection.tsx [hunk 1]
```diff
@@ -0,0 +1,270 @@
...
+  onSuccess: (first_name: string, email: string) => void;
+};
+
+const RegisterFormSection: FC<RegisterFormSectionProps> = ({ onSuccess }) => {
+  const isMobile = useIsMobile();
+  const messages = useMessages(messageIds);
+  const { loading, createNewAccount } = useCreateNewAccount();
+  const [showExtraFields, setShowExtraFields] = useState(false);
+  const [isTermsAccepted, setIsTermsAccepted] = useState(false);
+  const [emailError, setEmailError] = useState<string | null>(null);
```
Comment (ziggabyte) [inline src/features/account/components/RegisterFormSection.tsx]: type stricter, like the other one

File: src/features/account/components/RegisterFormSection.tsx [hunk 2]
```diff
@@ -0,0 +1,270 @@
...
+                  <ZUITextField
+                    fullWidth
+                    label={messages.register.labels.lastName()}
+                    onChange={(value) =>
+                      setFormData((prev) => ({ ...prev, last_name: value }))
+                    }
+                    size="large"
+                  />
+                  <MuiTelInput
+                    defaultCountry="SE"
```
Comment (ziggabyte) [inline src/features/account/components/RegisterFormSection.tsx]: should be from browser or org country?

File: src/features/account/components/RegisterFormSection.tsx [hunk 3]
```diff
@@ -0,0 +1,270 @@
...
+                  />
+                  <ZUITextField
+                    fullWidth
+                    label={messages.register.labels.lastName()}
+                    onChange={(value) =>
+                      setFormData((prev) => ({ ...prev, last_name: value }))
+                    }
+                    size="large"
+                  />
+                  <MuiTelInput
```
Comment (ziggabyte) [inline src/features/account/components/RegisterFormSection.tsx]: localization for this

File: .env.development [hunk 4]
```diff
@@ -1,6 +1,7 @@
 ZETKIN_APP_DOMAIN=http://www.dev.zetkin.org
 ZETKIN_GEN2_ORGANIZE_URL=http://organize.dev.zetkin.org
 ZETKIN_GEN2_CALL_URL=http://call.dev.zetkin.org
+ZETKIN_LOGIN_URL=http://login.dev.zetk.in
```
Comment (richardolsson) [inline .env.development]: This is not necessary. There is already a URL at `/login` which redirects to the correct login URL, so we don't need another environment variable, and this file should not be part of this PR.

File: src/features/account/components/LostPasswordSection.tsx [hunk 5]
```diff
@@ -123,7 +123,11 @@ const LostPasswordSection: FC<LostPasswordSectionProps> = ({
                 right: { md: 'auto', xs: 0 },
               }}
             >
-              <NextLink href={`https://login.zetk.in/`}>
+              <NextLink
+                href={`${
+                  process.env.ZETKIN_LOGIN_URL || 'https://login.zetk.in/'
+                }`}
+              >
```
Comment (richardolsson) [inline src/features/account/components/LostPasswordSection.tsx]: This should just link to `/login`, or maybe `/login?redirect=/my`.

File: src/features/account/components/ResetPasswordSection.tsx [hunk 6]
```diff
@@ -111,7 +111,11 @@ const ResetPasswordSection: FC<ResetPasswordSectionProps> = ({
                 right: { md: 'auto', xs: 0 },
               }}
             >
-              <NextLink href={`https://login.zetk.in/`}>
+              <NextLink
+                href={`${
+                  process.env.ZETKIN_LOGIN_URL || 'https://login.zetk.in/'
+                }`}
+              >
```
Comment (richardolsson) [inline src/features/account/components/ResetPasswordSection.tsx]: This should use `/login`.

File: src/features/account/components/UpdatedPasswordSection.tsx [hunk 7]
```diff
@@ -44,7 +44,11 @@ const UpdatedPasswordSection = () => {
                   width: '100%',
                 }}
               >
-                <NextLink href={`https://login.zetk.in/`}>
+                <NextLink
+                  href={`${
+                    process.env.ZETKIN_LOGIN_URL || 'https://login.zetk.in/'
+                  }`}
+                >
```
Comment (richardolsson) [inline src/features/account/components/UpdatedPasswordSection.tsx]: This should use `/login`.

File: src/utils/types/zetkin.ts [hunk 8]
```diff
@@ -212,6 +213,7 @@ export interface ZetkinSession {
   created: string;
   level: number;
   user: ZetkinUser;
+  factors: string[];
```
Comment (richardolsson) [inline src/utils/types/zetkin.ts]: I would type this more strictly than this. The possible choices are `email_password`, `phone_otp` and `api_key`.

```suggestion
  factors: ('email_password','phone_otp','api_key')[];
```

File: src/app/verify/[token]/page.tsx [hunk 9]
```diff
@@ -0,0 +1,28 @@
...
+  try {
+    await apiClient.put(`/api/users/me/verification_codes`, { code });
+
+    await redirectIfLoginNeeded();
+    redirect('/my');
+  } catch (err) {
+    const path = headersList.get('x-requested-path');
+    redirect(`/login?redirect=${path}`);
+  }
+}
```
Comment (richardolsson) [inline src/app/verify/[token]/page.tsx]: The logic of this is not correct. I made it work by changing it this way:

```diff
diff --git a/src/app/verify/[token]/page.tsx b/src/app/verify/[token]/page.tsx
index f6252496d..7859e122a 100644
--- a/src/app/verify/[token]/page.tsx
+++ b/src/app/verify/[token]/page.tsx
@@ -6,23 +6,23 @@ import BackendApiClient from 'core/api/client/BackendApiClient';
 
 interface PageProps {
   params: {
-    code: string;
+    token: string;
   };
 }
 export default async function Page({ params }: PageProps) {
-  const { code } = params;
+  await redirectIfLoginNeeded();
+
+  const { token } = params;
   const headersList = headers();
   const headersEntries = headersList.entries();
   const headersObject = Object.fromEntries(headersEntries);
   const apiClient = new BackendApiClient(headersObject);
 
   try {
-    await apiClient.put(`/api/users/me/verification_codes`, { code });
-
-    await redirectIfLoginNeeded();
-    redirect('/my');
+    await apiClient.put(`/api/users/me/verification_codes/${token}`);
   } catch (err) {
-    const path = headersList.get('x-requested-path');
-    redirect(`/login?redirect=${path}`);
+    redirect('/verify');
   }
+
+  redirect('/my');
 }

```

File: src/app/layout.tsx [hunk 10]
```diff
@@ -20,10 +21,27 @@ export default async function RootLayout({
...
+  const path = headersList.get('x-requested-path') || '';
+
+  if (user && session && session.factors && !path.startsWith('/verify')) {
+    const hasEmailAuth = session.factors.includes('email_password');
+
+    // Only redirect to email verification if user used email/password
+    // authentication and their email is not verified.
+    if (hasEmailAuth && !user.email_is_verified) {
+      redirect('/verify');
+    }
```
Comment (richardolsson) [inline src/app/layout.tsx]: This is already done in `redirectIfLoginNeeded()`, and I'm not sure we need to do it here as well?

**Review by richardolsson — COMMENTED** [review]
I left a bunch of comments based on the work I've done on integrating this on the backend.
