### PR TITLE
Add geography map settings panels and fix area selection click handle…

### LINKED ISSUE #2434: Areas: UI coherency
## Description
There are some incoherent UI patterns in the Areas screen.

## Steps to reproduce
1. Go to Areas

### Expected Behaviour
- Draw button located at usual CTA location to the far-right.
- Draw button is without drop shadow
- Draw button is text-only
- Filters and Search functionality accessible from right-aligned vertical toolbar overlayed on map, just like in a canvass assignment page
- Square icon button style is used for map overlay toolbar
  - its container's corners rounded with white background and with 1px solid #E0E0E0 border
  - its buttons divided by divider with color #E0E0E0

image

### Actual Behaviour
- The button for the main action of the screen ("Draw") sits alone in dedicated, left-aligned toolbar.
- Draw button has drop shadow
- Draw button has icon
- Legacy filter UI in dedicated, left-aligned toolbar.
- Legacy search UI  in dedicated, left-aligned toolbar.
- Primary button style is used for map navigation
- Rectangular-shaped buttons are used for map navigation even though containing icons only

image

### PR DESCRIPTION
**Pull request by laurablum**
## Description
This PR adds a settings side panel to the Geography map for selecting areas and controlling area layer styling, and fixes an issue where map click handlers could accumulate over time.

## Screenshots
image
image
image
image
image

## Changes
- **Adds** a right-side settings panel with:
  - Area selection (with search/filter)
  - Area layer style controls (filled/outlined/hidden)
- **Persists** chosen area layer style in local storage per org
- **Changes** area rendering to use the active MUI theme (no `oldTheme` dependency)
- **Fixes** `useAreaSelection()` to properly register/unregister the map click handler (prevents repeated listeners) and improves robustness when reading feature IDs

## Notes to reviewer
- Go to the Geography map for an org with areas.
- Click the **layers** button and switch area style (filled/outlined/hidden) and verify the map updates.
- Click the **select** button, search for an area, select it, and verify the selection/overlay.
- Click an area directly on the map and verify it opens the select panel and selects the clicked area.
- Refresh the page and verify the chosen area style persists for the org.
- **IMPORTANT**: The "Draw" button-changes are igbnored in this PR and are tackled in PR #3330

## Related issues
Resolves #2434

### CODE REVIEW

**Comment by sefsh** [comment]
Nice work laurablum! The changes work pretty good, though I've realized I snuck in a little disinformation in #2434:
>Filters and Search functionality accessible from right-aligned vertical toolbar overlayed on map, just like in a canvass assignment page

This means that you've now have gone ahead and implemented the area color data viz. However, in the Geopgraphy page, none of the area color filter states are applicable. Sorry for sending you down the wrong path wrt this. 

Without the area color visualization feature there is no use for the "Data visualization" map pane at all, so it should be removed for now along with its button.

The "Areas" map pane works great, it's quick and effortless. A bug I found though is that if you:
- select a single area in the "Select"/Areas pane
- click the select pane button
…the pane doesn't close, but toggles between the formerly selected area and the area overview.

The pane should always close directly when its corresponding button is clicked.

That's it, I think. Again, sorry for wasting your time with the dataviz detour. :(

**Review by ziggabyte — CHANGES_REQUESTED** [review]
Just marking this with "request changes" in reference to the comment @sefsh made above, so that it has the correct status :)

File: src/features/geography/components/GLGeographyMap/index.tsx [hunk 1]
```diff
@@ -44,104 +70,244 @@ const GLGeographyMap: FC<Props> = ({ areas, orgId }) => {
...
+          onZoomOut={() => map?.zoomOut()}
+        />
+        <Box
+          sx={{
+            position: 'absolute',
+            right: 16,
+            top: 16,
+            transform: rightSideOverlayOpen
+              ? `translate(-${
+                  SETTINGS_PANEL_WIDTH_PX + SETTINGS_PANEL_GAP_PX
```
Comment (ziggabyte) [inline src/features/geography/components/GLGeographyMap/index.tsx]: Thank you for this writing these out to make it more clear what this calculation does! :D

File: src/features/geography/hooks/useAreaSelection.ts [hunk 2]
```diff
@@ -7,37 +7,56 @@ import { Zetkin2Area } from 'features/areas/types';
...
+        ev.features.length > 1
+          ? [...ev.features].sort(
+              (feature0, feature2) => area(feature0) - area(feature2)
+            )
+          : ev.features;
+
+      const feature = featuresBySmallestFirst[0];
+      const id = Number(feature?.properties?.id);
+
+      if (!Number.isFinite(id)) {
```
Comment (ziggabyte) [inline src/features/geography/hooks/useAreaSelection.ts]: Wow, this is a new thing, this made me learn about `isFinite`! cool!

File: src/features/geography/hooks/useAreaSelection.ts [hunk 3]
```diff
@@ -7,37 +7,56 @@ import { Zetkin2Area } from 'features/areas/types';
...
 };
 
-export default function useAreaSelection({ areas, map }: Props): Return {
+export default function useAreaSelection({
+  areas,
+  map,
+  onSelectFromMap,
+}: Props): Return {
   const [selectedId, setSelectedId] = useState(0);
-  const selectedArea = areas.find((area) => area.id == selectedId) || null;
```
[the remark this answers is not in the document]
Comment (laurablum) [reply src/features/geography/hooks/useAreaSelection.ts]: I reverted these for now, since I don't want to break conventions.
