### PR TITLE
Select both Zetkin- and external ID in importer.

### LINKED ISSUE #1935: Import: Not possible to import External ID using Zetkin IDs as the key
## Description
A somewhat common pattern will be for users to export a list from Zetkin, populate it with external IDs (e.g. member IDs) and then import that list back. That's currently not possible, because it's not possible to map both Zetkin ID and External ID to (different) columns.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "Create..."
3. Click on "Import people"
4. Import a file that contains at least two columns
5. Map the first column to Zetkin ID
6. Map the second column to External ID

### Expected Behaviour
It should be possible.

### Actual Behaviour
The "ID" option is disabled in the drop-down, because it has already been configured as Zetkin ID.

## Screenshots (if you have any)
N/A

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR redesigns the way the user selects ids in the importer - instead of one selection with a config, it's now two separate choices with information.

(this is a design work done on top of @remipou 's work!)

## Screenshots
bild

bild

## Changes
* Removes the id config
* Adds info text about the two id types
* Makes the button in the mapping row say "info" instead of "map values" or "configure"

## Notes to reviewer
nothing in particular

## Related issues
Resolves #1935

### CODE REVIEW

File: src/features/import/l10n/messageIds.ts [hunk 1]
```diff
@@ -64,27 +64,23 @@ export default makeMessages('feat.import', {
...
-        header: m('Configure IDs'),
-        showOrganizationSelectButton: m('Map to...'),
         wrongIDFormatWarning: m(
           'The values in this column does not look like Zetkin IDs. A Zetkin ID only contains numbers. If some cells are empty or contain f.x. letters, it can not be used as Zetkin IDs.'
         ),
         zetkinID: m('Zetkin ID'),
-        zetkinIDExplanation: m(
-          'The values in this column are based on an export from Zetkin.'
+        zetkinIDInfo: m(
+          'A Zetkin ID is the ID a person has in Zetkin. You would have it in a file if you exported data from Zetkin.'
```
Comment (richardolsson) [inline src/features/import/l10n/messageIds.ts:76]:
```suggestion
          'A Zetkin ID is the ID of a person already in Zetkin. You would have it in a file if you exported data from Zetkin.'
```

File: src/features/import/l10n/messageIds.ts [hunk 2]
```diff
@@ -64,27 +64,23 @@ export default makeMessages('feat.import', {
...
       },
       ids: {
-        configExplanation: m(
-          'Importing with IDs allows Zetkin (now or in the future) to update existing people in the database instead of creating duplicates.'
-        ),
         externalID: m('External ID'),
-        externalIDExplanation: m(
-          'The values in this column are IDs from our main member system (not Zetkin).'
+        externalIDInfo: m(
+          'An external ID is an ID that comes from another system than Zetkin - your member system or something of the like. It can be used to find and identify people in Zetkin.'
```
Comment (richardolsson) [inline src/features/import/l10n/messageIds.ts:69]:
```suggestion
          'An external ID is an ID that comes from another system than Zetkin, such as a separate member database. It can be used to find and identify people in Zetkin.'
```

File: src/features/import/utils/remapFields.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+      return [
+        fn(key),
+        Array.isArray(value)
+          ? value.map((val) => getValue(val))
+          : getValue(value),
+      ];
+    })
+  );
+
+const remapFields = (importRes: ImportPreview | PersonImport) =>
```
Comment (richardolsson) [inline src/features/import/utils/remapFields.ts:21]: It took some effort understanding what this function does, but in the end I understand that it translates the key `member_id` (which is incorrectly leaked from the backend) to `ext_id` which is what it should be called.

**Review by richardolsson — DISMISSED** [review]
Nice work @remipou and @ziggabyte!

I tried the preview build and have reviewed the code. I've found everything to work as expected and the code looks good to me.

I found some potential for minor improvements (IMO) in the texts, but honestly it's entirely subjective and I think you should decide whether you want to merge as is or not.

**Review by richardolsson — APPROVED** [review]
This looks all good to me now! 💯 

Nice work both of you, and I'm sorry @remipou that no one got around to properly review your PR until now. I wasn't entirely comfortable with the UX that we came up with at the Code Camp, so I wanted to get some more people involved.
