### PR TITLE
Finish redux refactor for Views

### LINKED ISSUE #865: Deleting view column that is used for sorting
## Description
If I sort my view by a column, and then in the sorted state decide to delete that column

## Steps to reproduce
1. Go to any view
2. Sort by any column
3. Click ellipsis menu of column you sorted by, and delete the column
4. Get error

### Expected Behaviour
Deletes the column and resets sort to default

### Actual Behaviour
Goes into error 
bild

### LINKED ISSUE #957: Finish Views refactor react query -> redux
finish 🇫🇮 

- [x] Adding a column
- [x] Deleting a column
- [x] Renaming a column
- [x] Adding a person
- [x] Removing a person
- [x] Renaming a view
- [x] Modifying Smart Search

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR completes the Model/Repo/Store refactor using redux for views, removing all remnants of `react-query` from the views feature. There are some exceptions in the column choice dialog, where non-views data (tags, surveys etc) are retrieved using the old pattern.

This PR also seems to fix the "delete column" bug (#865), which makes sense since it rewrites a lot of the view content loading and manipulation code.

## Screenshots
None, this is a behind-the-scenes refactor.

## Changes
* Adds the necessary model, repo and store logic
* Removes all remnants of views related `react-query` code
* Refactors in-view searching to use the `IColumnType` classes for per-type search logic
* Changes the `FetchApiClient` so that it throws errors on failed requests
* Updates some tests to handle

## Notes to reviewer
Also test for #865 

## Related issues
Resolves #957 
Resolves #865

### CODE REVIEW

File: src/features/views/components/EmptyView.tsx [hunk 1]
```diff
@@ -9,59 +9,21 @@ import {
...
-        const prevRows: ZetkinViewRow[] =
-          queryClient.getQueryData<ZetkinViewRow[]>(rowsKey) || [];
-        const allRows = prevRows.concat([newRow as ZetkinViewRow]);
-        queryClient.setQueryData(rowsKey, allRows);
-
-        // Invalidate to retrieve entire row collection (in case more were added elsewhere)
-        queryClient.invalidateQueries(rowsKey);
-      },
-    }
-  );
```
Comment (ziggabyte) [inline src/features/views/components/EmptyView.tsx:64]: very satisfying deleting this much logic from a component!!!

File: src/features/views/components/EmptyView.tsx [hunk 2]
```diff
@@ -78,8 +40,9 @@ const EmptyView: FunctionComponent<EmptyViewProps> = ({ orgId, view }) => {
               <Box marginTop={2}>
                 <PersonSelect
                   name="person"
-                  onChange={(person) => {
-                    addFirstRowMutation.mutate(person);
+                  onChange={async (person) => {
+                    await model.deleteContentQuery();
+                    await model.addPerson(person);
                   }}
```
Comment (ziggabyte) [inline src/features/views/components/EmptyView.tsx:46]: also the difference in how clear the wording is, how much easier it is to read the new style!

**Review by ziggabyte — APPROVED** [review]
This was quite the refactor! Since there is nothing visual to give feedback on and I don't find any mistakes that are obvious to me, I say go ahead and merge this beauty!
