### PR TITLE
Show all person number formats for all orgs

### LINKED ISSUE #2113: Import UI crashes when configuring date-field in non-Scandinavian country
## Description
The recent addition of date format parsing in the importer UI assumes that all countries have equivalents of the Swedish/Norwegian/Danish concept of "personnummer" that consist of dates. When used in an organization with a different country code than SE/NO/DK, it crashes.

## Steps to reproduce
1. On the dev server, modify org 1 (using a PATCH request to https://app.dev.zetkin.org/api/orgs/1) to have country code `UK`
2. Go to https://app.dev.zetkin.org/organize/1/people
3. Click "Create"
4. Click "import people"
5. Drop any CSV
6. For any column, pick "Extra date" as the field to import into

### Expected Behaviour
You should be allowed to configure the parsing.

### Actual Behaviour
Crash

## Screenshots (if you have any)
image

## Proposed solution
The root of the issue seems to be this logic:

https://github.com/zetkin/app.zetkin.org/blob/13a632028a6ec5acb7bbd52137ed98aa0bb40e1c/src/features/import/hooks/useDateConfig.ts#L53-L63

Note how the type cast on line 59 claims that any string will be `'se' | 'dk' | 'no'`. Typecasts are dangerous. Removing the typecast will reveal the error, and force an if statement to make sure that the string is actually what this logic assumes it is (which it isn't when the org country is Germany or UK, for example).

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR solves a critical bug by adding a check before a dangerous typecast. 

## Screenshots
Import of dates no longer craches
bild

## Changes
* Adds a check before a typecast.

## Notes to reviewer
see #2113 for instructions on reproducing bug

## Related issues
Resolves #2113

### CODE REVIEW

File: src/features/import/hooks/useDateConfig.ts [hunk 1]
```diff
@@ -54,7 +54,12 @@ export default function useDateConfig(column: DateColumn, columnIndex: number) {
 
   const personNumberFormats: PersonNumberFormat[] = [];
 
-  if (organization) {
+  if (
+    organization &&
+    (organization.country === 'se' ||
```
Comment (richardolsson) [inline src/features/import/hooks/useDateConfig.ts:59]: This won't work, because `country` should generally be uppercase (although there are some outliers which are lowercase). So except for those outliers, this expression will always be false, even for Swedish (`SE`) organizations.

File: src/features/import/hooks/useDateConfig.ts [hunk 2]
```diff
@@ -54,7 +54,12 @@ export default function useDateConfig(column: DateColumn, columnIndex: number) {
...
+      organization.country === 'dk' ||
+      organization.country === 'no')
+  ) {
```
Comment (richardolsson) [inline src/features/import/hooks/useDateConfig.ts:62]: There's nothing wrong (in general, ignoring the specific lowercase/uppercase bug for now) with an expression like this, but there are two things that I would do differently.

## The use of `===`
First of all, I never use `===`. The purpose of that operator is to make sure in javascript that two values are not just "semantically" equal but also technically equal. For example, `1 == '1'` evaluates to true, but `1 === '1'` evaluates to false. You probably know this and feel that the stricter comparison is better because it's stricter.

But the thing is, the reason the `===` operator was added ([in hindsight](https://stackoverflow.com/a/53111225/229824)) to javascript was because of javascripts very weak typing. In most other programming languages `1 == '1'` would already evaluate to false, so `===` would not be necessary. And because we use typescript where types are stricter, we should never end up in a situation where we accidentally compare two values of different types. If you do try to do `1 == '1'` in typescript, you will actually [get an error](https://www.typescriptlang.org/play/?#code/IwAgvGIOTFQ). 

So I prefer to always use `==` because to me it signals to the reader that we _know_ the two operands are the same type, whereas using `===` signals to the reader an insecurity about the types on the part of the coder, which we should never have to feel.

## Many ORs
This is another matter of personal taste for me, but I like to avoid having lots of `||` in an `if` statement. Sometimes they can be replaced by some other expression (like here) and in other cases the ORs are necessary but then they can at least (always) be broken out and named.

### Using `Array.prototype. includes`
The same logic could be expressed as:

```suggestion
  if (
    organization && 
    ['se', 'dk', 'no'].includes(organization.country)
```

In fact, the whole expression could be abbreviated even more by using the optional chaining operator (`?.`) instead of explicitly checking whether `organization` is truthy:

```
  if (['se', 'dk', 'no'].includes(organization?.country)
```

This is just a shorter way of expressing the same thing, and although it does remove the need for having so many line breaks, it isn't necessarily easier to read. In some situations I would argue that it has an edge, because it avoids having _nested_ booleans like you have here (`A && (B || C || D)` becomes just `A && E`) but the expression itself could still be argued is more difficult to interpret, which is why it sometimes makes even more sense to name the expressions.

### Naming expressions (variables)
Most would very intuitively identify when code could be broken out into a function to make it more readable. One of the benefits of doing so is that the function will get a name, and the call site will be easier to read because the logic in the function is expressed as the function's name.

But the same principle can be applied to simpler expressions (like this one) using just variables. If we give the second operand of the `&&` operator a name, the if statement will be easier to read:

```suggestion
  const isNordicCountry = (organization.country === 'se' ||
      organization.country === 'dk' ||
      organization.country === 'no');
  if (organization && isNordicCountry) {
```

I realize this exact example doesn't really make much sense because the reason the `organization` expression is there is to make sense that `organization.country` doesn't throw an error. Again, there's nothing objectively wrong with what you've already done and I'm not suggesting you change anything. I'm just making a general comment on code structure that I hope can be of value.

**Review by richardolsson — CHANGES_REQUESTED** [review]
This PR fixes the crash, but it also breaks the original behavior, because the if statement will never be true. To me personally, I don't think that's a huge problem UX wise, because it means that all types of personal identification numbers will be available regardless of the organization's country. I confirmed this by changing the country of org 1 back to `SE` on the development server.

image

So the question is: What UX do we want? If we want to have the old UX of only seeing the country your organization belongs to the logic needs to be fixed. If we want this new behavior where all supported countries are always visible in the list the condition sholuld be removed entirely.

File: src/features/import/hooks/useDateConfig.ts (hunk 2 above)
Comment (ziggabyte) [reply src/features/import/hooks/useDateConfig.ts:62]: I honestly think that now that we have had this bug behaviour, that the UX this was trying to create (being "kind" to the organiser by only showing the most likely option) is not, I think, a great idea, and does not solve a real world observed problem. So honestly I think the most reasonable thing to do is to just let everyone always see all the three options of person numbers. It's not hard to pick one of three, and if for some odd reason a Danish org would like to import people with Swedish personnummer, they can do so.

Comment (ziggabyte) [reply src/features/import/hooks/useDateConfig.ts:62]: Yes, the reason I lean to use `===` is that it is somewhere ingrained in me from being in Javascript that I don't trust `==`. It is more out of habit that I keep using it even in Typescript. Makes sense to be observant of this and trust the framework of Typescript to do what it is built to do 😸

**Review by richardolsson — APPROVED** [review]
Simple, and better (because it gets rid of the bug). Nice work!
