### PR TITLE
Undocumented/bug events next week

### LINKED ISSUE #1294: Correct logic to sort events into archives
## Description
I'm experiencing unexpected behaviours in the activity archive, where recently added, open activities get added to the archive and not the current activities. My suspicion is that this is because the endDate property is set to a date without time, here on line 179, which is interpreted as 00:00 when it is compared to now in the next image, line 228.
This means that an activity created today, set to take place later today, will show up as "in the past" because the time of the event is set to 00:00 today = in the past.

## Steps to reproduce
1. Go to gen2, create an event that takes place later today in org and project of your choice
2. Go to gen3, to this org and project
3. go to archive tab
4. see your recently created event in the archive

### Expected Behaviour
The event has not happened yet, and is open, so it should be in the overview and activities tabs.

### Actual Behaviour
it gets sorted into the archive

## Screenshots (if you have any)
bild
bild
bild

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR addresses and fixes what events are shown in the "also this week" section of the project overview, and how activities are selected to be part of the archive.

## Changes
* Adds specific logic to select what events happen over the next week.
* Use a date without time to compare what activities should go in the archive tab.

This undocumented issue will close #1294

### CODE REVIEW

File: src/features/campaigns/models/CampaignActivitiesModel.ts [hunk 1]
```diff
@@ -139,11 +139,27 @@ export default class CampaignActivitiesModel extends ModelBase {
...
+            dateIsAfter(startDate, startOfToday) &&
+            dateIsBefore(startDate, weekFromNow);
+          const isOnGoing =
+            dateIsBefore(startDate, startOfToday) &&
+            dateIsAfter(endDate, weekFromNow);
+          const endsDuringWeek =
+            dateIsBefore(startDate, startOfToday) &&
+            dateIsBefore(endDate, weekFromNow);
+
+          return startsDuringWeek || isOnGoing || endsDuringWeek;
```
Comment (richardolsson) [inline src/features/campaigns/models/CampaignActivitiesModel.ts:155]: Very readable!

**Review by richardolsson — APPROVED** [review]
LGTM! 🎯
