### PR TITLE
Issue 1721/inherited survey

### LINKED ISSUE #1721: Inherited survey links to parent organization
## Description
When a sub-organization admin clicks a link to an inherited survey (that is owned by a parent organization) that is presented to them in their /projects section, that link takes them to the survey's page in the parent (owner) organization, which the may not be allowed to access.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects (parent org)
2. Click on any survey (go via "Activities" if none shows up in the overview)
3. Go to the "submissions" tab
4. Make sure "share with sub-organizations" is activated
5. Go to http://localhost:3000/organize/2/projects (a sub-organization)
6. Click on the same survey again

### Expected Behaviour
Should navigate to some URL under http://localhost:3000/organize/2/projects (note org 2).

### Actual Behaviour
Navigates to a survey URL under http://localhost:3000/organize/1/projects (note org 1).

## Screenshots
None

## Proposed solutions
Note that this is not a security issue. The Zetkin API restricts access to resources and organizations correctly. The problem here is just what we _try_ to show to the user, and the web app should not attempt to retrieve something that we _know_ the user will not be able to access.

I can think of a few different solutions, each with their own problems:

* Change access code in `scaffold()` so that the user is allowed to access (some) pages under the parent organization even without having full access to that organization. This will be technically very complicated compared to what we're doing right now, because right now we just check if `orgId` from the URL is one of the user's admin orgs.
* Change so that it links to the survey under the _current_ organization, i.e. http://localhost:3000/organize/2/projects/PROJ_ID/surveys/SURVEY_ID. This page works, except the breadcrumbs doesn't work on this page because the project `PROJ_ID` will also be owned by the parent org and will not accessible under the current org (or at all if you're not a parent-org admin).
* Change so that it links to the survey under the _current_ organization and a pseudo-project (e.g. `inherited`) similar to what is done for "standalone", e.g. http://localhost:3000/organize/2/projects/inherited/surveys/SURVEY_ID. I think this would be the easiest.

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR fixes a bug where shared submissions in child organizations navigate to the parent organization's submission, which is an original survey.

## Screenshots
- Survey in same organization which has project ID
image

- Survey in same organization which doesn't have project ID
image

- Shared survey in sub organization
image

## Changes

* Create `getSurveyCampId` function that returns `campId`(number) / 'standalone' / 'inherited'
* Changes `href` in `Link`
* Add `orgId` parameter in `getSurveyUrl`

## Related issues
Resolves #1721

### CODE REVIEW

File: src/features/surveys/components/SubmissionWarningAlert.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ import ZUIFuture from 'zui/ZUIFuture';
 import { Alert, AlertTitle, Box, Link } from '@mui/material';
 
 type SubmissionWarningAlertProps = {
-  campId: number | 'standalone';
+  campId: number | 'standalone' | 'inherited';
```
Comment (richardolsson) [inline src/features/surveys/components/SubmissionWarningAlert.tsx:9]: I wonder if "shared" is better than "inherited". What do you think @ziggabyte?

This is to indicate that a parent organization owns this survey, and has shared it with all of it's sub-orgs (including your current organization). It's just visible in the URL, so it's not critical, but we might as well pick whatever we're most comfortable with right now and not have to feel like we should change it later. :blush¨

File: src/features/surveys/utils/getSurveyUrl.ts [hunk 2]
```diff
@@ -1,10 +1,24 @@
...
+  }
+}
+
+export function getSurveyCampId(survey: ZetkinSurvey | null, orgId: number) {
+  if (survey) {
+    return survey.organization.id !== orgId
+      ? 'inherited'
+      : survey.campaign
+      ? survey.campaign.id
+      : 'standalone';
```
Comment (richardolsson) [inline src/features/surveys/utils/getSurveyUrl.ts:21]: I struggle to read nested ternaries like this. I would recommend the following solutions instead, for readability:

```tsx
if (survey.organization.id !== orgId) {
  return 'inherited';
}

return survey.campaign?.id ?? 'standalone';
```

File: src/pages/api/breadcrumbs.ts [hunk 3]
```diff
@@ -95,7 +95,7 @@ async function fetchElements(
       },
     ];
   } else if (fieldName === 'campId') {
-    if (fieldValue !== 'standalone') {
+    if (fieldValue !== 'standalone' && fieldValue !== 'inherited') {
```
Comment (richardolsson) [inline src/pages/api/breadcrumbs.ts:98]: I don't feel strongly about this, but would it maybe be better with `if (typeof fieldValue == 'number') {`?

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! There are some things here that I want to raise, but the only one I really want to change is the nested ternary. The others I'm not sure whether they should be changed or not, but it would be interesting to hear your thoughts.

File: src/features/surveys/components/SubmissionWarningAlert.tsx (hunk 1 above)
Comment (kaulfield23) [reply src/features/surveys/components/SubmissionWarningAlert.tsx:9]: I think "shared" sounds better!

**Review by richardolsson — APPROVED** [review]
Nice work! This looks great now. 🖖
