### PR TITLE
Fix modal colorful backdrop flickering

### LINKED ISSUE #3462: ZUI: The ZUIModal colourful background blinks
### The feature

ZUI components are made to be the implementation of our design system. They are currently used on the "public facing" pages, like /my and the organization and event pages like /o/[orgId] and /o/[orgId]/events/[eventId]

ZUIModal is a component that is used to show something on top of the screen. Around the modal is a transparent layer of colourful gradients that slowly move

### The bug
The gradients blink (re-render? re-mount? re-something) everytime you interact with content in the modal

## Steps to reproduce

1. Go to https://app.dev.zetkin.org/my and log in as testuser@example.com with password "password"
2. Filter to find calls 
3. click the "call" button on one of the cards to take you to the gen 3 call interface 
(3 1/2. If you're running the project locally and are redirected to the gen2 call interface, make sure you have a file in the root of the project called `.env.local` that contains the line `FEAT_CALL: *`)
4. Click on "call log" at the bottom left corner 
5. When the modal opens, type to search for something in the text field

### Expected Behaviour
The beautiful colours of the background keep floating relaxingly and smoothly

### Actual Behaviour
Seizure alert rave strobe

## Screenshots

https://github.com/user-attachments/assets/d9841e0e-3613-46b3-9ab9-3b8a4af0cb0f

### PR DESCRIPTION
**Pull request by Jrende**
## Description
This PR fixes an issue where the backdrop would flicker every time something changed which caused a redraw. An example is the call log search dialog where typing a character would make the backdrop redraw and flicker.
The problem was partly that react expects the rendering to be deterministic, so redrawing everything with the same values will not cause any problems. Using Math.random is problematic with that in mind.

## Screenshots
https://github.com/user-attachments/assets/a60e1822-c7ae-47fd-8d14-ad72cee3be5d

## Changes
* Replaced Math.random() in backdrop with seeded random, so that it gets the same values when redrawing
* Moved backdrop in dialog out from backdrop property, since the fade-in effect was part of the issue causing the flicker
* Add util file with seeded random function and hash function. A seed can be sent to the backdrop, but it's not critical. The user probably won't notice if the colorful backdrop is the same each time the dialogue is opened.

## Related issues
Resolves #3462

### CODE REVIEW

File: src/zui/components/ZUIModal/ModalBackground.tsx [hunk 1]
```diff
@@ -63,19 +67,20 @@ type LayerData = {
...
       const pattern = PATTERNS[patternIndex];
       const imageHeight = pattern.length;
       const imageWidth = pattern[0].length;
-      const randomColors = COLORS.concat().sort(() => Math.random() - 0.5);
+      const randomColors = COLORS.concat().sort(() => random() - 0.5);
 
-      const duration = 23 + Math.random() * 19;
-      const delay = Math.random() * 7;
+      const duration = 23 + random() * 19;
+      const delay = (new Date().getTime() / 1000) % duration;
```
Comment (ziggabyte) [inline src/zui/components/ZUIModal/ModalBackground.tsx]: I cannot remember why the numbers 19 and 23 were chosen when this was originally built, i think we should have named them something in the first place 😅 

Once again facing the hard truth that everything needs a clear name 🧑‍⚖️
