### PR TITLE
issue-1890/hours-in-month-view

### LINKED ISSUE #1890: Calendar: Monthly calendar always displays time in 24-base
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Steps to reproduce
Prerequisite: Have your browser locale set to english
1. Go to the calendar, month view
2. Look at the time marks in the left side

### Expected Behaviour
Shows time in a way that matches the locale of the browser

### Actual Behaviour
Always shows 24-hour time.

## Screenshots (if you have any)
(please ignore that the times are off in this example, that is tracked in another bug report)
bild

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR fixes a bug where the calendar only displays time in a 24-hour format on the hour lines.

## Screenshots
- 12hrs
image

- 24hrs
image

## Changes

* Adds `.toString()` to time so that `FormattedTime` can show 12/24 hour automatically
* Creates `is12HourClock` to change `minute` prop in `FormattedTime`

## Notes to reviewer
I made `is12HourClock` to remove the minutes (":00") in `FormattedTime` on a 12-hour clock. This was necessary because of styles of text in calendar. When the hour is displayed as a two-digit number, the width for text becomes too narrow.
image

I tried to increase the width of `Box` where texts are in. It would look good on 12 clock time like this
image
But there was too much space between the time and day lane on the 24-hour clock.
image

So I decided to remove minute to make it look nicer.

## Related issues
Resolves #1890

### CODE REVIEW

**Comment by kaulfield23** [comment]
Wait, Let me try something on it!

File: src/features/calendar/components/CalendarWeekView/index.tsx [hunk 1]
```diff
@@ -122,9 +126,8 @@ const CalendarWeekView = ({ focusDate, onClickDay }: CalendarWeekViewProps) => {
                 <Typography color={theme.palette.grey[500]} variant="caption">
                   <FormattedTime
                     hour="numeric"
-                    hour12={false}
-                    minute="numeric"
-                    value={time.toDate()}
+                    minute={is12HourClock ? undefined : 'numeric'}
```
Comment (ziggabyte) [inline src/features/calendar/components/CalendarWeekView/index.tsx:129]: I think this should always be `numeric`!

File: src/features/calendar/components/CalendarWeekView/index.tsx [hunk 2]
```diff
@@ -111,7 +111,11 @@ const CalendarWeekView = ({ focusDate, onClickDay }: CalendarWeekViewProps) => {
         {/* Hours column */}
         <Box>
           {range(24).map((hour: number) => {
-            const time = dayjs().set('hour', hour).set('minute', 0);
+            const time = dayjs().set('hour', hour).set('minute', 0).toString();
+            const is12HourClock = Intl.DateTimeFormat(navigator.language, {
```
Comment (ziggabyte) [inline src/features/calendar/components/CalendarWeekView/index.tsx:115]: ...and that this logic can be removed :)

**Review by ziggabyte — CHANGES_REQUESTED** [review]
It works as intendet, I now see the hours formatted in a way that is consistent with the times in the events! 

However, I don't like the removal of the `.00` to make more room, it makes it still incosistent with the times in the events. 

I think you should remove the `is12HourClock` logic, and instead increase the width of the box the hours are displayed in. This you can do by increasing the constant on line 37, I tried with 60px and that works for both Chrome and Firefox!:
`const HOUR_COLUMN_WIDTH = '60px';`

File: src/features/calendar/components/CalendarWeekView/index.tsx (hunk 2 above)
Comment (kaulfield23) [reply src/features/calendar/components/CalendarWeekView/index.tsx]: I was trying to change width to other boxes except for the very parent box! Very easy and nice solution! Thank you! ❤️

**Review by ziggabyte — APPROVED** [review]
Woop woop! All onboard the merge train! 🚋
