### PR TITLE
Issue 564/sub orgs forbidden for nonofficials

### LINKED ISSUE #564: Navigating to organization sub-pages should be forbidden for non-organization officials
## Description
Currently it's possible to open a page under the `/organize/X/…` path for anyone who's been authenticated to level 2, even if they're not an official in organization X.

## Steps to reproduce
1. Go to  /organize/1/campaigns
2. Sign in as testadmin@example.com
3. Go to /organize/5/campaigns (an unrelated organization)

### Expected Behaviour
User should get 404, or maybe be redirected somewhere else?

### Actual Behaviour
User is presented with an empty page without any campaigns on it, or perhaps a 500 error, because they do not have access to the campaigns belonging to organization 5.

## Requirements
EDIT: Algorithm described below was worked out during the conversation in this issue and on Slack.

### Server-side
- [x] On login, add available organisations to the session (obtained from `/orgs/{org_id}/people/{person_id}/connections`)
- [x] If the user tries to access an organization that is listed in their session, render the page with no further checks (it will be reconfirmed on the front-end)
- [x] Otherwise (user tries to access an organisation that _is not_ in their session), request available orgs again and wait for the result
  - [x] If the list of accessible organizations have changed to now include the requested organization, update the session and and then display the page
  - [x] Otherwise (the list of accessible organizations still does not include the requested organization), redirect to PAGE
- [x] Add route for PAGE, a custom page that informs the user that they aren't authorized to look at what they tried to look at

### Client-side
- [ ] On page load, async request (so as not to delay page load) available orgs for that user to check if they have changed
- [ ] If the requested organization is not in the list, redirect to PAGE

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR makes it so that when logged in, you can't access pages of organizations you are not a member of and have a role in. If you are trying to access such a page, you get the 404-page.

## Related issues
Resolves #564

### CODE REVIEW

**Review by richardolsson — CHANGES_REQUESTED** [review]
Great work! Some comments below, and also I think we need a test that verifies that non-official users get 404. All other tests already verify that this is working, but will need modified mock data in the `login()` fixture in `playwright/fixtures/next.ts`.

File: playwright/mockData/Memberships.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+    organization: KPD,
+    profile: {
+      id: RosaLuxemburg.id,
+      name: RosaLuxemburg.first_name + ' ' + RosaLuxemburg.last_name,
+    },
+    role: 'admin',
+  },
+];
+
+export default Memberships;
```
Comment (djbusstop) [inline playwright/mockData/Memberships.ts:16]: This would probably be better inside the KPD section. Because this is "memberships" for KPD members

File: playwright/tests/organize/memberships.spec.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+          id: RosaLuxemburg.id,
+          name: RosaLuxemburg.first_name + ' ' + RosaLuxemburg.last_name,
+        },
+        role: null,
+      },
+    ];
+
+    login(RosaLuxemburg, memberships);
+    const response = await page.goto(appUri + '/organize/1/campaigns');
+    expect(response?.status()).toEqual(404);
```
Comment (djbusstop) [inline playwright/tests/organize/memberships.spec.ts:52]: Same thing, check URL for redirection

File: src/pages/index.tsx [hunk 3]
```diff
@@ -34,8 +36,25 @@ export const getServerSideProps: GetServerSideProps = scaffold(
...
           reqWithSession.session.tokenData = context.z.getTokenData();
+          if (context.user) {
+            try {
+              reqWithSession.session.organizations = await getOrganizations(
+                context
+              );
+            } catch (error) {
+              reqWithSession.session.organizations = null;
+            }
+          }
```
Comment (djbusstop) [inline src/pages/index.tsx:57]: I'm not sure why this code is needed on the index page, doesn't scaffold handle this stuff?

File: src/utils/next.ts [hunk 4]
```diff
@@ -75,6 +78,14 @@ const stripParams = (relativePath: string, params?: ParsedUrlQuery) => {
   return url.pathname + url.search;
 };
 
+const hasOrg = (reqWithSession: { session?: AppSession }, orgId: string) => {
+  return reqWithSession.session?.organizations?.find(
+    (org) => org === parseInt(orgId)
+  )
+    ? true
+    : false;
```
Comment (djbusstop) [inline src/utils/next.ts:86]:
```suggestion
  return Boolean(reqWithSession.session?.organizations?.find((org) => org === parseInt(orgId));
```

Rather than a turnary, you can use this "Boolean constructor" which will return true if a truthy input, and false if a falsy input

Comment (djbusstop) [reply src/utils/next.ts:86]: This isn't formatted properly so you can't just approve it, sorry!

Comment (ziggabyte) [reply src/utils/next.ts:86]: Oooh fancy!! :D

File: src/utils/next.ts [hunk 5]
```diff
@@ -141,11 +157,28 @@ export const scaffold =
...
+            reqWithSession.session.organizations = null;
+          }
+          if (!hasOrg(reqWithSession, orgId)) {
+            return {
+              notFound: true,
+            };
+          }
+        }
+      }
     }
```
Comment (djbusstop) [inline src/utils/next.ts:177]: I'm sorry if this is annoying but I would love some comments here

File: src/utils/next.ts [hunk 6]
```diff
@@ -141,11 +157,28 @@ export const scaffold =
...
+          } catch (error) {
+            reqWithSession.session.organizations = null;
+          }
+          if (!hasOrg(reqWithSession, orgId)) {
+            return {
+              notFound: true,
+            };
+          }
+        }
+      }
```
Comment (djbusstop) [inline src/utils/next.ts:176]: I'm sorry if this is annoying but I would love some comments here

File: src/utils/next.ts [hunk 7]
```diff
@@ -97,9 +108,16 @@ export const scaffold =
...
+    const reqWithSession = req as IncomingMessage & {
+      cookies: NextApiRequestCookies;
+      session: AppSession;
+    };
 
-    const reqWithSession = req as { session?: AppSession };
-    if (reqWithSession.session?.tokenData) {
+    if (!('session' in reqWithSession)) {
+      throw new Error('Session was not applied correctly.');
+    }
```
[the remark this answers is not in the document]
Comment (ziggabyte) [reply src/utils/next.ts:118]: so i add dependency to newest version of next-session, and use the applySession in that insted?

File: src/utils/next.ts (hunk 6 above)
Comment (ziggabyte) [reply src/utils/next.ts:176]: Very good suggestion!

File: playwright/tests/organize/memberships.spec.ts [hunk 8]
```diff
@@ -0,0 +1,54 @@
...
+          id: RosaLuxemburg.id,
+          name: RosaLuxemburg.first_name + ' ' + RosaLuxemburg.last_name,
+        },
+        role: 'witch',
+      },
+    ];
+
+    login(RosaLuxemburg, memberships);
+    const response = await page.goto(appUri + '/organize/1/campaigns');
+    expect(response?.status()).toEqual(404);
```
[the remark this answers is not in the document]
Comment (djbusstop) [reply playwright/tests/organize/memberships.spec.ts:29]: Dang, you're right! I thought it redirected. This is perfect then :1st_place_medal:

File: src/pages/index.tsx (hunk 3 above)
Comment (djbusstop) [reply src/pages/index.tsx:57]: Hm I'm not sure I know enough about the code, but I just put a console log on `index` and it never showed. So I think this code only has to do with the index page. But I don't know well enough to say for sure, curious what @richardolsson knows

File: src/utils/next.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (djbusstop) [reply src/utils/next.ts:118]: nah I think we shouldn't update now, too many moving parts. But I think you can remove 116 - 118 (ironic since I told you to do it)

File: src/utils/next.ts (hunk 4 above)
Comment (richardolsson) [reply src/utils/next.ts]: Nice! I saw this and had a similar idea, except I usually do `!!someTruthyOrFalsyExpression` instead of `Boolean(someTruthyOrFalsyExpression)`. I think wither way is more concise than ternary. 😊

File: src/pages/index.tsx (hunk 3 above)
Comment (richardolsson) [reply src/pages/index.tsx:57]: Thanks for tagging me!

I haven't really looked closely at any code in this PR, but @ziggabyte is right about architecture/flow. All users are always redirected to the index page after logging in. The index page is configured on the OAuth2 client as the redirect page, and is responsible for exchanging the authorization code for a token, and storing that in the session. Then the user may or may not be redirect to another page on the site. So this is always where the session is first created, and hence where the user's memberships/organizations is first retrieved.

For most users, the organizations will never be retrieved again. They're cached in the session data for the duration of their session. The only time `scaffold()` will retrieve organizations is when a logged in user tries to navigate to an organization to which they don't have access, at which point `scaffold()` will re-fetch the organizations to make sure that hasn't changed during the session. That could happen when someone logs in, notices they don't have access to organization X, tells a comrade who promotes them, and then tries again without logging out and back in again.

File: src/utils/getOrganizations.ts [hunk 9]
```diff
@@ -0,0 +1,15 @@
+import { ScaffoldedContext } from './next';
+import { ZetkinMembership } from 'types/zetkin';
+
+const getOrganizations = async (ctx: ScaffoldedContext): Promise<number[]> => {
```
Comment (richardolsson) [inline src/utils/getOrganizations.ts:4]: I think this function's name does not really reflect what it does. I think something like `getUserOrganizations` or `getUserMemberships` would be more suitable. Do you mind renaming it?

**Review by richardolsson — CHANGES_REQUESTED** [review]
Great work on this! I only really would like a function to be renamed, and that's it. 💯

File: src/utils/getOrganizations.ts (hunk 9 above)
Comment (ziggabyte) [reply src/utils/getOrganizations.ts:4]: Would love to rename 😸

**Review by richardolsson — APPROVED** [review]
