### PR TITLE
Issue 2177: Updates Call History Smart Search logic and YML

### LINKED ISSUE #2177: Smart Search: Search criteria misleading in English and all translations
## Description
There is a filter/selection for the Smart Search feature which allows an admin user to search for people based on their phone call history. One criteria is to search for people who have not been reached in a certain call assignment, but it's labelled in a misleading way making it sound like it will only find people who were called and not reached, when in fact it finds people who were not reached regardless of whether they were called.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Click on "Create"
3. Click on "Create list"
4. In the new list, click "Configure" under "Configure Smart Search list"
5. Click "Add/remove people"
6. Find and add the "Call history" filter
7. Open the dropdown that is by default configured to "have been called"
8. Pick the third option
9. Click "Save selection"

### Expected Behaviour
The options should be:

* "have been called" (operator is `called`)
* "have been successfully reached" (operator is `reached`)
* "have not been reached" (operator is `notreached`)

Selecting the third option should also remove the "at least N times" part of the sentence, and remove the `minTimes` data from the configuration.

### Actual Behaviour
The third option is "have been unsuccessfully tried", which sounds like the people that match have been called but not reached (incorrect) and the `minTimes` part remains in the `configuration` that is sent to the API (check browser network panel to verify).

## Screenshots (if you have any)
image

## Proposed solution
A solution to this issue will have to:

- [ ] Update the label to better reflect what the filter actually does
- [ ] Remove all translations of the faulty label from YAML files so that they can be redone
- [ ] Modify the logic to remove the "at least N times" from the UI and the `minTimes` from the configuration when picking the `notreached` option

### PR DESCRIPTION
**Pull request by MattettaM**
## Description
This PR makes changes to the Call History Smart Search function to make the Not Reached option more accurate and removes the minTimes segment of the Sentence render when Not Reached is selected.

## Screenshots
image
image

## Changes
- Rewords the notreached string to be more in line with what the issue states
- Changes the logic to not display the minTimes segment when notreached is selected
- Removes affected localization strings

## Notes to reviewer
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Click on "Create"
3. Click on "Create list"
4. In the new list, click "Configure" under "Configure Smart Search list"
5. Click "Add/remove people"
6. Find and add the "Call history" filter
7. Open the dropdown that is by default configured to "have been called"
8. Pick the third option that should now be called "have not been reached"
9. The sentence render should now be updated to remove "at least" and the amount selection.

## Related issues
Resolves #2177

### CODE REVIEW

**Review by richardolsson — CHANGES_REQUESTED** [review]
So great of you to take this on! The Smart Search UI code is very complex and I know it can be difficult to navigate.

Everything that you've done looks great. But I'm still missing two things, as described below. Can you have a look at fixing them before we proceed to merge this?

First, when the sentence is rendered in "display" mode (in the summary of the entire Smart Search), the word "once" is still displayed:

image

Second, the `minTimes` attribute is still being sent to the server. Whenever the the operator is `notreached`, the `minTimes` attribute needs to be removed from the configuration. This bug is the reason why the search comes up empty, even though there are hundreds of people that haven't been reached. You can confirm that `minTimes` is currently being sent to the server by saving the query and looking in the network panel.

image

File: src/features/smartSearch/components/filters/CallHistory/index.tsx [hunk 1]
```diff
@@ -156,12 +156,21 @@ const CallHistory = ({
...
               <StyledSelect
-                onChange={(e) =>
-                  setConfig({
-                    ...filter.config,
-                    operator: e.target.value as CALL_OPERATOR,
-                  })
-                }
+                onChange={(e) => {
+                  const callOperator = e.target.value as CALL_OPERATOR;
+                  if (callOperator == CALL_OPERATOR.NOTREACHED) {
```
Comment (richardolsson) [inline src/features/smartSearch/components/filters/CallHistory/index.tsx:161]: Nice! 💯

**Review by richardolsson — APPROVED** [review]
Awesome work! This seems to be ready to merge now.

I have reviewed the code and tried the preview build to make sure that the correct data is being sent to the server and that the UI works as expected.

This was a challenging task and I'm super impressed by how quickly and nicely you solved it! 💯
