### PR TITLE
Issue-2496 Adding amount of people per tag

### LINKED ISSUE #2496: Imports: Validate/preview feedback about tags is confusing
## Description
When importing using the Zetkin importer UI, it's possible to map values in a column to tags in Zetkin. It's actually possible to map the same value to multiple tags, or use multiple values or multiple columns to apply multiple tags to people.

When doing so, the UI lists the tags that will be applied, and prints how many people will have one or more tags applied, but in doing so it can easily be understood as all tags being added to all people.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people and sign as testadmin@exampl.com
2. Click on "Create" (big button, top right)
3. Click "Import people" 
4. Drag and drop a CSV file with the content described under "Example file" below
5. Select "FNAME" and configure to import as "First name"
6. Select "LNAME" and configure to import as "Last name"
7. Select "TAG1" and configure to import as tag
8. Map "x" to 2 tags of your choosing
9. Select "TAG2" and configure to import as tag
10. Map "x" to 1-2 tags of your choosing
11. Click "Validate"
12. Do NOT actually execute the import in the next step – just look at the summary

### Expected Behaviour
The summary should list what tags are being imported, and how many people will have each of the tags applied, e.g:

* Activist: 2 people
* Member: 2 people

### Actual Behaviour
The summary lists the tags that are being imported, and says "2 people will have tags added", causing confusion about whether all tags will be applied to all people or not.

### Example file
This file has two people in it, one with an x in the column called "TAG1" and the other with an x in the column "TAG2".

```csv
FNAME,LNAME,TAG1,TAG2
Clara,Zetkin,x,
Richard,Olsson,,x
```

### Tag columns configured
Image

### Preview result

Image

## Proposed solution
This should be a fairly simple task, because the data from the server does actually list the number of affected person, by tag. See `data.stats.person.summary.tagged.byTag` in the data below.

```json
{
    "data": {
        "stats": {
            "person": {
                "summary": {
                    "addedToOrg": {
                        "byOrg": {},
                        "total": 0
                    },
                    "created": {
                        "total": 0
                    },
                    "tagged": {
                        "byTag": {
                            "4": 3,
                            "10": 4
                        },
                        "total": 4
                    },
                    "updated": {
                        "byChangedField": {},
                        "byInitializedField": {},
                        "total": 0
                    }
                }
            }
        },
        "problems": []
    }
}
```

### PR DESCRIPTION
**Pull request by MattettaM**
## Description
This PR adds information about the amount of people that will receive each added tag when importing a list

## Screenshots
image

## Changes

* Adds Box containing the TagChip and number of people that will receive that tag
* Changes the Box layout to be inline to display each tag separately

## Notes to reviewer

1. Go to https://app.dev.zetkin.org/organize/1/people and sign as [testadmin@exampl.com](mailto:testadmin@exampl.com)
2. Click on "Create" (big button, top right)
3. Click "Import people"
4. Drag and drop a CSV file with the content described under "Example file" in the linked issue
5. Select "FNAME" and configure to import as "First name"
6. Select "LNAME" and configure to import as "Last name"
7. Select "TAG1" and configure to import as tag
8. Map "x" to 2 tags of your choosing
9. Select "TAG2" and configure to import as tag
10. Map "x" to 1-2 tags of your choosing
11. Click "Validate"
12. Do NOT actually execute the import in the next step – just look at the summary

The tags should now display the amount of people who will receive each tag

## Related issues
Partially Resolves #2496
Still needs design

### CODE REVIEW

**Comment by richardolsson** [comment]
This is great work by @MattettaM, but requires that a designer takes a look at it. Would you care to, @Bagera or @sefsh?

One idea that might make sense is to put the number in the title, e.g. that a tag called "Activist" becomes "Activist (25)". That would better handle when there are lots of values.

**Comment by Bagera** [comment]
Nice work!

Sorry for the late comment.

I agree with @richardolsson about the solution. As there could be quite a lot of tags, I think the list should just flow left to right.

I have made a mockup of how that would look. I have only looked at the text content of the tags and the flow of the list, so disregard any other inconsistencies.

image

**Comment by MattettaM** [comment]
image

The latest commit makes it look as designed, but I'm not very happy with the solution as it introduces a new optional parameter to TagChip, which shouldn't be required as this could be handled with `tag.value`.

I couldn't figure out how to change this value inside the map iterator however. This is essentially what I would want the solution to look like.

```typescript
<Box display="flex" flexWrap="wrap" gap={1} paddingTop={1}>
    {addedTags.map((tag) => (
        {tag.value = {` (${peoplePerTag[tag.id]})`}}
        <TagChip key={tag.id} tag={tag} />
    ))}
</Box>
```
Then the optional parameter can be removed, and in TagChip, rendering optionalString can be replaced with tag.value, alternatively that we append the peoplePerTag value to tag.title

File: src/features/tags/components/TagManager/components/TagChip.tsx [hunk 1]
```diff
@@ -159,6 +167,7 @@ const TagChip: React.FunctionComponent<{
         <TagToolTip tag={tag}>
           <Box className={classes.label + ' ' + classes.deleteContainer}>
             {tag.title}
+            {optionalString}
```
Comment (richardolsson) [inline src/features/tags/components/TagManager/components/TagChip.tsx:170]: Instead of this, I think we should change the `title` of the tag when rendered in this situation.

File: src/features/import/components/ImportDialog/elements/ImpactSummary/AddedTags.tsx [hunk 2]
```diff
@@ -69,7 +71,11 @@ const AddedTags: FC<AddedTagsProps> = ({
       </Typography>
       <Box display="flex" flexWrap="wrap" gap={1} paddingTop={1}>
         {addedTags.map((tag) => (
-          <TagChip key={tag.id} tag={tag} />
+          <TagChip
+            key={tag.id}
+            optionalString={` (${peoplePerTag[tag.id]})`}
+            tag={tag}
```
Comment (richardolsson) [inline src/features/import/components/ImportDialog/elements/ImpactSummary/AddedTags.tsx:77]: How about this, to change the title directly?

```suggestion
            tag={{
              ...tag,
              title: `${tag.title} (${peoplePerTag[tag.id]})`
            }}
```

This of course doesn't _change_ the tag title, just the way it's rendered, without having to change the API of `TagChip`.

File: src/features/tags/components/TagManager/components/TagChip.tsx [hunk 3]
```diff
@@ -103,9 +103,17 @@ const TagChip: React.FunctionComponent<{
   noWrappedLabel?: boolean;
   onClick?: (tag: ZetkinTag) => void;
   onDelete?: (tag: ZetkinTag) => void;
+  optionalString?: string;
```
Comment (richardolsson) [inline src/features/tags/components/TagManager/components/TagChip.tsx:106]: I would revert this, like you suggested.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Great progress! I think it looks great now in the GUI. I appreciate the update to the PR so that we can talk about the solution you found. Here are my thoughts.

> The latest commit makes it look as designed, but I'm not very happy with the solution as it introduces a new optional parameter to TagChip, which shouldn't be required as this could be handled with `tag.value`.

The `tag.value` attribute is intended for values in "value tags", so we shouldn't use it for this. It would be misleading, but also could conflict with actual tag values.

> I couldn't figure out how to change this value inside the map iterator however. This is essentially what I would want the solution to look like.
> 
> ```ts
> <Box display="flex" flexWrap="wrap" gap={1} paddingTop={1}>
>     {addedTags.map((tag) => (
>         {tag.value = {` (${peoplePerTag[tag.id]})`}}
>         <TagChip key={tag.id} tag={tag} />
>     ))}
> </Box>
> ```

The problem you have here is that the code is using a single-expression function in the mapping, which makes it slightly more complicated. You could switch to a block statement function, but I have another suggestion below.

> Then the optional parameter can be removed, and in TagChip, rendering optionalString can be replaced with tag.value, alternatively that we append the peoplePerTag value to tag.title

The `tag.title` is a good idea IMO and exactly what I would go for! Concrete suggestion below.

**Review by richardolsson — APPROVED** [review]
Nice work! I really like this. It's going to make lots of organizers super happy!
