### PR TITLE
Lazy loading data for person hover card

### LINKED ISSUE #1984: List: Large list has weird scrolling behaviour and error
## Description
When scrolling through a large list, sometimes the scrolling starts jumping erratically and generates an error.

## Steps to reproduce
1. Go to a large list, for example a list with everyone (http://localhost:3000/organize/1/people/lists/123)
2. Scroll down and up until the issue occurs

### Expected Behaviour
* No errors
* Scrolling only occurs when the user is actually scrolling

### Actual Behaviour
* Error occurs
* Weird automatic scrolling behaviour

## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/21238654/96f59e92-65e4-4261-9ffd-75d6e1959148

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR fixes a performance issue in lists (and potentially other places) that can even trigger a browser error. The bug was caused by every avatar in a list loading the relevant person object and it's tags, in case it needs to display the hover card. This happened because the hover card always loads it's data, even before it's displayed, and this PR changes the hover card to only load data once it's opened.

It also fixes an unrelated issue that I came across while testing this, which was that the popper was allowed to open outside of the browser viewport.

## Screenshots
None

## Changes
* Modify `ZUIPersonHoverCard` so that it loads data lazily, i.e. only once the popper actually shows
* Fix an issue causing the `ZUIPersonHoverCard` to display the popper outside of the viewport bounds sometimes
* Removes an obsolete `eslint-disable` comment

## Notes to reviewer
Please play around with hover cards all over the place, as this affects all hover cards, not just the ones in lists.

## Related issues
Resolves #1984

### CODE REVIEW

File: src/zui/ZUIPersonHoverCard.tsx [hunk 1]
```diff
@@ -82,86 +76,93 @@ const ZUIPersonHoverCard: React.FunctionComponent<{
...
-                  .filter((field) => !!person[field])
-                  .map((field) => {
-                    const value = person[field];
-                    const linkType = field.includes('mail')
-                      ? 'mailto:'
-                      : field.includes('phone')
-                      ? 'tel:'
-                      : '';
+        <Fade in={open} timeout={200}>
+          <Box>{open && <HoverCardContent personId={personId} />}</Box>
```
Comment (kaulfield23) [inline src/zui/ZUIPersonHoverCard.tsx:80]: So nice solution! 😸

**Review by kaulfield23 — APPROVED** [review]
I can't spot anything weird..! I tested both `main` and this branch for comparison. These changes improve performance a lot!
