### PR TITLE
remove selection bar on delete from event popper

### LINKED ISSUE #1491: Deleting a selected event in the calendar does not close the bottom bar
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
I had created a few events in my project calendar and wanted to delete some of them via their "event poppers". Along the way one of the events got marked (in the checkbox) before I deleted it, and when it was deleted the bottom-bar still stayed. It seems the state of an event being checked did not get cleared when the checked event no longer exists.

## Steps to reproduce
1. Go to a project that has events, or create some events in a project
2. go to the calendar
3. check the checkbox of one event 
4. notice the bottom bar appear
5. now delete the checked event using the ellipsis menu on its "event popper"

### Expected Behaviour
The bottom bar disappears, as the only checked event no longer exists

### Actual Behaviour
The bottom bar is still there, saying 1 event is selected

## Screenshots (if you have any)
bild

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR fixes a bug where event selection bar remains even after deleting the event from single event popper.

## Screenshots

https://github.com/zetkin/app.zetkin.org/assets/77925373/2f227ba6-4b89-46d8-a6f8-f046a1946d69

It has weird error but except for that, the function is working as expected.

## Changes

* Adds `eventDeselected` in store

## Notes to reviewer
I could use existing `eventsDeselected` reducer and dispatch like `store.dispatch(eventsDeselected([event]));` but it is not event"s" and felt weird to send the whole event there when it only needs `eventId`. So I created `eventDeselected` instead.

## Related issues
Resolves #1491

### CODE REVIEW

File: src/features/events/store.ts [hunk 1]
```diff
@@ -113,6 +113,12 @@ const eventsSlice = createSlice({
         );
       }
     },
+    eventDeselected: (state, action: PayloadAction<number>) => {
```
Comment (niklasva82) [inline src/features/events/store.ts:116]: There is already an eventsDeselected, why not use that one?

**Review by niklasva82 — CHANGES_REQUESTED** [review]
Great work! But I struggle to understand why you  basically reimplemented the eventsDeselected reducer but for a single event rather than just reuse the existing one and provide an array with the one event id as payload?

File: src/features/events/store.ts (hunk 1 above)
Comment (kaulfield23) [reply src/features/events/store.ts:116]: As I wrote in Note to reviewer, it feels weird for me to use `eventsDeselected` because this is not event"s" and other reducers have reducer for "event" and "events". For example, `eventCreated`,`eventsCreated` / `eventLoaded`, `eventsLoaded` / `eventUpdated`, `eventsUpdated` etc... So I followed a same pattern here. But I can use existing `eventsDeselected` reducer! I was just unsure what is the best in this case!

**Review by niklasva82 — APPROVED** [review]
Great! Other than that issue I have no complaints.
