### PR TITLE
Fix survey sorting

### LINKED ISSUE #1703: Sort survey submission by First name, Last name and email.
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
In the list of survey submissions you can currently sort the Date and Respondent columns, but not columns of First name, Last name and Email. 

## Steps to reproduce
1. Go to the submissions tab of a survey with submissions, for example `organize/1/standalone/surveys/1/submissions`
2. Click on the little arrow next to the column header in the Date or Respondent column
3. Notice that the columns get sorted
4. Now click on the same little arrow in the First name, Last name or email columns

### Expected Behaviour
Sorts the values in these columns 

### Actual Behaviour
Does nothing

### PR DESCRIPTION
**Pull request by alexandrakoch**
## Description
This PR adds sorting for all survey submission fields using a `sortComparator` in the `makeSimpleColumn` function

## Changes
* Adds a `GridComparatorFn`, `alphabeticalComparator`, to `SurveySubmissionsList.tsx` to compare values alphabetically
* Adds a `sortComparator` (`alphabeticalComparator`) and `valueGetter` to the `makeSimpleColumn` function to enable alphabetical sorting for those columns

## Related issues
Resolves #1703

### CODE REVIEW

File: src/features/surveys/components/SurveySubmissionsList.tsx [hunk 1]
```diff
@@ -14,13 +14,18 @@ import ZUIRelativeTime from 'zui/ZUIRelativeTime';
...
   GridRenderCellParams,
   useGridApiContext,
 } from '@mui/x-data-grid-pro';
 import { FC, useEffect, useMemo } from 'react';
 import { Msg, useMessages } from 'core/i18n';
 import { ZetkinPerson, ZetkinSurveySubmission } from 'utils/types/zetkin';
 
+const alphabeticalComparator: GridComparatorFn<string> = (v1, v2) =>
+  //compares strings alphabetically, locale aware
+  v1.localeCompare(v2);
```
Comment (kaulfield23) [inline src/features/surveys/components/SurveySubmissionsList.tsx:27]: Nice way that sorting with `sortComparator` that gets value from `valueGetter`! I just tested it, and got this error from `alphabeticalComparator` when there is no value in a cell.
image

**Review by kaulfield23 — CHANGES_REQUESTED** [review]

**Comment by ziggabyte** [comment]
@alexandrakoch do you wanna finish this, or should someone from the team take over? Either is fine :D

**Review by ziggabyte — APPROVED** [review]
I took over to finish the last bits of this! Great job getting it started! :D
