### PR TITLE
Change User menu links

### LINKED ISSUE #3469: Activist Portal: User menu links
### The feature

In the activist portal, users can click their avatar to bring up the user menu where they can navigate between different pages and log out.

### The bug

The user menu includes links to pages that are very close to each other and that don't need to have their own links while missing a link to the organize part of zetkin.

## Steps to reproduce

1. Go to [https://app.dev.zetkin.org/o/1](https://app.dev.zetkin.org/o/1)
2. Click on on the avatar

### Expected Behaviour

I expect a menu containing the following:
- My Zetkin 
- Organize (If applicable)
-  Settings
- [---]
-  Log out

### Actual Behaviour

The menu contains links that are superfluous and misspelled and lacks an organize link:

- My activities
- All events 
-  Settings
- [---]
-  Logout

## Screenshots

Image

### PR DESCRIPTION
**Pull request by buegeleisen**
## Description
This PR restructures the Avatar User menu

## Screenshots
Screenshot 2026-02-14 at 19 48 10

## Changes
* Adds Organize link if applicable
* Changes the links to My Zetkin

## Notes to reviewer
None

## Related issues
Resolves #3469

### CODE REVIEW

File: src/features/public/components/ActivistPortalHeader/index.tsx [hunk 1]
```diff
@@ -40,16 +40,23 @@ const ActivistPortalHeader: FC<Props> = ({
...
         onClick: () => router.push('/my/home'),
       },
-      {
-        label: messages.home.menu.allEvents(),
-        onClick: () => router.push('/my/feed'),
-      },
+      ...(isOfficial
+        ? [
+            {
+              label: 'Organize',
```
Comment (ziggabyte) [inline src/features/public/components/ActivistPortalHeader/index.tsx]: This string should be localized, so it can be translated to the different locales we support! You can look at how the message on row 49 is created and use a similar logic :)

File: src/features/public/components/ActivistPortalHeader/index.tsx [hunk 2]
```diff
@@ -40,16 +40,23 @@ const ActivistPortalHeader: FC<Props> = ({
     useState<HTMLButtonElement | null>(null);
   const router = useRouter();
 
+  const memberships = useUserMemberships();
+  const isOfficial = memberships.find((membership) => membership.role != null);
+
   const menuItems: MenuItem[] = useMemo(
     () => [
       {
-        label: messages.home.menu.myActivities(),
```
Comment (ziggabyte) [inline src/features/public/components/ActivistPortalHeader/index.tsx]: This message, `myActivities` is not used anywhere now that you have removed it from here, so you can delete that from the messageIds file!
