### PR TITLE
Issue 1937/event title empty string

### LINKED ISSUE #1937: Event: The default title of newly created event is empty string ("")
## Description
When I create a single event by dragging the mouse on the weekly view in the Calendar or by clicking "Create event" in the "Create Activity" button, the newly created event has default title ""(empty string) in database.
## Steps to reproduce -1
1. Go to any project. For example 'http://localhost:3000/organize/1/projects/11'
2. Click on 'Create Activity'
3. Click on 'Create Event' and check the event ID
4. Now check the data of newly created event. For example 'http://localhost:3000/api/orgs/1/actions/${eventId}'
## Steps to reproduce -2
1. Go to any project. For example 'http://localhost:3000/organize/1/projects/11'
2. Click on 'Calendar'
3. Click on 'Week'
4. Drag a mouse on random date and click on 'Create single event'.
5. Check the event ID
6. Now check the data of newly created event. For example 'http://localhost:3000/api/orgs/1/actions/${eventId}'

### Expected Behaviour
The default title of an event should be `null`
### Actual Behaviour
The default title is `""`
## Screenshots (if you have any)
image
image

### PR DESCRIPTION
**Pull request by helihard**
## Description
This PR creates events with null title via campaign action button and via calendar week view.

## Changes
- Changes the default title of newly created event to null via campaign action button
- Changes the default title of newly created event to null via calendar week view

## Notes to reviewer
None

## Related issues
Resolves #1937

### CODE REVIEW

File: src/features/calendar/components/CalendarWeekView/index.tsx [hunk 1]
```diff
@@ -307,32 +308,3 @@ const CalendarWeekView = ({ focusDate, onClickDay }: CalendarWeekViewProps) => {
 };
 
 export default CalendarWeekView;
-
-function useCreateEvent() {
```
Comment (ziggabyte) [inline src/features/calendar/components/CalendarWeekView/index.tsx:311]: Lovely to see this go 👋

File: src/features/calendar/components/CalendarWeekView/index.tsx [hunk 2]
```diff
@@ -254,10 +252,13 @@ const CalendarWeekView = ({ focusDate, onClickDay }: CalendarWeekViewProps) => {
...
-                            await createAndNavigate(
-                              pendingEvent[0],
-                              pendingEvent[1]
-                            );
+                            await createEvent({
+                              activity_id: null,
+                              end_time: pendingEvent[1].toISOString(),
+                              location_id: null,
+                              start_time: pendingEvent[0].toISOString(),
+                              title: null,
```
Comment (ziggabyte) [inline src/features/calendar/components/CalendarWeekView/index.tsx:260]: so nice and neat now :)

**Review by ziggabyte — APPROVED** [review]
Woop woop for issue number 2!! :D
