### PR TITLE
stop sidebar animation flicker when reloading page

### LINKED ISSUE #1685: Sidebar/menu animates too aggressively
## Description
The menu on the left-hand side on all /organize/ID pages animates on every page load / navigation. I think it should only animate when the user triggers it to open/close.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1
2. Make sure the navbar on the left is open (click little arrow over logo if not)
3. Reload the page

### Expected Behaviour
The navbar should be open immediately.

### Actual Behaviour
The navbar starts closed, but expands on refresh.

## Screenshots (if you have any)
None

### PR DESCRIPTION
**Pull request by nanoobop**
remove open attribute didn't have an affect

## Description
stop sidebar animation flicker when reloading page

## Changes
Change defaultstate on Open from false to LastOpen
Removed the open attribute from Drawer since I didn't see it having an effect.

## Notes to reviewer
open drawer, reload page 
close drawer reload page

## Related issues
Resolves #1685

### CODE REVIEW

File: src/zui/ZUIOrganizeSidebar/index.tsx [hunk 1]
```diff
@@ -88,20 +88,14 @@ const ZUIOrganizeSidebar = (): JSX.Element => {
 
   const [checked, setChecked] = useState(false);
   const [lastOpen, setLastOpen] = useLocalStorage('orgSidebarOpen', true);
-  const [open, setOpen] = useState(false);
+  const [open, setOpen] = useState(lastOpen);
```
Comment (richardolsson) [inline src/zui/ZUIOrganizeSidebar/index.tsx:91]: So simple! Nice work. 💯

File: src/zui/ZUIOrganizeSidebar/index.tsx [hunk 2]
```diff
@@ -88,20 +88,14 @@ const ZUIOrganizeSidebar = (): JSX.Element => {
...
 
   const handleExpansion = () => {
     setChecked(!checked);
   };
 
-  useEffect(() => {
-    if (lastOpen != open) {
-      setOpen(lastOpen);
-    }
-  }, []);
```
Comment (richardolsson) [inline src/zui/ZUIOrganizeSidebar/index.tsx:103]: Of course! I'm glad you thought about this.

**Review by richardolsson — APPROVED** [review]
Awesome work! I've tried the preview build and reviewed the code and it looks great. I'm going to be sooooo much less annoyed when I'm navigating around Zetkin going forward. I'm happy! 🎉
