### PR TITLE
Issue 3365 - Removes US-centric locale for smart search date picker

### LINKED ISSUE #3365: Smart Search: Date format and date picker use wrong locale (MM/DD/YYYY and week starting on Sunday)
### The feature

Smart search helps the user to find correct target group based on several criterias. This specific criteria, 'any point in time', help the user to narrow the search based on date and time.

### The bug

Date format and date picker use wrong locale (MM/DD/YYYY and week starting on Sunday). This is problematic as it does not adjust to the users  local environment settings.

Currently we don't have any users in the US, so the preferred format would be YYYY/MM/DD and the week should start on a Monday.

## Steps to reproduce

1. Go to https://app.dev.zetkin.org/organize/1/projects/410/callassignments/154
2. Click on the button 'Edit Target Group'
3. Click on the button 'Add / Remove People'
4. Select people based on 'Events - Select based on data from events'
5. Click on filter labeled 'at any point in time' 

### Expected Behaviour

Date format and date picker is reflecting the users local environment settings, YYYY/MM/DD, and week starts on a Monday.

### Actual Behaviour

Date format and date picker use wrong locale (MM/DD/YYYY and week starting on Sunday). 

## Screenshots

Image

Image

https://github.com/user-attachments/assets/5a803393-89d6-47c6-9a46-ff26f8f84be5

### PR DESCRIPTION
**Pull request by MattettaM**
## Description
This PR fixes issues regarding the smart search date picker and the displayed date format to not be US-centric.

## Screenshots
image

## Changes
Updates the smart search date picker week to start on a Monday.
Changes the date format in the smart search to YYYY/MM/DD.

## Notes to reviewer
Go to a organizing page where you can access the smart search, such as adding participants to a call event. Choose to add users based on participation. In the smart search, filter for participants who participated before, or after, a specific date. The date should now be in the new format, and when selecting the date, the date picker should now display Monday as the first day.

## Related issues
Resolves #3365

### CODE REVIEW

File: src/features/smartSearch/components/inputs/StyledDatePicker.tsx [hunk 1]
```diff
@@ -1,14 +1,18 @@
...
+import updateLocale from 'dayjs/plugin/updateLocale';
 import { useTheme } from '@mui/material';
 import { DatePicker, DatePickerProps } from '@mui/x-date-pickers/DatePicker';
 
 const StyledDatePicker: React.FC<DatePickerProps<dayjs.Dayjs>> = (
   props
 ): React.ReactElement => {
   const theme = useTheme();
+  dayjs.extend(updateLocale);
+  dayjs.updateLocale('en', { weekStart: 1 });
```
Comment (richardolsson) [inline src/features/smartSearch/components/inputs/StyledDatePicker.tsx]: I agree that it's not ideal to hardcode this like this, and I'm guessing that even though it's happening here, it probably affects the entire system.

**Review by ziggabyte — CHANGES_REQUESTED** [review]
I think this can be solved by using the `adapterLocale` property on `LocalizationProvider`! There is a little util component I built for the Zui design system components that uses this property - it basically tells all MUI components inside the `LocalizationProvider` what way it should show dates and times! That component is called "LocaleSwitcher" (i used it to test that something would look good in all different locales). 

So if we pass the same locale as we are using for text translations, to the `LocalizationProvider` wherever we use it, all date pickers should show dates in whatever way is common for that locale. 

English would be the problem - since I assume simply using "en" falls back to "en-US" as standard, but it's worth a try!
