### PR TITLE
Invalidate milestones on checkbox click

### LINKED ISSUE #2361: Journeys: Milestone checkbox does not refresh after toggle
## Description
The Journeys feature in Zetkin tracks people along some journey (e.g. new members, or casework in a union). A journey has milestones. When the organizer clicks on a milestone, the updated state is added to the journey's timeline, but there is currently a bug that's causing the UI to not update.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/journeys
2. Go into any journey
3. Go into any journey instance (an item in the journey list)
4. Go to the "Milestones" tab
5. Click a checkbox next to a milestone

### Expected Behaviour
The state should update in the server/timeline and the UI should update to reflect the new state.

### Actual Behaviour
The state does update on the server/timeline, but the UI on the page does not update. Refreshing the page shows the updated state.

### After clicking "Evidence collected" (nothing visibly happened)
image

### After reloading
image

### PR DESCRIPTION
**Pull request by k-nut**
## Description
This PR invalidates the milestones of a journey instance when updating the status. This should lead to the page automatically updating the visible UI state after a button is checked, rendering a manual reload unnecessary. 

## Screenshots
https://github.com/user-attachments/assets/b34b798c-3e3e-46ce-8fd7-bb4bfc62e32b

## Notes to reviewer
I have added a new invalidation call to `useUpdateMilestoneStatus`. It calls the new `invalidateJourneyInstanceMilestones` function which invalidates the `state.milestonesByInstanceId[instanceId]` of the passed journey id. 

I hope that this is the right way to do this. An alternative that I had considered was to instead change `invalidateJourneyInstance` which was exposed already to also invalidate the milestones but my understanding is that -since this function is also called from other places - it doesn't always warrant invalidating the milestones as well.

## Related issues
Resolves #2361

### CODE REVIEW

File: src/features/journeys/store.ts [hunk 1]
```diff
@@ -55,6 +55,13 @@ const journeysSlice = createSlice({
         }
       }
     },
+    invalidateJourneyInstanceMilestones: (
+      state,
+      action: PayloadAction<number>
+    ) => {
+      const instanceId = action.payload;
+      state.milestonesByInstanceId[instanceId].isStale = true;
```
Comment (richardolsson) [inline src/features/journeys/store.ts:63]: I actually do think that this could be added to the existing `invalidateJourneyInstance` action. If the journey instance has changed, I think it's fair to also reload the state of the milestones, which is a cheap operation.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work getting acquainted with the redux store! I'm glad you were able to find what was causing this bug and that it wasn't more complex than this.

As you point out in "Notes to reviewer", the alternative solution would be to add the additional state mutation to `invalidateJourneyInstance()` and I actually think that is better. Would you mind making that change?

**Comment by k-nut** [comment]
I see that the playwright tests are failing now. I'm gonna take a look 👀

**Comment by richardolsson** [comment]
> I see that the playwright tests are failing now. I'm gonna take a look 👀

I think it's likely that this is not a bug, but rather a fault in the test. I'm guessing that the test isn't mocking the API calls for milestones or something like that, and before that API request was never made in the test (because the milestones were not invalidated) and now it is.

This is just my guesstimate, but in general I would trust your code in this case, and assume that you will need to make changes to the test rather than making changes to the program code.

I could of course be wrong and the test has found some bug, so it's worth investigating. I just don't want you to doubt your own code any more than you doubt the tests, in this case. 😊

**Comment by k-nut** [comment]
I'm a bit lost as to what is happening here. I agree with your reasoning that this is probably related to the setup of the mocks. My understanding is as follow:
- I am now invalidating the journey instance milestones
- This leads to `useJourneyInstanceMilestones`'s `loadListIfNecessary` to trigger another call to get the latest data. Just like `useJourneyInstance`'s `loadItemIfNecessary` (which seems to be triggered and mocked already), it makes a call to `api/orgs/${orgId}/journey_instances/${instanceId}` but discards everything but the milestones.

I'm unsure how the testing setup works with moxy. Do we need to tell it to use the same mock twice? Just duplicating it did not seem to help. It could of course also be that I'm misunderstanding something here. Any pointers are welcome :)

**Comment by richardolsson** [comment]
I investigated a little bit, and it seems like the tests have actually found a bug. Thank you Playwright!

I'm not sure how your change can be causing this bug, but for sure there is a bug. Here's how to reproduce. Can you please investigate?

1. Go to https://localhost:3000/organize/1/journeys
2. Go into the case journey
3. Go into any case
4. Add a new assignee
5. Remove the assignee by clicking the X

Expected results:
API requests should be made in result to the actions taken in steps 4 and 5, and the UI should update after step 4 and again after step 5.

Actual results:
The API requests are made correctly, but the UI does not update without a full page refresh, either on step 4 or 5.

image

**Comment by richardolsson** [comment]
I just realized when I tried this in deveopment that an error is thrown by the line of code that you've added, because sometimes the milestones have not been loaded (so `instanceId` is not a valid key). That seems to be causing this bug. 😊

File: src/features/journeys/store.ts [hunk 2]
```diff
@@ -44,6 +44,7 @@ const journeysSlice = createSlice({
       const instanceItem = state.journeyInstanceList.items.find(
         (item) => item.id == instanceId
       );
+      state.milestonesByInstanceId[instanceId].isStale = true;
```
Comment (richardolsson) [inline src/features/journeys/store.ts:47]: `state.milestonesByInstanceId[instanceId]` can be `undefined`, if the user has not visited the milestones page before interacting with the journey some other way.

**Review by richardolsson — CHANGES_REQUESTED** [review]

File: src/features/journeys/store.ts [hunk 3]
```diff
@@ -48,9 +48,12 @@ const journeysSlice = createSlice({
       if (instanceItem) {
         instanceItem.isStale = true;
         if (instanceItem.data) {
-          if (state.timelineUpdatesByInstanceId[instanceItem.data?.id]) {
-            state.timelineUpdatesByInstanceId[instanceItem.data?.id].isStale =
-              true;
+          const { id } = instanceItem.data;
```
Comment (k-nut) [inline src/features/journeys/store.ts:51]: I'm not quite sure I understand what this id is. I think it should be identical to the `instanceId` that is passed in as the payload? If so, I'm not sure why it is being picked again from a more nested field here. I'd appreciate some pointers :)

**Comment by k-nut** [comment]
Ah thank you for the explanation @richardolsson! I have now modelled this much more closely to the existing code but I have some more questions. At least both my manual tests and the playwright tests worked now though.

File: src/features/journeys/store.ts (hunk 3 above)
Comment (richardolsson) [reply src/features/journeys/store.ts:51]: Yes, I agree that this should be the same as `instanceId`.

**Review by richardolsson — APPROVED** [review]
I have reviewed the changes and tried the preview build again. Everything is working as expected now!

You're right that we could have used `instanceId` instead, but I don't think that needs to prevent this from being merged. Let's get this merged! 💯
