### PR TITLE
Issue 2802/superuser access to lists

### LINKED ISSUE #2802: Lists: Superuser cant see lists from orgs they are not an official in
### The feature

"Lists" is a feature in Zetkin which allows organizer users to create lists of people. 

"Superuser" is a type of user in Zetkin, someone who has access to everything, everywhere. It's basically @richardolsson, so he can help orgs debug and understand problems. 

### The bug

When a superuser goes to a list of an org that they are not also an admin in, they get redirected to the "shared" version of the list. annoying.

## Steps to reproduce
0. If  you are already logged in as testadmin@example... , go to https://app.dev.zetkin.org/logout to become logged out
1. On that same page, log in as `testsuperuser@example.com`, with password `password` and phone code `999999`
2. Go to https://app.dev.zetkin.org/organize/1/people/lists/10/

### Expected Behaviour
You get to the editable, normal verison of the list

### Actual Behaviour
You get redirected to the "shared" version of the list (https://app.dev.zetkin.org/organize/1/people/lists/10/shared)

## Screenshots
Image

## Hints
This is where the logic to redirect someone that is not an official happens, in `src/pages/organize/{orgId}/people/lists/{viewId}/`, this is where we need to also let a superuser pass through and not get caught :) 

Image

### PR DESCRIPTION
**Pull request by owenboy9**
## Description
When a superuser goes to a list of an org that they are not also an admin in, they get redirected to the "shared" version of the list. 

## Screenshots
[Add screenshots here]

## Changes

* create getSuperUser file & function in utils specifically to filter out non-superusers
* incorporate it into index.tsx where it's used, in combination with getSuperUser, to allow superuser to see full lists instead of being redirected to the ones available to everyone

## Notes to reviewer
If you are already logged in as testadmin@example... , go to https://app.dev.zetkin.org/logout to become logged out
On that same page, log in as testsuperuser@example.com, with password password and phone code 999999
Go to https://app.dev.zetkin.org/organize/1/people/lists/10/

## Related issues
Resolves #2802 

regular user gets: Error during request: 403, http://localhost:3000/api/orgs/1/people/fields 
when trying to access the same list

### CODE REVIEW

**Comment by richardolsson** [comment]
I will rebase the relevant commit and open a new PR, and @ziggabyte will review.

**Comment by richardolsson** [comment]
I rebased the relevant commit and force-pushed it. Handing over to @ziggabyte for review.

File: src/utils/getSuperUser.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+  ctx: ScaffoldedContext,
+  allowAnyone = false
+): Promise<boolean> => {
+  const userStatusRes = await ctx.z.resource('users', 'me').get();
+  const userData = userStatusRes.data.data as ZetkinUser;
+
+  return !!(allowAnyone || userData?.is_superuser);
+};
+
+export default getSuperUser;
```
Comment (ziggabyte) [inline src/utils/getSuperUser.ts:14]: I see that you've looked at the `getUserMemberships` function as inspiration, and that makes sense since it's a function used in the same file where we want the check for if someone is a superuser. 

One bit of context is that we usually don't make separate util functions until we know that what we are making a util function for is something that is needed in many places. I usually use the number 3 as a guide - the first and second time a bit of logic is needed, it's best to do it directly in its place even though it is a repetition, the third time is the bell rining to say "ok this is needed in enough places that we can make it a general purpose thing". Not always 3, but most commonly 3 is my personal guide for when it's time to make a general util, a general component, a general function etc. 

The other bit of info is that even though I totally understand that you copied the `getUserMemberships` function and found a way to modify it - well done on exploring and figuring it out!! - and even though your function technically works, we can make a much simpler solution that gets us what we need quicker. 

So, I propose that you delete this function file and look at my comment on the other file insted :)

File: src/pages/organize/[orgId]/people/lists/[viewId]/index.tsx [hunk 2]
```diff
@@ -37,7 +38,13 @@ export const getServerSideProps: GetServerSideProps = scaffold(async (ctx) => {
     // Check if user is an official
     // TODO: Consider moving this to some more general-purpose utility
     const officialMemberships = await getUserMemberships(ctx, false);
-    if (!officialMemberships.includes(parseInt(orgId as string))) {
+
+    const isSuperUser = await getSuperUser(ctx, false);
```
Comment (ziggabyte) [inline src/pages/organize/[orgId]/people/lists/[viewId]/index.tsx:42]: Insted of making a full function call here, the `ctx` (aka "context") actually has everything we need already. (that's not obvious to know when you're new, so how did i know that? i used the search function in vs code and searched for `is_superuser`, to see how and where that property was used elsewehere to check if someone is a superuser). 

So the `ctx` object has a `user` property on it, that is either a `ZetkinUser` or null. The `ZetkinUser` object has the `is_superuser` property, which is either `true`, `false` or `undefined`.

This means that `const isSuperUser = !!ctx.user?.is_superuser` will give us a boolean that says if whoever is trying to access this page is a superuser or not. To break it down: 
- `!!` is typescript for "make the thing to the right of me into a boolean"
- `ctx.user?.is_superuser` here we need the `?` after `user` since `user` can be `undefined`, and ofcourse `undefined` does not have a property called `is_superuser`. So you put a `?` to say "if the thing to the left of me is `undefined` or `null`, stop here" (read more [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) if you want)

File: src/pages/organize/[orgId]/people/lists/[viewId]/index.tsx [hunk 3]
```diff
@@ -37,7 +38,13 @@ export const getServerSideProps: GetServerSideProps = scaffold(async (ctx) => {
...
+
+    if (
+      !officialMemberships.includes(parseInt(orgId as string)) &&
+      !isSuperUser
+    ) {
```
Comment (ziggabyte) [inline src/pages/organize/[orgId]/people/lists/[viewId]/index.tsx:47]: I really like when conditions are named, it makes it so much easier to read the code. I suggest to both save `!officialMem....` in a named constant, and then save the "sum" of that constant and `isSuperUser` in a constant. That means something like: 
```
const isOfficialMember = officialMemeber....;
const isSuperUser = ctx....;
const notAllowedAccess = !isOfficialMember && !isSuperUser; 

if(notAllowedAccess) {....
```

**Review by ziggabyte — CHANGES_REQUESTED** [review]
Great job working on this! I'm gonna give some feedback on the code in comments below, and i know i'm commenting a lot, but please know that this is not because you did something bad or wrong - it's part of the process! This is how we learn :)  

One feedback related to git, that I think you might have already picked up on, is to be conscious about where you make your branch from. For most of the cases you will encounter as a code volunteer, `main` is where you want to branch off from. Git is really hard and takes a while to get into the fingers (took me months of patient explanations from @richardolsson to really grasp how branching works), so if you feel like you don't totally grasp what's up with git - we're very happy to share our knowledge!

The second learning point is that in the PR template here on gitHub, the final section `Related issues` is where you fill in the number of the gitHub issue that you are resolving with that PR. In gitHub PRs the phrase "Resolves #nnnn" is a magic phrase, that maks gitHub understand that when this PR is merged, issue number nnnn should be closed. So when you make a PR - make sure to fill in that line in the template! I filled it in for you now, so no stress about it, but it's a good bit of information to have on how gitHub works :)

**Comment by ziggabyte** [comment]
Since the comments have not been addressed I'm going ahead and making the suggested changes to the code so that we can get this merged :)

**Review by ziggabyte — APPROVED** [review]
I have made the suggested changes and approve of the result :)

**Comment by owenboy9** [comment]
thank you, Ziggi. sorry i've been mia.
o

owen kraus
pronouns: he/him // they/them
(what is this?
<https://www.glsen.org/sites/default/files/GLSEN%20Pronouns%20Resource.pdf>)
