### PR TITLE
ISSUE-1731/breadcrumbs-caching

### LINKED ISSUE #1731: Survey title in breadcrumbs displays the title of the first survey that was viewed
## Description
Survey title in breadcrumbs displays wrong title.
## Steps to reproduce
1. Go to http://localhost:3000/organize/2/projects/activities where you can see all activities.
2. Click on any survey
3. Go back to http://localhost:3000/organize/2/projects/activities
4. Click on another survey

### Expected Behaviour
The survey title in breadcrumbs displays the current survey title
### Actual Behaviour
The survey title in breadcrumbs displays only the title of first viewed survey

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by river-bbc**
## Description
This PR fixes an issue where breadcrumbs were not updating when clicking multiple surveys, only showing the first suvery in the breadcrumbs even when navigating to a new one. This had to do with the caching not updating the breadcrumbs for the route for 5 min, because changing the query parameters didn't make the cached item stale.

This does not fix the flashing issue which is fixed here: https://github.com/zetkin/app.zetkin.org/pull/1735/files#diff-11f03a79b05fa9c9284cbceb9b0418dce3aa12accc517783930d46dd70ffe527R38

## Changes

Changes the key used in the store for cached responses to use the `router.asPath` value instead of the `router.pathname` value. This includes ids in the path and is unique per each route.

## Notes to reviewer

* Go to surveys
* Click on a survey
* Click "back"
* Click on a different survey
* The breadcrumb should be correct

Also try:
* Changing the title of an editable title item and checking the breadcrumbs change when it saves

## Related issues
Resolves #1731

### CODE REVIEW

**Comment by richardolsson** [comment]
Oh I see! Thanks for investigating this bug. I think I was the one who wrote this code initially, and I didn't mean for the cache key to be `/path/with/[variables/in/it` but `/path/with/123/in/it`. I'm thinking that would make for an easier fix, if it's fairly easy to get the "hydrated" (real) path out of the router?

File: src/features/breadcrumbs/hooks/useBreadcrumbs.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ export default function useBreadcrumbElements() {
   const apiClient = useApiClient();
   const dispatch = useAppDispatch();
   const router = useRouter();
-  const path = router.pathname;
+  const { pathname, asPath: path } = router;
```
Comment (richardolsson) [inline src/features/breadcrumbs/hooks/useBreadcrumbs.ts:11]: So simple!

**Review by richardolsson — APPROVED** [review]
Beautiful! Nice work researching and fixing this.

I will squash and merge! 🦑
