### PR TITLE
edit url to go to correct destination

### LINKED ISSUE #167: "Organize" button links to wrong URL
When signed in as an official, the "Organize" button in the header is pointing to the wrong URL. This is because the Organize pages didn't exist in this app when the button was added, so it links to the old Organize app.

image

Steps to reproduce:

1. Navigate to localhost:3000
2. Click the "Log in" button
3. Log in using an account with organization official privileges, eg. username `testadmin@example.com`, password `password`
4. The header should contain a button labeled "Organize". Click it

Expected results: You should be redirected to http://localhost:3000/organize/1
Actual results: Redirected to https://organize.zetk.in

Important! The link should not be hard-coded to /organize/1. It should lead to an organization ID in which the user actually has organization official privileges. The user's memberships can be used to find the first organization in which it has enough privileges. Similar logic is already employed to decide whether to show the Organize button in the first place.

### PR DESCRIPTION
**Pull request by fannysoderlund**
//Me and Srilatha

Resolves #167

### CODE REVIEW

File: src/components/PublicHeader.tsx [hunk 1]
```diff
@@ -10,15 +10,17 @@ import {
...
 
 import apiUrl from '../utils/apiUrl';
-import { ZetkinOrganization, ZetkinUser } from '../types/zetkin';
+import { ZetkinMembership, ZetkinOrganization, ZetkinUser } from '../types/zetkin';
 
 interface PublicHeaderProps {
     user: ZetkinUser | null;
     org?: ZetkinOrganization | null;
     canOrganize?: boolean;
+    officials: ZetkinMembership[];
```
Comment (richardolsson) [inline src/components/PublicHeader.tsx:19]: The public interface (i.e. the props) that this component exposes to the wold should be as simple for component users (programmers) to understand as possible, and difficult to misunderstand.

In my opinion, there are two flaws with the way it currently looks.

## 1. The name and content of `officials`
The name of the new property `officials` implies that what should be passed is a list of organization officials, which could mean a list of several people who are all officials in an organization (or several). What's actually being passed is a list of memberships belonging to a single user. I think the name used for the variable in `DefaultLayout` is more clear, and should be used as a name for the property as well, i.e. `officialMemberships`.

Optionally, the property could be repurposed to pass in _all user memberships_, which would then be filtered inside the `PublicHeader` component (currently happens in `DefaultLayout`). With that solution, less would need to happen in `DefaultLayout` (which is difficult to test because it's [not pure](https://medium.com/technofunnel/working-with-react-pure-components-166ded26ae48)) and more could be done inside `PublicHeader`, which is easier to test (because it _is_ pure).

## 2. Derived data property
There are now two properties that both contain information about whether the user should see the _Organize_ button or not, `officials` and `canOrganize`. Actually, one is actually supposed to be calculated from the other, i.e. `canOrganize` depends on what the `officials` array contains, it is said to be _derived from_ `officials`, which is _base data_.

The issue is that both the _derived data_ and _base data_ needs to be calculated by the component that _uses_ `PublicHeader`. The `PublicHeader` component is basically telling anyone who wants to use it that it must provide two properties, one of which could be calculated from the other, but does not take responsibility of how that calculation should happen.

What happens if they contain conflicting information, or one is omitted? If the developer that uses `PublicHeader` somewhere forgets to include the `canOrganize` property (which is declared optional above) but passes in `officials`. Or if they set `canOrganize` to `true` but pass in an empty array of `officials`? At least with the way it's implemented right now, the latter case would result in an exception.

I would remove `canOrganize` now that we have `officials` (albeit renamed as suggested in 1 above).

File: src/components/PublicHeader.tsx [hunk 2]
```diff
@@ -10,15 +10,17 @@ import {
...
 }
 
-const PublicHeader = ({ canOrganize, user, org  } : PublicHeaderProps) : JSX.Element => {
+const PublicHeader = ({ canOrganize, user, org, officials: memberships  } : PublicHeaderProps) : JSX.Element => {
```
Comment (richardolsson) [inline src/components/PublicHeader.tsx:22]: The reassignment of `officials` to `memberships` here only strengthens my opinion from the previous comment that the property should be renamed to `officialMemberships` (if filtered outside) or `userMemberships` (if filtered within this component).

Avoid reassignment like this when possible. When reading the component after reading the interface, I was stumped to come across the `memberships variable` further down, until I realized it was reassigned from `officials` here. Having read the interface I knew there was no property called `memberships` and I didn't see one being declared, because it's not obvious from just glancing over a function signature containing object destructuring.

File: src/components/PublicHeader.tsx [hunk 3]
```diff
@@ -70,10 +72,12 @@ const PublicHeader = ({ canOrganize, user, org  } : PublicHeaderProps) : JSX.Ele
                         </View>
                         <>
                             { canOrganize && (
-                                <NextLink href="https://organize.zetk.in">
-                                    <Button data-testid="organize-button" variant="cta">
-                                        <Msg id="misc.publicHeader.organize"/>
-                                    </Button>
+                                <NextLink href={ `/organize/${memberships[0].organization.id}` }>
```
Comment (richardolsson) [inline src/components/PublicHeader.tsx:75]: This is risky. Although it's perfectly sane to expect that the `memberships` array is not empty with the way that `DefaultLayout` is using `PublicHeader`, it's not safe to assume that will always be the case for any component.

Add some validation further up the render function to make sure that the array is not empty. This makes even more sense if the calculation of `canOrganize` is moved inside this function as suggested in a previous comment.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Great work! Impressive how you were able to figure this out in such a short amount of time, including writing tests! 🚀 

I have added some comments below on how I think this should be refactored to be even better. In summary:

1. Rename the `officials` property `userMemberships`
2. Pass in the full list of memberships to `PublicHeader` and move the filtering from `DefaultLayout` to inside `PublicHeader`
3. Remove the `canOrganize` property from the public interface, it can be derived from the filtering inside `PublicHeader`
4. Avoid reassignment when using object destructuring in function component

I would also recommend that you set up the pre-commit hook for git as described in the README file. It will prevent you from accidentally committing anything that won't pass the linter. 😊
