### PR TITLE
Issue 2583/lock design pattern

### LINKED ISSUE #2583: Surveys: Content lock design pattern outdated
## Description
There's a new design pattern for activity editing lock. Surveys feature is using the old one.

### The feature

For when creating surveys and other types of questionaires in Zetkin, we need to make sure that organizers don't edit the meaning or context of questions mistakenly while people have started to submit replys to them meanwhile. We impede this by locking the content to make the organizer focus on this possible issue before editing.

### The bug

Having implemented the lock mechanism once more in for canvass assignments a better design has emerged. Now surveys' design need to be updated.

## Steps to reproduce

1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Create a project or pick an existing one at random
3. Create a Survey
4. Click CREATE QUESTIONS
5. Click OPEN QUESTION
6. Type anyhing as title
7. Click PUBLISH SURVEY
8. Click on the OVERVIEW tab
9. Click "Visit survey in activist portal" in the sidebar
10. Type anything as answer to the question
11. Chose the "Sign as…" option
12. Check the "I accept the terms stated below" checkbox
13. Click SUBMIT
14. Go back to the survey Questions tab
15. Refresh the page
16. Toggle between states by clicking UNLOCK / LOCK

### Actual Behaviour

Image 

Image

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR updates the design for the lock/unlock function in `Survey` to be aligned with the ` Canvass Assignment` feature and use the same design pattern for this functionality across the project.

## Screenshots
image
image

## Changes
* Changes `Locks `icons for `Switch` component.
* Adds `Divider`.
* Change `Thumbs `for `Check `and `Close `icons.
* Removes localized strings.

## Notes to reviewer
None

## Related issues
Resolves #2583

### CODE REVIEW

File: src/features/surveys/components/EditWarningCard.tsx [hunk 1]
```diff
@@ -68,14 +67,16 @@ const EditTips: FC<{
 }> = ({ bullets, header, icon }) => {
   return (
     <Box display="flex" gap={2} marginTop={1}>
-      <Box>{icon}</Box>
       <Box>
```
Comment (ziggabyte) [inline src/features/surveys/components/EditWarningCard.tsx:70]: This `Box` seems to be not neccessary!

File: src/features/surveys/components/EditWarningCard.tsx [hunk 2]
```diff
@@ -68,14 +67,16 @@ const EditTips: FC<{
...
-        <Typography fontWeight="bold">{header}</Typography>
-        <ul style={{ marginTop: 0, paddingLeft: 16 }}>
+        <Typography>{header}</Typography>
+        <Typography style={{ marginTop: 2 }}>
```
Comment (ziggabyte) [inline src/features/surveys/components/EditWarningCard.tsx:72]: I think you should change this Typography to be a Box instead, because it has children. A Typography/`p` should not have children that are Box/`div`

**Review by ziggabyte — CHANGES_REQUESTED** [review]
When looking at Survey and Area assignment side by side I notice this difference, not in how the locking logic behaves, but in how the page behaves - where the Survey has a breakpoint to become one column, the Area assignment report stays in one column 
bild

There are also differences in vertical space between the different parts of the component: above/below divider, between the "bullet points", above/below the headers for the red/green bullet points
bild

I think if you pull in main into this branch you can check and make sure the spacing is the same in both the components.

**Review by ziggabyte — CHANGES_REQUESTED** [review]
Looking at the preview build I notice that the two components still look a bit different from each other on the page, and also quite different from each other in the code, the space between the "bullet points": 
bild


Since it's two cards that we want to behave pretty much exactly the same, I'm thinking it makes sense to have the code be the same in both places - either by just literally having the same code duplicated in two places, or making a shared ZUI component. 

What do you think?

File: src/zui/ZUILockCard.tsx [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+  tips,
+  unlockedHeader,
+  unlockedSubheader,
+}) => {
+  const theme = useTheme();
+
+  const renderTips = (section: TipsSection) => {
+    const icon =
+      section.iconType === 'check' ? (
+        <Check style={{ color: theme.palette.success.main }} />
```
Comment (ziggabyte) [inline src/zui/ZUILockCard.tsx:40]: No need to change this, but I think you can just write "color='success'" here, just like you did with "color='error'" below?

**Review by ziggabyte — APPROVED** [review]
This is looking good :D 
great to finally get this into the codebase!!
