### PR TITLE
Inform the user if the shared list link they are using doesn't exist or is not shared

### LINKED ISSUE #2708: Lists: Trying to access shared view without permissions raises 500
### The feature
"Lists" is a feature in Zetkin which allows organizer users to create lists of people. These lists can then be shared with other people who do not have full admin access to the system, to delegate certain tasks such as outreach.

When a list is shared with someone, that someone can sign in using two-factor authentication (requires a Zetkin user account) to access the list, provided that they know the URL. In this role, they can make basic changes to the list (subject to configuration by the user who shared it).

### The bug
Signing in and accessing a list that has been shared with you works well, but if the list has not been shared with you in Zetkin (but you received the URL somehow) then instead of a useful error message you will currently get a 500 internal error.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Go to any list
3. Click the "Share" button in the top right
4. Copy the "restricted link" (without sharing with anyone)
5. Open an incognito window in your browser (or log out)
6. Navigate to the share-able restricted link
7. Log in as an unprivileged user, e.g. testuser@example.com (password `password`, SMS OTP `999999`)

### Expected Behaviour
There should be some sort of screen explaining to the user that they do not have access to this URL.

### Actual Behaviour
An internal server error (500) is thrown.

### Sharing settings
Image

### Trying to access as user without permission
Image

### PR DESCRIPTION
**Pull request by Herover**
## Description
This PR attempts to show the user a useful error message if they cant view a shared list.

Parts of the code violates the lint rule regarding rules of hooks (conditionally running hooks), but given that the access level cannot change without reloading the entire page, it should not become a problem. I'm not sure what the best way to fix this without ignoring rules is.

## Screenshots

image

## Changes
[Add a list of features added/changed, bugs fixed etc]

* Changes the view shared list page to detect disallowed access or access to non-existing list.

## Notes to reviewer

A list that exists but is not shared, ex. http://localhost:3000/organize/1/people/lists/199/shared without being logged in or logged in as a user that does not have access, and access a list that does not exist. Both should give the user a similar message.

## Related issues
Resolves #2708

### CODE REVIEW

File: src/pages/organize/[orgId]/people/lists/[viewId]/shared.tsx [hunk 1]
```diff
@@ -42,9 +45,16 @@ async function getAccessLevel(
...
-  );
+  let accessList: ZetkinObjectAccess[] = [];
+  try {
+    accessList = await apiClient.get<ZetkinObjectAccess[]>(
+      `/api/orgs/${orgId}/people/views/${viewId}/access`
+    );
+  } catch (e) {
+    if ((e as Error).message == 'Error during request: 403') {
+      return null;
+    }
```
Comment (ziggabyte) [inline src/pages/organize/[orgId]/people/lists/[viewId]/shared.tsx:56]: This try-catch is great! But I think that the `if` is not neccessary, because whatever error appears we want this function to return `null`

File: src/pages/organize/[orgId]/people/lists/[viewId]/shared.tsx [hunk 2]
```diff
@@ -57,7 +67,7 @@ export const getServerSideProps: GetServerSideProps = scaffold(async (ctx) => {
 
   // TODO: Handle this some other way with server-side models?
   const apiClient = new BackendApiClient(ctx.req.headers);
-  const accessLevel = await getAccessLevel(
+  let accessLevel = await getAccessLevel(
```
Comment (ziggabyte) [inline src/pages/organize/[orgId]/people/lists/[viewId]/shared.tsx:70]: I think, for a first step, we should begin with keeping this as a const, and then add a line below to do something like `if (accessLevel == null) { return notFound() }`. This would make it 404 for the user. Would you wanna try this approach?

**Review by ziggabyte — CHANGES_REQUESTED** [review]
I think this is a very creative solution to give the user a message, however I think it's enough at this stage to "just" return a 404 without more deeper context. We don't have anywhere else in Zetkin where we show more custom messages when someone is not allowed to view something, we just give them 404. 

I know that in the issue it says "a useful error message", but I think in this situation the 404 page is useful and simple enough and we can consider more specified messages in another work!

**Comment by Herover** [comment]
I agree :)

As we talked about, there seem to be another issue where a component tries to access a API so even if a user has access to the list, they still get a 403 error when viewing it.
