### PR TITLE
fix: Sort people import UI column values

### LINKED ISSUE #2499: Importer: Mapping values appear to user as arbitrarily sorted
## Description
The Zetkin web app has a UI for importing data about persons into Zetkin, where the user needs to "map" columns in a CSV or Excel file to destinations in Zetkin. It's possible to map data to, for example, Zetkin tags and organizations.

The UI for configuring this mapping lists the text values found in the file, and allows the user to pick what value should be interpreted as what tag/organization. But when the values are listed, they are listed in the order in which they appear in the file. To the user, this seems very arbitrary, and they should be ordered alphabetically instead.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Click on "Create"
3. Click on "Import people"
4. Drag and drop a CSV file with the content from the example file below
5. Configure the "TAG" column to map to tags
6. Note the order in which the values are listed in the UI
7. Cancel the import and refresh the page
8. Click on "Create" again
9. Click on "Import people" again
10. Change the sample file so that the two person rows are in the opposite order
11. Drag and drop the CSV file onto the importer
12. Configure the "TAG" column to map to tags
13. Note the order in which the values are listed in the UI

### Example file
```csv
FNAME,LNAME,TAG
Clara,Zetkin,x
Richard,Olsson,y
Last,Person,
```

### Expected Behaviour
The values should be listed in the same order in steps 6 and 13. I think they should be alphabetical, with empty values always at the top or at the bottom (whoever takes this issue on can decide).

### Actual Behaviour
The values are ordered differently in steps 6 and 13. In both cases, they are sorted in the order in which they appear in the file.

### Step 6 (x first)

Image

### Step 13 (y first)

Image

### PR DESCRIPTION
**Pull request by katjam**
## Description
This PR sorts the values displayed when mapping imported people fields

## Screenshots
csv:
```
ID,FIRST NAME,LAST NAME,CHAPTER,NETWORK
1,Clara,Zetkin,Malmo,Network 2
2,Jane,Doe,Leipzig,
3,Joe,Ham,Leipzig,Malmo
4,Clara,,Leipzig,Feminist network
5,Alex,Zander,Berlin,Malmo
```
sorted values:
image

## Changes

* Changes the order of imported column values to be alphabetical when mapping

## Notes to reviewer
Can be tested as per issue description in #2499

## Related issues
Resolves #2499

### CODE REVIEW

File: src/features/import/hooks/useUIDataColumn.ts [hunk 1]
```diff
@@ -30,7 +30,16 @@ export default function useUIDataColumn(
...
 
-  cellValues.forEach((value, idx) => {
+  let cellValuesSorted = [];
+  if (firstRowIsHeaders) {
+    const headerItem = cellValues[0];
+    const values = cellValues.slice(1);
+    cellValuesSorted = [headerItem, ...values.sort()];
+  } else {
+    cellValuesSorted = cellValues.sort();
+  }
```
Comment (richardolsson) [inline src/features/import/hooks/useUIDataColumn.ts:40]: At first I was a little bit uncomfortable making this change in `useUIDataColumn()`, instead of doing it in the UI component. But as I was investigating, I realized that the way this hook is designed the array needs to be sorted in here.

I think this is a flaw in the way this hook has been designed, and not a flaw in how you've chosen to solve this problem.

**Review by richardolsson — APPROVED** [review]
I reviewed the code and I tried the preview build and found that this is working as expected. I do think this PR exposes a flaw in the way hooks have been designed in the importer, but that's not a problem with this PR. Merging! 💯
