### PR TITLE
Minor layout fixes for org-switcher in side-bar

### LINKED ISSUE #1797: Nav: Org switcher chevron occluded when org title is long
## Description
When the title of an organization is long, the header of the nav menu becomes too wide and pushes the chevron out of the frame so that it can't (easily) be clicked.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1 and log in
2. Change the name of the organization using a `PATCH /api/orgs/1` with `{ "title": "Organization With A Long Name" }`
3. Open the left hand side nav menu

### Expected Behaviour
The header should show the title with ellipsis, e.g. "Organization With A L…" followed by a downward-facing chevron.

### Actual Behaviour
The header shows the full name, or as much of it as fits within the container, and the chevron is hidden outside of the container.

## Screenshots
Note how the chevron is just barely visible (a few pixels of it) to the right of the organization name.

image

### LINKED ISSUE #1799: Organization selector filter too large, doesn't align
## Description
The input field for filtering for organizations in the selector in the sidebar is of a large size. The consequence is that toggling this menu makes the content jump around unnecessarily much.

## Steps to reproduce
1. Click on the dropdown icon button by the organization name in the sidebar menu.
2. Watch the button moving down with the new content.

### Expected Behaviour
bild

An text input field height such as this would align the input field and button of the filter widget.

### Actual Behaviour
bild

### PR DESCRIPTION
**Pull request by ajoensson**
## Description
This PR fixes an issue where the org-switcher chevron could disappear for long organization names, as well as the size of the filter in the org-switcher. The chevron is now always visible by truncating the organization name with an ellipsis if they are too long.

## Screenshots
Before the fix:
Screenshot 2024-03-16 at 11 59 33

Fixed:
Screenshot 2024-03-16 at 11 59 55

and it still works the same for short organization names
Screenshot 2024-03-16 at 12 06 41

The chevron now aligns whether expanded or not, since the filter input has the correct size:
Screenshot 2024-03-16 at 12 23 57

## Changes

* Update CSS in organization sidebar to add overflow behaviour for long organization names.
* Change size of organization switcher filter to match with unexpanded switcher.

## Notes to reviewer
In order to test the longer org name, you can do as follows (quoted from #1797):
> Change the name of the organization using a `PATCH /api/orgs/1` with `{ "title": "Organization With A Long Name" }` 

## Related issues
Resolves #1797
Resolves #1799

### CODE REVIEW

File: src/zui/ZUIOrganizeSidebar/index.tsx [hunk 1]
```diff
@@ -220,6 +229,7 @@ const ZUIOrganizeSidebar = (): JSX.Element => {
                             }}
                             onChange={(e) => setSearchString(e.target.value)}
                             placeholder={messages.organizeSidebar.filter()}
+                            size="small"
```
Comment (richardolsson) [inline src/zui/ZUIOrganizeSidebar/index.tsx:232]: Great! This will please designer Josef. ✨

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! I'm seeing a small problem with this when the org name is long. When the title element grows, the margins around the avatar shrink. I see it very clearly in Chrome on the preview build (see screenshot below) but also in your screenshots, albeit less extreme.

image

Would you mind looking into this? Let me know if you want me to show and/or explain more thoroughly.

**Comment by ajoensson** [comment]
It should be fixed now! PTAL!

File: src/zui/ZUIOrganizeSidebar/index.tsx [hunk 2]
```diff
@@ -171,13 +171,15 @@ const ZUIOrganizeSidebar = (): JSX.Element => {
...
                           display: 'flex',
+                          overflow: 'hidden',
                         }}
                       >
                         {!showOrgSwitcher && (
                           <>
                             <Box
                               sx={{
                                 display: 'flex',
+                                flexShrink: 0,
```
Comment (richardolsson) [inline src/zui/ZUIOrganizeSidebar/index.tsx:182]: Simple fix! ❤️

**Review by richardolsson — APPROVED** [review]
Great! Lets get this merged!

**Comment by richardolsson** [comment]
Playwright is acting up this weekend. I have looked at the failing tests and they are notoriously flaky and unrelated to this fix, so I'm going to merge with 4/5 checks passing.
