### PR TITLE
Issue 2742  activist portal/events  filter out non published events for admins

### LINKED ISSUE #2742: Activist portal/Events: : Filter out non-published events for Admins
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When a user that has admin permissions navigate to their feed (http://localhost:3000/my/feed) they can see events that are in a non-published state AND/OR events that are inside a project that is non-published.

Those events should NOT be visible.

### The feature
Activist portal is where users can see and participate in their activities, for example sign-up for events, join a canvass assignment etc.

### The bug
Admin users shouldn't be allow to see non-published events (or events that are published inside a non-published project) because it can bring confusion if the event is not ready to be public.

## Steps to reproduce
1. Go to [http://localhost:3000/my/feed]
2. Click on 'All events'
3. Check that you are logged in as "Angela Davis" (is the predefined user)
4. The user can see a event called (Event in a non-published project) that belongs to a non-published project

### Expected Behaviour
This event should be hidden
### Actual Behaviour
Event is visible
## Screenshots

Image

**Provide at least one fullscreen screenshot (preferably including URL bar) for context**

### PR DESCRIPTION
**Pull request by Vaavii-Jakob**
## Description
This PR changes the filter for the Events that will be shown to the user, by comparing the date on which the Event is published to the current date.

## Screenshots
Before:
before
After:
after

## Changes

* Fixes the bug which resulted in showing unpublished events

## Related issues
Resolves #2742

### CODE REVIEW

**Review by ziggabyte — CHANGES_REQUESTED** [review]
Nice! 

When I played with the deployed version of this, I realise there is an extra layer of check that is needed - to see if the event belongs to a project/campaign, and if so, that the project/campaign is `published` and that the `visibility` property is `open`. 

If you create an event inside a hidden and/or unpublished project/campaign, and "publish" this event - it will now still be visible in the list for someone logged in with 2 factors as admin, but not for a regular user. 

So adding a check for if the event.campaign is published and has visibility "open"!

File: src/features/events/rpc/getAllEvents.ts [hunk 1]
```diff
@@ -94,8 +96,34 @@ async function handle(params: Params, apiClient: IApiClient): Promise<Result> {
...
-    return state == EventState.OPEN || state == EventState.SCHEDULED;
+  const filteredEvents = await Promise.all(
+    events.map(async (event) => {
+      let isEventPublished = false;
+      let isCampaignPublished = false;
+      if (event.published) {
+        const eventPublishDate = dayjs(event.published);
+        isEventPublished = eventPublishDate.valueOf() < dayjs().valueOf();
+      }
+      if (event.campaign) {
```
Comment (ziggabyte) [inline src/features/events/rpc/getAllEvents.ts]: Unfortunately this introduces a bug where events without a campaign will never be part of the list.. 

How about simplifying the logic a bit, to just have one boolean, something like this? 

```
let isPublished = false;

if (event.published) {
   isPublished = //event.publish is in the past
}

if (event..campaign) {
   //get campaign
   isPublished = //campaign is not archived, is published and is open
}

``` 

This way an event without a campaign will also be included in the list.

**Review by ziggabyte — APPROVED** [review]
I think this looks really nice now! :D 

Ready to merge!
