### PR TITLE
Issue 2446/area assignment status colour

### LINKED ISSUE #2446: Area assignment: status not shown correctly in activity list or activity overview
## Description
Area Assignments (which will be the new name for canvass assignments, changing in #2443) are one of six different types of "activities" in Zetkin (alongside events, call assignments, surveys, tasks and email).

Activities have lifecycles, which are slightly different depending on the activity. Area assignments can be drafts, or scheduled to be published at a future date, or published/started, or unpublished/ended.

The state is indicated in various places, but it seems like the different components are not consistent when it comes to how they render the state.

## Steps to reproduce
1. Create an area/canvass assignment
2. Give it a name 
3. Click "Start assignment"
4. Go to the activity overview (/organize/(orgId)/projects/(projectId) and see the assignment in the "today" section
5. Go to the "Activities" tab on the project, and see the assignment in the list
7. Now go back to the assignment 
8. Click "End assignment" 
9. Repeat step 4 and 5

### Expected Behaviour
At step 4 and 5, the status dot, tooltip and explanation are correct and all agree, wherever you look

### Actual Behaviour
At step 4 and 5, there is disagreement across the different components if the assignment is a draft, starting today, or closed.

## Screenshots (if you have any)
When the assignment has been opened and then closed again, this is what it looks like in the various places:

In the assignment
bild

In the activities list
bild

In the activity overview
bild

### PR DESCRIPTION
**Pull request by jaws82**
## Description

This PR adds the correct method for selecting the status colour for an area assignment in the project activity list.

## Screenshots

Screenshot From 2025-06-08 11-06-51
Screenshot From 2025-06-08 11-07-08

## Changes

* Adds the correct method for selecting the status colour (replacing hard coded grey value)

## Notes to reviewer

(none)

## Related issues

Resolves #2446

### CODE REVIEW

File: src/features/campaigns/components/ActivityList/items/AreaAssignmentListItem.tsx [hunk 1]
```diff
@@ -24,7 +27,7 @@ const AreaAssignmentListItem: FC<Props> = ({ caId, orgId }) => {
   }
 
   const areaAssignees = getAreaAssignees(sessions);
-  const color = STATUS_COLORS.GREY;
```
Comment (ziggabyte) [inline src/features/campaigns/components/ActivityList/items/AreaAssignmentListItem.tsx:27]: lol i love that we just hard coded this and forgot about it 😂

**Review by ziggabyte — APPROVED** [review]
This little status dot will eventually change when we switch to using the new design system, but in the meantime this is a very good and needed update to not just have it be grey all the time :) 

Good that it matches with the overview list now :)
