### PR TITLE
Sorting based on flagging status

### LINKED ISSUE #2474: Can't sort list based on OAN
## Description
When phone banking in Zetkin, it's possible to "flag" a call as in need of organizer action. We call this "Organizer action needed", or "OAN" for short. A person who's been flagged as OAN will be blocked from all calls until the flag is resolved. To facilitate the organizer action, there is a list for all the flagged people that is created automatically, with a column indicating their flagging status. The column can have different states – yellow (action needed), grey (action taken) or empty (because they may have been flagged in another part of the organization). But it's not currently possible to sort based on this value.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1
2. Find any call assignment
3. Under "Blocked", click "View list" next to "Organizer action needed", which will create the list if it doesn't exist already
4. In the list, mark one as resolved
5. Click the column to sort

### Expected Behaviour
The column should be sorted such that it's segmented into yellow, grey and empty.

### Actual Behaviour
Nothing happens when sorting.

## Screenshots (if you have any)
TBD

### PR DESCRIPTION
**Pull request by helihard**
## Description
This PR enables sorting based on flagging status (action needed, action taken, empty) in the 'Organizer action needed' table.

## Screenshots
asc
desc
none

## Changes
* Adds a sortComparator to the 'organizer action' column type. Rows are sorted based on flagging status:
Highest priority: there are flagged calls (organizer_action_needed), and at least one call has an unresolved issue (organizer action has not been taken)
Medium: there are flagged calls, and none of them has an unresolved issue
Lowest: empty/white

## Notes to reviewer
I am a bit confused regarding what would be considered 'asc' or 'desc' sorting in this case, but that could easily be altered in the code.

## Related issues
Resolves #2474

### CODE REVIEW

**Review by ziggabyte — DISMISSED** [review]
I am approving this, but also giving a suggestion for an improvement for making the code a bit more consise. You decide if you wanna make a new commit with this, or leave it :)

File: src/features/views/components/ViewDataTable/columnTypes/OrganizerActionColumnType.tsx [hunk 1]
```diff
@@ -27,6 +27,27 @@ import useToggleDebounce from 'utils/hooks/useToggleDebounce';
...
+  v1: ZetkinOrganizerAction[],
+  v2: ZetkinOrganizerAction[]
+): number => {
+  const hasActions = (v: ZetkinOrganizerAction[]): boolean => {
+    return v.length > 0;
+  };
+
+  const getSortValue = (v: ZetkinOrganizerAction[]): number => {
+    if (!hasActions(v)) {
+      return 2;
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/OrganizerActionColumnType.tsx:40]: Why return 2? Sorting comparator functions should return a negative number, zero, or a positive number to indicate the relationship between the compared values (`v1` and `v2` in this case).

The size of the returned value does not matter (except zero), only whether it's negative or positive.

Returning 1 in some execution branches and 2 in other branches makes me think that it matters somehow, but it shouldn't, so that makes me think that it's a mistake. In any case, it makes me think, which makes reading more difficult. 😊 

Would it make sense to change this?

```suggestion
      return 1;
```

**Comment by helihard** [comment]
I can see where I made the code unnecessary complicated and less readable. I have removed the named variable, since in the end I decided on it being unnecessary, it is clear enough without it what the code does. I have also removed my public display of affection for TS syntax.

@richardolsson: You are, to no surprise, right. What I wanted to achieve was to get the priority of each of the three cases (orange, gray and white), where those that do not have an array of organizer actions in the payload get the lowest priority, in this case 2. The helper (renamed for clarity) returns either 2, 1 or 0, while the sorter should return a positive, negative or 0 by comparing the priorities.

**Comment by richardolsson** [comment]
> @richardolsson: You are, to no surprise, right. What I wanted to achieve was to get the priority of each of the three cases (orange, gray and white), where those that do not have an array of organizer actions in the payload (whites) get the lowest priority, in this case 2. The helper (renamed for clarity) returns either 2, 1 or 0, while the sorter should return a positive, negative or 0 by comparing the priorities.

I actually think I was wrong, and you were right. I didn't realize when I read the code that this was an inner helper function that had a reason for returning 0, 1 or 2. I think your reasoning is good! 💯 

That said, I haven't had time to look at the recent changes. I think @ziggabyte will finish the review!

**Review by ziggabyte — APPROVED** [review]
We are ready for takeoff!!! 🚀 ⭐
