### PR TITLE
Fixes issue #1778

### LINKED ISSUE #1778: Importer: Unpublished sub-orgs visible when selecting organization to add people to
## Description
When mapping a value to an organization, the dropdown menu that contains the orgs to select from contains unpublished organisations. 

## Steps to reproduce
To actually see this in action you need to be in an organization with unpublished sub-organizations, but even if you're not these steps will take you to the correct drop-down. 
1. Go to `/people`
2. Start an import by selecting "import people" from the button in the top right corner
3. Select a file and load it
4. In the Configure stage, in the Mapping section, select to import any field as Organization
5. Click "Map values" to see the organization mapping interface to the right
6. Click "Map to..." on any of the rows 
7. Open the now-visible drop-down menu of organizations

### Expected Behaviour
The organisations in the drop-down are all active, published organisations

### Actual Behaviour
The list will contain un-published organisations as well as published ones

## Screenshots (if you have any)
bild

## Suggested solution
Filter the list of organisations on `org.active == true`

### PR DESCRIPTION
**Pull request by MattettaM**
Adds filtering of organisations based on isActive

## Description
This PR adds filtering of organisations based on isActive

## Screenshots
image

## Changes

* Adds filter to the organisations so inactive organisations are not added to the list

## Notes to reviewer
Follow repo steps 

## Related issues
Resolves #1778

### CODE REVIEW

File: src/features/import/components/ImportDialog/Configure/Configuration/OrgConfig.tsx [hunk 1]
```diff
@@ -16,9 +16,10 @@ interface OrgConfigProps {
 const OrgConfig: FC<OrgConfigProps> = ({ uiDataColumn }) => {
   const { orgId } = useNumericRouteParams();
   const messages = useMessages(messageIds);
-  const subOrgs = useSubOrganizations(orgId);
+  const subOrgs = useSubOrganizations(orgId).data || [];
+  const activeOrgs = subOrgs.filter((subOrg) => subOrg.is_active);
 
-  if (!subOrgs.data) {
+  if (!subOrgs) {
```
Comment (richardolsson) [inline src/features/import/components/ImportDialog/Configure/Configuration/OrgConfig.tsx:22]: For this to have the same effect as before, it needs to be changed to `if (!subOrgs.length)`. Before, `subOrgs` could be `null`, which is falsy. With your changes, it will instead be an empty array, and an empty array is truthy, so you need to check the length instead.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Great work! This will make organizer Adam very happy.

I've looked at the preview build and at the code. In my code review, I found a minor thing that changes behavior in undesired ways. I don't think the effects are very massive, but I thnk it's best to not introduces unnecessary changes in behavior. See comment below.

File: src/features/import/components/ImportDialog/Configure/Configuration/OrgConfig.tsx (hunk 1 above)
Comment (kaulfield23) [reply src/features/import/components/ImportDialog/Configure/Configuration/OrgConfig.tsx:22]: Thank you!! 😸

**Review by richardolsson — APPROVED** [review]
Great work! This is ready to merge now. 🙌

**Comment by richardolsson** [comment]
I have no idea why the tests are unusually flaky right now, but none of the failing playwright tests have anything to do with the code that is being touched by this PR, so I'm going to go ahead and merge anyway. Work is being done to reduce test flakiness.
