### PR TITLE
issue-1956/assigned-avatar-resets

### LINKED ISSUE #1956: List: Assigned avatar resets when double clicking the cell but does not update the cell
## Description
When I try to edit the assignee but decide not to update it, the avatar reset to default after clicking away.

## Steps to reproduce
1. Go to any list
2. Click on '+New column'
3. Click on 'Assigned Person' in 'Outreach' section
4. Set assignee to the cell
5. Double click the cell for edit mode
6. Don't set any new assignee. Just click outside of the popper

### Expected Behaviour
Assignee should be displayed in avatar
### Actual Behaviour
The avatar reset to default
## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/e83a138e-59d0-40b0-925a-29db7840dafb

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR fixes a bug where assigned avatar resets only in UI after editing the cell.

## Screenshots

https://github.com/zetkin/app.zetkin.org/assets/77925373/e77e5a4a-0e84-4ab9-a6f5-2358ab940f0c

## Changes

* Removes `valueGetter` that converts object to string
* Adds `sortComparator` for sorting assignee

## Related issues
Resolves #1956

### CODE REVIEW

**Comment by kaulfield23** [comment]
Found a bug! Will fix it today

File: src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx [hunk 1]
```diff
@@ -42,20 +41,19 @@ export default class LocalPersonColumnType
...
-        const cell = params.row[params.field];
-        return this.cellToString(cell);
+      sortComparator: (v1, v2) => {
+        if (!v1) {
+          return 1;
+        }
+        if (!v2) {
+          return -1;
+        }
+        return v1.first_name.localeCompare(v2.first_name);
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx:56]: This sorts based on first name, but what happens if two people have the same first name? Those people will end up in "random" order. I think you should also sort on last name. You can do that in one of two ways:

Option 1: Check the return value from `v1.first_name.localeCompare(v2.first_name)` and if it's zero, return the same but for last name instead, like so:

```tsx
return v1.first_name.localeCompare(v2.first_name) || v1.last_name.localeCompare(v2.last_name);
```

Or, you can create a full name variable and compare those instead:

```tsx
const name1 = `${v1.first_name} ${v1.last_name}`;
const name2 = `${v2.first_name} ${v2.last_name}`;
return name1.localeCompare(name2);
```

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! I have tried the preview build which is working well, and looked at the code which looks mostly good. But I don't think the sorting is working fully as intended? Check my comment below.

File: src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx (hunk 1 above)
Comment (kaulfield23) [reply src/features/views/components/ViewDataTable/columnTypes/LocalPersonColumnType.tsx:56]: Ah yeah I totally forgot about the last name! My bad!

**Review by richardolsson — APPROVED** [review]
Looking good now! Nice work. 💯
