### PR TITLE
sub_query Smart Search filter crashes if org has no smart searches yet.

### LINKED ISSUE #1690: Bug in `sub_query` Smart Search filter UI when there are no standalone filters
## Description
The `sub_query` Smart Search filter (currently labeled in the UI as "Based on another Smart Search query") allows user to select another smart search query and include it's result in the one they're editing, but when there are no "standalone" queries (which will be the normal case for organizations onboarded post Gen3, because standalone queries are not exposed anywhere in the UI) the UI crashes.

My guess is that this is because it tries to select the first query, but there are none.

## Steps to reproduce
1. Go to http://localhost:3000/organize/6/people (Org 6 has no standalone queries)
2. Create a new list
3. Configure a Smart Search for the list
4. Click "Add/remove people"
5. At the bottom of the list, click "Based on another Smart Search query"

### Expected Behaviour
Should open the UI to select which query, either one of many call assignments, or one of the "standalone" queries in that organization.

### Actual Behaviour
Crashes the UI.

## Screenshots (if you have any)
This happens on a production build. In your develompent build, you should be getting more information instead of just a black screen with an error message.

image

## Proposed solution
After loading standalone queries, if none exists, default to the first call assignment instead. If that also doesn't exist yet, present a message that says "there are no other Smart Searches in this organization yet", and disable "Save selection", only allowing user to cancel and go back. This is similar to the default state (before picking any options) in the filter labelled "Based on options they have selected in survey questions".

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR fixes a bug where the UI would crash when rendering the Smart search filter form for `sub_query`, by actually testing if there are queries to select from and if there are none, render a message instead. 

## Screenshots
bild

## Changes
- Switch out accidentally always truthy conditions with actual condition tests
- Render a message when there are no queries to select from.

## Related issues
Resolves #1690

### CODE REVIEW

File: src/features/smartSearch/components/filters/SubQuery/index.tsx [hunk 1]
```diff
@@ -127,143 +127,151 @@ const SubQuery = ({
...
-                onChange={(e) => setOp(e.target.value as OPERATION)}
-                value={filter.op}
-              >
-                {Object.values(OPERATION).map((o) => (
-                  <MenuItem key={o} value={o}>
-                    <Msg id={messageIds.operators[o]} />
+      renderSentence={() =>
+        queries.length == 0 ? (
+          <Msg id={messageIds.filters.subQuery.noSmartSearches} />
+        ) : (
```
Comment (richardolsson) [inline src/features/smartSearch/components/filters/SubQuery/index.tsx:133]: What happens when there are no standalone smart search queries (`queries`) but there _are_ call assignments?

**Review by richardolsson — COMMENTED** [review]
Just looking at the code, I'm not sure if this is working as I would expect. Does the logic care about call assignments?

File: src/features/smartSearch/components/filters/SubQuery/index.tsx (hunk 1 above)
Comment (ziggabyte) [reply src/features/smartSearch/components/filters/SubQuery/index.tsx:133]: This filter already takes callassignments into consideration, the `queries` variable here is an array made up of standalone queries, call assignment target queries, and call assignment "done" queries:
bild

Comment (richardolsson) [reply src/features/smartSearch/components/filters/SubQuery/index.tsx:133]: Ah, I went looking for it but clearly not thoroughly enough. Thanks for clarifying!

**Review by richardolsson — APPROVED** [review]
Thank you @ziggabyte for pointing out what I missed. I'm happy with this now that I understand it fully!
