### PR TITLE
Fix server error on 404 page. create custom 404 page and implement ge…

### LINKED ISSUE #105: Server error on 404 page
This error occurs on 404 pages. The best long-term solution is to [implement our own](https://nextjs.org/docs/advanced-features/custom-error-page) (internationalized) 404 page, and wrap it's `getStaticProps()` in `scaffold()` (or something equivalent to scaffold).

```
[0] Error: [@formatjs/intl Error INVALID_CONFIG] "locale" was not configured, using "en" as fallback. See https://formatjs.io/docs/react-intl/api#intlshape for more details 
[0] 
[0]     at new InvalidConfigError (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@formatjs/intl/src/error.js:37:23)
[0]     at Object.createIntl (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/@formatjs/intl/src/create-intl.js:37:21)
[0]     at Object.createIntl (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/react-intl/src/components/provider.js:63:27)
[0]     at new IntlProvider (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/react-intl/src/components/provider.js:83:27)
[0]     at processChild (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3305:14)
[0]     at resolve (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
[0]     at ReactDOMServerRenderer.render (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
[0]     at ReactDOMServerRenderer.read (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
[0]     at renderToString (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
[0]     at Object.renderPage (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/dist/next-server/server/render.js:54:851)
[0]     at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:141:19)
[0]     at loadGetInitialProps (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/dist/next-server/lib/utils.js:5:101)
[0]     at renderToHTML (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/dist/next-server/server/render.js:54:1142)
[0]     at async /Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/dist/next-server/server/next-server.js:109:97
[0]     at async /Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/dist/next-server/server/next-server.js:102:142
[0]     at async DevServer.renderToHTMLWithComponents (/Users/richardolsson/src/zetkin/product/app.zetkin.org/node_modules/next/dist/next-server/server/next-server.js:134:387) {
[0]   code: 'INVALID_CONFIG'
[0] }

```

### PR DESCRIPTION
**Pull request by nehahirve**
This PR implements a custom 404 page. Since only static prop fetching is available for the 404 page in Next, it hard codes 'en' as the language for messages. Fixes #105

### CODE REVIEW

File: src/pages/404.tsx [hunk 1]
```diff
@@ -0,0 +1,46 @@
+import { getMessages } from '../utils/locale';
+import { GetStaticProps } from 'next';
+import Head from 'next/head';
+import { FormattedMessage as Msg } from 'react-intl';
+import { Link as AdobeLink, Content, Flex, Heading } from '@adobe/react-spectrum';
```
Comment (richardolsson) [inline src/pages/404.tsx:5]: Is it necessary to import `Link as AdobeLink` here, or could it's default name be used?

In other places, where `Link` from Spectrum has collided with `Link` from NEXT, we have renamed the NEXT one instead. But here there doesn't seem to be a collision at all?

File: src/pages/404.tsx [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+
+const options = {
+    localeScope: [
+        'pages.404',
+        'misc.publicHeader',
+    ],
+};
```
Comment (richardolsson) [inline src/pages/404.tsx:12]: This structure was "designed" as a way of passing options to `scaffold()`. Since it's only hard-coded in this use case, we don't need the entire structure. The array is all we need, and since it's only used in one place (line 16) it could be inlined there.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Awesome! This looks great. 🥳 

I left a few minor comments below, and then I'd also like to see if we could create a test for this. See if you can fix the minor things now, and we'll take a look at the test later together!

**Comment by nehahirve** [comment]
Cypress test checks server endpoint and tests for 404 status, checks that custom 404 page content loads.

File: src/pages/404.tsx [hunk 3]
```diff
@@ -0,0 +1,42 @@
+import { getMessages } from '../utils/locale';
+import { GetStaticProps } from 'next';
+import Head from 'next/head';
+import { FormattedMessage as Msg } from 'react-intl';
+import { Content, Flex, Heading, Link } from '@adobe/react-spectrum';
```
Comment (richardolsson) [inline src/pages/404.tsx:5]: This is a minor thing, but we try to separate library imports from imports that are from the project codebase. Library imports come first, and then separated by an empty line comes local imports.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Awesome! 💎 

Only one minor little thing until it's perfect. I'm sorry I didn't catch this in my previous review. See comment below.

**Review by richardolsson — APPROVED** [review]
Great! We have arrived! 🎉 

Congratulations on completing your first Zetkin PR. 🎊 🥳 🍰
