### PR TITLE
Show full event start + end time on multi-day events in month calendar

### LINKED ISSUE #1878: Calendar: All (or at least many) events in calendar link to same event
## Description
Something seems to have happened on main causing many events in the calendar to link to the same event page.

## Steps to reproduce
1. Go to https://app-zetkin-id2fprog3-zetkin.vercel.app/organize/1/projects/calendar?campId=&focusDate=2024-04-05&timeScale=month (preview branch belonging to PR #1875)
2. Click on any event
3. Hover the "GO TO EVENT PAGE" link and observe the URL it leads to
4. Click on any other event
5. Hover the "GO TO EVENT PAGE" link of this other event and observe the URL
6. Try repeating steps 2-5 but clicking the links instead of hovering to verify link

### Expected Behaviour
The "GO TO EVENT PAGE" links should lead to different pages, since you are interacting with two different events.

### Actual Behaviour
Both links go to same page, which in my case is event with ID 21.

## Screenshots
Note that both links lead to the event with ID 21.

### One event
image

### Unrelated event
image

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR changes the EventPopper in the month calendar to display the full event's start and end times, when the event spans over multiple days. Before this, the time displayed showed as 00.00-00.00, since it technically spans over that whole day. This was, for obvious reasons, confusing. 

## Screenshots
bild

## Changes
* Adds the properties originalEndTime and originalStartTime to multi day events
* uses these properties where appropriate to display the correct time information

## Related issues
Resolves #1878

### CODE REVIEW

File: src/features/campaigns/types.ts [hunk 1]
```diff
@@ -32,8 +32,13 @@ export type TaskActivity = CampaignActivityBase & {
...
 };
 
+export type MultiDayEvent = ZetkinEvent & {
+  originalEndTime: string;
+  originalStartTime: string;
+};
+
 export type EventActivity = CampaignActivityBase & {
-  data: ZetkinEvent;
+  data: ZetkinEvent | MultiDayEvent;
```
[the remark this answers is not in the document]
Comment (ziggabyte) [reply src/features/campaigns/types.ts:41]: I think it's a good suggestion to maybe re-do it so that it is like you say, only in the function and the calendar.

File: src/features/events/components/EventWarningIcons.tsx [hunk 2]
```diff
@@ -73,8 +73,7 @@ const EventWarningIconsSansModel: FC<{
     if (!hasContact) {
       icons[0] = (
         <WarningSlot
-          key="contact"
-          icon={<FaceRetouchingOff color="error" />}
+          icon={<FaceRetouchingOff key="contact" color="error" />}
```
Comment (richardolsson) [inline src/features/events/components/EventWarningIcons.tsx:76]: What is the purpose of this change (and the others like it)? Will this not cause warnings because the `WarningSlot` elements now lack a `key`?

**Review by richardolsson — APPROVED** [review]
I have looked at the code and tried the preview build, and I find that this is working as expected and the code looks fine.

I do have a question regarding one of the changes that you've made. But I'm approving the PR as is so that you can merge if you don't feel that my comment gives ground for any changes.

File: src/features/events/components/EventWarningIcons.tsx (hunk 2 above)
Comment (ziggabyte) [reply src/features/events/components/EventWarningIcons.tsx:76]: I did it in response to a console warning that elements were missing their `key` property, changing it to this made the key end up on the right element in the dom and the warning went away...
