### PR TITLE
issue-2152: Show in week if day is DST start or end

### LINKED ISSUE #2151: Calendar in WEEK mode shows 24 hours for every day
## Description

The days where DST begins and ends are displayed with 24 hours in the WEEK-mode of an organization calendar, even though they in local time have 23 or 25 hours.

An event in central Europe scheduled between 2 AM and 3 AM on such a date is very likely to be interpreted differently by different users. That hour either does not exist in local time, or occurs twice in local time.

* https://en.wikipedia.org/wiki/Day
* https://en.wikipedia.org/wiki/Summer_time_in_Europe

## Steps to reproduce
1. Go to `/organize`
2. Open an organization
3. Open CALENDAR
4. Switch to WEEK mode
5. Go to week 43, including the last Sunday in October --- 2024-10-27

### Expected Behaviour

* either a calendar omitting 12 AM -- 3 AM from every day
* or a calendar omitting 12 AM -- 3 AM for Sunday
* or a calendar with 25 hours for Sunday
* or a calendar displaying which time zone is used

### Actual Behaviour

A calendar with 24 hours per day is displayed and no time zones are indicated.

## Screenshots (if you have any)

image

### PR DESCRIPTION
**Pull request by Jrende**
## Description
This PR adds a label under day header in week view if daylight saving time starts of ends during that day. Should handle different locales.

## Screenshots
Screen Shot 2024-09-28 at 14 55 12

## Changes
* Adds DST detection and display to DayHeader

## Notes to reviewer
DST ends on 27/10 in Europe.

## Related issues
Resolves #2151

### CODE REVIEW

**Comment by richardolsson** [comment]
Wow! The only thing that makes me happier than @WULCAN reporting this weird edge case last week, is the fact that you @Jrende have already come up with a solution! 

I've looked at the code and I feel like you've solved the tech side of this, but I'm not so sure what we should do with the information in the UI. I think that having an indicator in the day header does make sense, but at the same time it does take up a lot of space for something that will only affect some users (whose events take place in the middle of the night).

So I think I'm going to ask @sefsh or @Bagera to look at this and try to figure something out. One idea I have is to put the label on the hour where the change takes place instead. I'm going to let the designers decide, but maybe @Jrende you can just assess how difficult that would be to do? Like, is it simple to figure out what hour of the night the DST switches?

File: src/features/calendar/components/CalendarWeekView/utils.ts [hunk 1]
```diff
@@ -30,3 +30,9 @@ export function scrollToEarliestEvent(
 
   weekElement.scrollTo({ behavior: 'smooth', top: heightInPixels });
 }
+
+export function getDSTOffset(date: Date): number {
+  const jan = new Date(date.getFullYear(), 0, 1).getTimezoneOffset();
+  const jul = new Date(date.getFullYear(), 6, 1).getTimezoneOffset();
+  return (date.getTimezoneOffset() - Math.max(jan, jul)) / 60;
```
Comment (WULCAN) [inline src/features/calendar/components/CalendarWeekView/utils.ts:37]: Wow, I did not know that "the timezone offset is the offset [...], at the time represented by the Date object".

I had guessed that `Date` would only consider the current offset of the host system. Now I'm getting curious if this behaviour has unexpected consequences elsewhere.

Comment (Jrende) [reply src/features/calendar/components/CalendarWeekView/utils.ts:37]: I wish JS had better date handling, especially time zones become very hacky. But this seems to work, provided daylight savings occurs sometime between January and June. Handling it manually would be a nightmare, so I'm glad this seems to work.

**Comment by Jrende** [comment]
After consulting with UX experts it now looks like this:
WintertimeDayView
WintertimeWeekView
WintertimeMonthView
A label will be visible for the day when the time changes. I had some trouble figuring out what to write in it, after talking with a native english speaker "DST starts/ends" wasn't very clear, so I changed it to Winter time/Summer time. Writing out "Daylight Savings Time" might be more clear, but it didn't fit in the UI

File: src/features/calendar/components/utils.ts [hunk 2]
```diff
@@ -278,3 +278,9 @@ export const getActivitiesByDay = (
 
   return dateHashmap;
 };
+
+export function getDSTOffset(date: Date): number {
+  const jan = new Date(date.getFullYear(), 0, 1).getTimezoneOffset();
+  const jul = new Date(date.getFullYear(), 6, 1).getTimezoneOffset();
+  return (date.getTimezoneOffset() - Math.max(jan, jul)) / 60;
+}
```
Comment (richardolsson) [inline src/features/calendar/components/utils.ts:286]: This is the type of function that would love some unit tests, I think. 😊

File: src/features/calendar/components/CalendarMonthView/Day.tsx [hunk 3]
```diff
@@ -23,6 +27,13 @@ const Day = ({
 }: DayProps) => {
   const isToday = dayjs(date).isSame(new Date(), 'day');
 
+  const dstOffset = useMemo(
+    () =>
+      getDSTOffset(dayjs(date).startOf('day').toDate()) -
+      getDSTOffset(dayjs(date).endOf('day').toDate()),
+    [date]
+  );
```
Comment (richardolsson) [inline src/features/calendar/components/CalendarMonthView/Day.tsx:35]: This pattern returns three times. Maybe it could be a utility function that returns a boolean, which would also take a way the need of comparing `dstOffset !== 0` and have the added benefit of better describing what it is. The `dstOffset` variable name is correct in that it describes what the numeric value constitutes, but it doesn't really help me understand why that's relevant (or why `zero` is a special value on line 71). Something like this would maybe be cool?

```suggestion
  const dstChangesToday = useMemo(
    () => isDstChangeDay(date),
    [date]
  );
```

**Review by richardolsson — APPROVED** [review]
Awesome work on this! 👏 

I've tried the preview build to verify that it works and what it looks like (slightly different than the PR screenshots after changes due to design review) and reviewed the code. I found some duplication in the code that could theoretically be fixed, and I had an idea of adding unit tests. But honestly I don't care very deeply about either of those, so I'm just going to approve and if you want to take on one or both of those things you can open a separate PR at some point. 😊

**Comment by WULCAN** [comment]
The new design looks good but I think it would still be very confusing if an event was scheduled before 4 AM in central Europe on 2024-10-27.

Winter time in central Europe is UTC+1 and labeling that whole day with 'Winter time' can be interpreted as all the calendar's times that day referring to winter time. 00:10 Winter time would be 23:10 UTC but at 23:10 UTC a local clock would say 01:10.
