### PR TITLE
Map marker overlap

### LINKED ISSUE #2445: Area assignments: location markers end up on top of what's in the center of the area
## Description
When I zoom in and out on the map in the "Map" tab of the organizer facing part of an area assignment, in some zoom levels the markers for locations end up on top of the thing shown in the center of the area. this looks weird, as the markers feels like the are part of the "map world" and the stuff shown in the center are "floating" on top of the "map world" (this is my very non-scientific way of describing it, i hope you understand my reasoning)

## Steps to reproduce
1. Create a canvass assignment/area assignment (depending on if the renaming has been merged yet heh)
2. Go to the "map" tab
3. Click on an area
4. Make sure there are some dots marking locations in the center of the area 
   (if there are not: 
   - assign Angela Davis to the area
   - Give the assignment a title
   - click "Start assignment" up in the right corner
   - in a new tab, go to "/my/home"
   - find the assignment in the list 
   - go into the assignment 
   - create some locations in the center of the area
   - go back to original tab)
5. In the info box that comes up, add an assignee to the area
6. See the little icon of the assignee appear in the center of the area
7. Now zoom in and out and look at the icon of the assignee

### Expected Behaviour
The icon of the assignee stays on top of the location markers at all levels of zoom

### Actual Behaviour
In some levels of zoom the location markers are rendered on top of the icon

## Screenshots (if you have any)
bild

### PR DESCRIPTION
**Pull request by k-nut**
## Description
This PR ensures that the markers in the center of the area in a map are positioned on top of the individual markers.

## Screenshots
|before|after|
|-|-|
| CleanShot 2025-02-02 at 09 02 11@2x|CleanShot 2025-02-02 at 09 01 15@2x|

## Changes
There are two commits:
* The first one extracts some duplicated code for ordering areas on the map (not strictly necessary for this PR)
* The second one adds the `zIndexOffset` property to the `DivIconMarker` and uses it on the markers for the center of the areas. 

The leaflet library automatically sets z indexes on all markers so that they display properly. It allows providing the zIndexOffset to explicitly place some markers on a higher level which is just what we want here.

## Related issues
Resolves #2445

### CODE REVIEW

File: src/features/areaAssignments/components/OrganizerMapRenderer.tsx [hunk 1]
```diff
@@ -308,24 +308,9 @@ const OrganizerMapRenderer: FC<OrganizerMapRendererProps> = ({
               return -1;
             } else {
               // When  none of the two areas are selected, sort them
-              // by size, so that big ones are underneith and the
+              // by size, so that big ones are underneath and the
```
Comment (djbusstop) [inline src/features/areaAssignments/components/OrganizerMapRenderer.tsx:311]: nice!

File: src/features/areaAssignments/components/OrganizerMapRenderer.tsx [hunk 2]
```diff
@@ -398,7 +383,11 @@ const OrganizerMapRenderer: FC<OrganizerMapRendererProps> = ({
             return (
               <>
                 {overlayStyle == 'households' && (
-                  <DivIconMarker iconAnchor={[0, 0]} position={mid}>
+                  <DivIconMarker
+                    iconAnchor={[0, 0]}
+                    position={mid}
+                    zIndexOffset={100}
```
Comment (djbusstop) [inline src/features/areaAssignments/components/OrganizerMapRenderer.tsx:389]: What do you think about setting this on all `DivIconMarker`, or exposing this prop but having a default value, so it's always higher than other layers but it can be overridden.

Comment (k-nut) [reply src/features/areaAssignments/components/OrganizerMapRenderer.tsx:389]: (we talked in person and decided against this). But we did make the props for `DivIconMarker` nicer.

File: src/features/events/components/LocationModal/DivIconMarker.tsx [hunk 3]
```diff
@@ -1,15 +1,23 @@
...
-  iconAnchor?: [number, number];
-  position: LatLngExpression;
-}> = ({ children, draggable, eventHandlers, iconAnchor, position }) => {
+export const DivIconMarker: FC<
+  {
+    iconAnchor?: [number, number];
+  } & Pick<
+    MarkerProps,
+    'children' | 'draggable' | 'eventHandlers' | 'position' | 'zIndexOffset'
+  >
```
Comment (djbusstop) [inline src/features/events/components/LocationModal/DivIconMarker.tsx:12]: Dit is aba geil

**Review by djbusstop — APPROVED** [review]
