### PR TITLE
Issue 1962/Resolves Unsent Notification filter error

### LINKED ISSUE #1962: Calendar: Filter 'Unsent notifications' in calendar filters wrong events
## Description
When I try to use the filter in the calendar and check 'Unsent notifications' to see events that need to notify participants, it filters the wrong events
## Steps to reproduce
1. Go to calendar
2. Click on 'Week'
3. Create these four events
    a. An event that has no participants (Notifications: 0/0).
    b. An event that has participants but no notifications sent (Notifications: 0/3).
    c. An event that has participants and all have received notifications (Notifications: 3/3).
    d. An event that has participants and some have received notifications (Notifications: 1/3).
4. Click on 'Filter'
5. Click on checkbox 'Unsent notifications'

### Expected Behaviour
The filter should return event b and d
### Actual Behaviour
The filter returns event b and c

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by MattettaM**
## Description
This PR fixes the Unsent Notification Filter bug which filtered away the wrong events from the calendar.
The filter previously displayed events that had matching amounts of notified participants to booked participants. It now sorts out events where the booked participants are greater than the amount of notified participants.

## Screenshots
image
image

## Changes

* Changes the Unsent Notifications filter to filter away events that have greater or equal amounts of reminded participants to booked participants.

## Notes to reviewer
Create events with different amount of notified to booked participants. I used 0/0, 0/3, 2/3 and 3/3 for my testing. Enable the Unsent Notifications filter. Only 0/3 and 2/3 should be visible.

## Related issues
Resolves #1962

### CODE REVIEW

File: src/features/events/hooks/useFilteredEventActivities.ts [hunk 1]
```diff
@@ -100,7 +100,7 @@ export default function useFilteredEventActivities(
         (filterState.selectedActions.includes(
           ACTION_FILTER_OPTIONS.UNSENT_NOTIFICATIONS
         ) &&
-          stats.numReminded != stats.numBooked)
+          stats.numReminded >= stats.numBooked)
```
Comment (kaulfield23) [inline src/features/events/hooks/useFilteredEventActivities.ts:103]: Nice catch! 👍

**Review by kaulfield23 — APPROVED** [review]
