### PR TITLE
Display error message when button in email still has its default text

### LINKED ISSUE #2444: Email: Show error message if button has default text
## Description
When I have added a button to my email content, the button contains some default text. 
In the code we check that this text has been changed, and if it has not been changed you are not allowed to send the email - to spare some embarassing buttons ending up in everyones inboxes. 
BUT! even though this neat check exists, we don't actually show an error message to the user. 

## Steps to reproduce
1. Create a new email
2. Add a target group and lock it
3. Go to the "compose" tab and add a subject line 
4. Add a button block inside the email editor
5. Don't change the text of the button, and don't add a URL
6. Look at the button block in the right-hand-side "content" tab 
7. See the little yellow warning triangle 
8. Add a valid URL

### Expected Behaviour
The warning triangle is still there, and a little message saying something like  "This button still has the default text!" 

### Actual Behaviour
The warning triangle is there, but no info about why

## Screenshots (if you have any)
bild

### PR DESCRIPTION
**Pull request by helihard**
## Description
This PR adds an error message to be displayed in case the user has not changed the default text of a button in an email draft.

## Screenshots
button-default-text-warning

## Changes
* Adds an error message. When the default text of the button has been changed, the name of the element ('Button') is displayed in the right-hand 'Content' column.

## Notes to reviewer
When playing around a bit, I found some possible areas for improvement.

* Both the previous code and my code does allow for the button text to consist only of whitespaces. 
* Neither version allows for the button text to consist of zero characters, but as a result of this PR, the error message reads 'This button still has the default text' also in the case of an empty (0 characters) button. 

I should be able to just add a second error message (along the lines of 'This button must have some text', 'This button cannot be empty), just let me know if I should file this as a new issue or simply build on the current issue and re-PR it.

## Related issues
Resolves #2444

### CODE REVIEW

File: src/features/emails/components/EmailEditor/EmailSettings/ButtonBlockListItem.tsx [hunk 1]
```diff
@@ -39,7 +39,11 @@ const ButtonBlockListItem: FC<ButtonBlockLIstItemProps> = ({
       hasErrors={hasErrors}
       readOnly={readOnly}
       selected={selected}
-      title={messages.editor.tools.button.title()}
+      title={
+        data.buttonText
+          ? messages.editor.tools.button.title()
+          : messages.editor.tools.button.settings.defaultButtonTextWarning()
```
Comment (richardolsson) [inline src/features/emails/components/EmailEditor/EmailSettings/ButtonBlockListItem.tsx:45]: I was thinking that maybe the error message could be moved out of the header? I mean the block is still a button even if it's invalid, so I think it might be a bit jarring to replace the title like this.

Compare this with how invalid links are handled in paragraph/text blocks. It's still a text block and titled as such ("Text"), but there's an additional warning underneath.

image

File: src/features/emails/l10n/messageIds.ts [hunk 2]
```diff
@@ -63,6 +63,7 @@ export default makeMessages('feat.emails', {
           noButtonText: m('Click to change this text!'),
         },
         settings: {
+          defaultButtonTextWarning: m('This button still has the default text'),
```
Comment (richardolsson) [inline src/features/emails/l10n/messageIds.ts:66]: Maybe we can change this to something that works regardless of what the error is? Something like "Make sure to add your text to the button" or something like that?

I trust you to come up with something reasonable. Just wanted to propose a bit of a shortcut here that might work. 😊

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! I have looked at the preview build and I have reviewed the code changes.

I was super happy to see this. I'm hoping to be able to make a release sometime next week, but there's not much to release, so this would be lovely to merge. 😊 

I did find two things that I think could be improved, one of which is related to the problem you raised in the PR:

> Neither version allows for the button text to consist of zero characters, but as a result of this PR, the error message reads 'This button still has the default text' also in the case of an empty (0 characters) button.

File: src/features/emails/components/EmailEditor/EmailSettings/ButtonBlockListItem.tsx (hunk 1 above)
Comment (helihard) [reply src/features/emails/components/EmailEditor/EmailSettings/ButtonBlockListItem.tsx:45]: Thank you! Of course that would be a more suitable way to handle it. I'll be back with an updated version shortly.

Comment (helihard) [reply src/features/emails/components/EmailEditor/EmailSettings/ButtonBlockListItem.tsx]: several-button-text-errors

It seems to be doing what I intended for it to do: displays error when the button has its default text, when the button has zero characters and when the button texts consists only of whitespaces.

File: src/features/emails/components/EmailEditor/EmailSettings/ButtonBlockListItem.tsx [hunk 3]
```diff
@@ -33,6 +33,9 @@ const ButtonBlockListItem: FC<ButtonBlockLIstItemProps> = ({
   }, 400);
 
   const error = inputValue.length > 0 && !formatUrl(inputValue);
+  const buttonTextError =
+    !data.buttonText?.replaceAll('&nbsp;', '').trim().length ||
```
Comment (richardolsson) [inline src/features/emails/components/EmailEditor/EmailSettings/ButtonBlockListItem.tsx:37]: Nice! 💯

**Review by richardolsson — APPROVED** [review]
Great work! This is much better IMO. I have tried the preview build and reviewed the code changes and I think this is ready to merge. 🎉
