### PR TITLE
display correct campaign manager avatar on single campaign page

### LINKED ISSUE #255: Campaign manager avatar
Show the avatar of the person who has been assigned as a campaign manager.

Steps to reproduce:

1. Navigate to /organize/1/campaigns/1
2. Click edit
3. Select a campaign manager
4. Save

Expected results: The "No campaign manager" should be replaced with the name of the manager _and the person icon should be their avatar_
Actual results: The "No campaign manager" is replaced with the name of the manager but the icon remains generic.

image

### PR DESCRIPTION
**Pull request by nehahirve**
resolves #255

### CODE REVIEW

File: src/pages/organize/[orgId]/campaigns/[campId]/index.tsx [hunk 1]
```diff
@@ -142,7 +142,9 @@ const CampaignSummaryPage: PageWithLayout<CampaignCalendarPageProps> = ({ orgId,
                 </Box>
                 <Box display="flex" flex={ 1 } p={ 1 }>
                     <Box p={ 1 }>
-                        <Avatar></Avatar>
+                        <Avatar
+                            { ...(campaign?.manager && { src: `/api/orgs/${orgId}/people/${campaign?.manager.id}/avatar` }) }>
```
Comment (richardolsson) [inline src/pages/organize/[orgId]/campaigns/[campId]/index.tsx:146]: I'm not a big fan of this way of adding conditional properties, but I'm open to being convinced. Would love to hear your thoughts and motivations @nehahirve. Also, what do you think @djbusstop and @niklasva82?

I think I would prefer one of the following ways instead.

## Conditional value only (inline)
```tsx
<Avatar src={ campaign?.manager?
  `/api/orgs/${orgId}/people/${campaign?.manager.id}/avatar` : undefined }
/>
```

## Conditional value only (declared separately)
```tsx
// Higher up
const avatarSrc = campaign?.manager?
  `/api/orgs/${orgId}/people/${campaign?.manager.id}/avatar` : undefined;

// TSX
<Avatar src={ avatarSrc }/>
```

## Conditional component
```tsx
{ campaign?.manager? (
  <Avatar src={ `/api/orgs/${orgId}/people/${campaign?.manager.id}/avatar` }/>
) : <Avatar /> }
```

Comment (nehahirve) [reply src/pages/organize/[orgId]/campaigns/[campId]/index.tsx:146]: There's no special advantage to doing it my way, I guess it's less readable, will change

Comment (richardolsson) [reply src/pages/organize/[orgId]/campaigns/[campId]/index.tsx:146]: Honestly, I would usually do something like this:

```tsx
// Higher up
let avatar = <Avatar />;
if (campaign?.manager) {
  avatar = <Avatar src={ `/api/orgs/${orgId}/people/${campaign?.manager.id}/avatar` }/>;
}

// TSX
{ avatar }
```

But that's because I started writing JSX before we as a coding community started to gravitate towards in-JSX ternaries and the `{ someBool && <SomeComponent/> }` construct. So maybe I'm just being conservative. 😊

**Review by richardolsson — APPROVED** [review]
LGTM! 🚀
