### PR TITLE
Issue 1662/refactor sorting

### LINKED ISSUE #1662: Tag columns and Survey answers columns can't be sorted
## Description
Tag columns and Survey answers columns can't be sorted. 

## Steps to reproduce
1. Go to 'views'
2. Click on the arrow to sort Tag column

### Expected Behaviour
To be sorted

### Actual Behaviour
can't be sorted

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR allows users to sort Person Tag Columns and Survey Response Columns, as requested from organizers.

## Screenshots

https://github.com/zetkin/app.zetkin.org/assets/36491300/f0a321d0-2415-43cd-b738-62b7850037ab

## Changes
* Adds a sorting function called `sortComparator` in `SurveyResponseColumnType`
* Refactors the `sortComparator` to check `title `property when value is null in v1 and v2.

## Notes to reviewer
None

## Related issues
Resolves #1662

### CODE REVIEW

File: src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType.tsx [hunk 1]
```diff
@@ -44,34 +44,52 @@ export default class PersonTagColumnType implements IColumnType {
...
+              } else {
+                return v1.value.localeCompare(v2.value);
+              }
+            } else if (
+              typeof v1.value === 'number' &&
+              typeof v2.value === 'number'
+            ) {
+              return v1.value - v2.value;
+            }
+          } else {
```
Comment (richardolsson) [inline src/features/views/components/ViewDataTable/columnTypes/PersonTagColumnType.tsx:70]: This logic is very complex. I would really love a unit test for logic of this complexity. Is that something we could achieve?

With proper testing, we could investigate ways to simplify the implementation, without risking breaking the logic (because the test would let us know).

**Review by richardolsson — COMMENTED** [review]
Great work figuring out this very complex logic. I think we should create a unit test for the sorting logic, and then potentially simplify it if possible.

**Review by richardolsson — APPROVED** [review]
Nice work on all of this! I think it's ready to merge now. 😊
