### PR TITLE
3382: fix location change update after location edit

### LINKED ISSUE #3382: Canvass: Changing name of location resets it's stats in cache
### The feature
Area assignments is a feature in Zetkin that can be used to assign a geographical area to an activist, e.g. for door knocking, leafletting or other canvassing activities.

The Canvasser UI is a interface for activists who have been assigned an area assignment, to display the area on a map, create or edit locations in that area (e.g. renaming them), and record visits.

Recorded visits accumulate stats on the locations, which are then displayed on the map as indications on the location pins.

### The bug
When the name of a location is changed, the accumulated stats are reset in the Redux store cache, so it looks on the map as if they were lost. Nothing has gone wrong on the backend, so refreshing the page restores the numbers, but this should not be necessary.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/my and sign in as `testadmin@example.com`
2. Find any area assignment (e.g. by filtering on "Canvass")
3. Go to the assignment
4. Pick an area
5. In the area, find a location with recorded visits (or create a location and record visits there)
6. Point the crosshairs at the location
7. Open the drawer
8. Click the pencil in the top right to edit
9. Change the name and save
10. Close the drawer again to look at the map

### Expected Behaviour
The name in the drawer should have changed, but nothing else should have happened to the pin on the map.

### Actual Behaviour
The name in the drawer has changed correctly, but the numbers have also been lost, causing the pin to render incorrectly

### Selecting the location (step 6)
Image

### Editing the location (step 9)
Image

### Actual behavior (step 10)
Note the redux dev tools, where the store has been updated without the stats.
Image

## Proposed solution
Locations in the API is a primitive that does not contain stats. When retrieved from an endpoint below an area assignment, the stats are accumulated and added to the payload. But updating a location (`PATCH`) takes place at an endpoint that is not below the assignment, so when the updated location comes back, it does not have the stats. It should not replace the location in the store, but rather be "merged" (using `{...oldLocation, ...updatedLocation}` or something like that).

### PR DESCRIPTION
**Pull request by joergreichert**
## Description
This PR resolves the household visit stats location marker not preserved problem. 

## Screenshots
image

## Changes
When applying the changed location name and description, the other attributes of the location are now kept now.

## Notes to reviewer
* create in organization 1 one canvass activity and household, add visits
* http://localhost:3000/canvass/96/areas/131?step=edit - change name and see afterwards that the marker not loosing the visits stats

## Related issues
Resolves #3382

### CODE REVIEW

**Review by richardolsson — DISMISSED** [review]
Nice work taking this on! It seems like the linter is complaining. But I'm also surprised the code even works. I've elaborated in a comment below.

File: src/features/areaAssignments/store.ts [hunk 1]
```diff
@@ -250,12 +250,17 @@ const areaAssignmentSlice = createSlice({
     },
     locationUpdated: (state, action: PayloadAction<ZetkinLocation>) => {
       const location = action.payload;
+      const updateStategy = (itemToUpdate: RemoteItem<ZetkinLocation>) =>
+        ({
+          ...itemToUpdate.data,
+          ...location,
+        } as ZetkinLocation);
```
Comment (ziggabyte) [inline src/features/areaAssignments/store.ts:257]: I don't think the typecast is neccessary here, Typescript understands that all the right properties will be present on the object even if `.data` is null :)

**Review by ziggabyte — APPROVED** [review]
I'm hopping in to finish up this review process since it has been a long time since it's been worked on. 

When I play with it works just as expected. I like that the solution is totally contained in the store logic, and that you started by making a function that adds this strategy for only this specific reducer. That way we can take a separate PR to look at how we want behaviour to be in other reducers, and if it makes sense to have this behaviour on everything, or if it should be decided on a per-reducer basis :) 

I'm approving!
