### PR TITLE
Adjust ParticipantsList for smaller screens.

### LINKED ISSUE #1343: Action column in Participants page gets messy in smaller screens
## Description
When we reduce the screen the buttons of the right column are getting messy and the attendance dropdown gets hidden.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/1/events/161/participants
2. Play with the width of the screen to see the column shrink

### Expected Behaviour
Display buttons and attendance dropdown clear

### Actual Behaviour
Overlaying of elements

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR adjusts the styling of the ParticipantsList to look neater on a narrow screen.

## Screenshots
bild

## Changes
* Adds `minWidth`  to name and action columns
* Changes the styling a little to utilise build in features of components like  the grid and `Select`

## Related issues
Resolves #1343

### CODE REVIEW

File: src/features/events/components/ParticipantListSection.tsx [hunk 1]
```diff
@@ -192,15 +188,15 @@ const ParticipantListSection: FC<ParticipantListSectionListProps> = ({
       flex: 1,
       headerName: messages.eventParticipantsList.columnPhone(),
       hideSortIcons: true,
-      renderCell: (params) => {
+      resizable: false,
+      sortable: false,
+      valueGetter: (params) => {
```
Comment (richardolsson) [inline src/features/events/components/ParticipantListSection.tsx:193]: Nice improvement! 💯

**Review by richardolsson — APPROVED** [review]
All good! The grid component is complicated, so maybe there's an even better solution, but this should be good enough™.
