### PR TITLE
Issue-1914/Incorrectly displaying "1 additional row" when showing the row number had been better

### LINKED ISSUE #1914: Incorrectly displaying "1 additional row" when showing the row number had been better
## Description
I want to see the errored row's number when number to "additional row" is only one in a warning message.
## Steps to reproduce
1. Go to 'http://localhost:3000/organize/1/people'
2. Click on 'Create' and then click on 'Import people'
3. Upload a file that contains more than 10 rows, 9 of which contain malformed email addresses
4. Map columns for first name, last name and email address
5. Click on 'Validate'

### Expected Behaviour
Display row's number at the end instead of '...and 1 additional row' For example, ...1,2,3,4,5,6,7,8 and 9
### Actual Behaviour
displaying '...and 1 additional row' intead of showing row's number. This is silly, because it takes more space than just showing the row number. The "…and N additional rows" should only begin happening when there are more than 1 extra row.

## Screenshots (if you have any)
image

_Originally posted by @richardolsson in https://github.com/zetkin/app.zetkin.org/pull/1904#discussion_r1566150771_

### PR DESCRIPTION
**Pull request by DemianVoksi**
## Description
This PR resolves the issue that appears in the error message when only one errored row appears as "1 additional row" instead of the row number.  

## Screenshots
import_people

## Changes
* Changes the conditions of the Error message to allow rows with a length of breakpoint + 1 to appear as .fewRows instead of .manyRows.

## Notes to reviewer
*Try adding another CSV file with 10 emails, as suggested in the original issue. 

## Related issues
Resolves #1914

### CODE REVIEW

File: src/features/import/components/ImportDialog/elements/ImportMessageList/ProblemRowsText.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { FC } from 'react';
 
-import messageIds from 'features/import/l10n/messageIds';
 import { Msg } from 'core/i18n';
+import messageIds from 'features/import/l10n/messageIds';
```
Comment (richardolsson) [inline src/features/import/components/ImportDialog/elements/ImportMessageList/ProblemRowsText.tsx:4]: I leave this comment not because this is something you need to change, but because you have expressed to me that you hope to learn and grow as a developer and I want to offer some knowledge based on my experience.

Here you've made a change to the code that is not relevant to the bug you wanted to fix. That can seem like a tiny thing (and it is) but it is unnecessary, and it tells me that maybe your git method can improve.

First, lets investigate the "why". Why is it valuable to not include irrelevant changes in a commit/PR? Well, a lot of times when bugs occur, especially if they are regressions (things that used to work stop working) the first step to try and find them is to do git "forensics". That usually means some combination of `git log <file>` (looking at the history of a file), `git blame <file>` (looking at who last touched the relevant lines, and why) and `git bisect` (finding the commit that broke the code).

Changing a line of code even though you don't have to makes this more difficult. It can add an unnecessary commit to `git log` and `git bisect`, and it obfuscates what was the last _relevant_ change on this line when doing `git blame`. Sometimes it's still the right thing to do (e.g. re-formatting or refactoring it for clarity) but in cases like these where there is no obvious benefit of making the change, it's probably better not to make the change.

Still, this can very easily happen because when you're working on some code, especially code you don't know, it's commonplace to experiment and change the code a lot before finally figuring out and deciding what is the right change to make. By that time, it's often impossible to keep in one's head exactly what changes have been made.

That's when tools come in handy! Here's how I use git to avoid committing things that are not relevant to the change I want to make.

* Before I make a commit, I always do `git diff` (and `git status`) to see what changes I have made.
* I very rarely `git add <file>` and _never_ `git add .` to stage all changes for commit. I use `git add -N <file>` to add new files (which adds them without staging them) and then `git add -p` to go through every chunk of code that has changed and decide individually whether to include them in my commit or not.
* Sometimes, after staging the code I think is relevant, if I don't feel 100% confident that the staged code is enough for the change to work, I will do `git stash --keep-index` which temporarily "hides" all unstaged changes and try my code again to make sure it still works. If it does, I will `git stash drop` to discard the stashed changes after my commit.
* If I feel confident that everything will work, I will commit my stashed changes and then do `git reset --hard` afterwards to delete all the uncommitted changes (can be dangerous).

I always recommend to people to never use anything other than `git add -p` to stage changes for commit. The VSCode git GUI has similar functionality where changes can be added separately. I don't use that, but that's simply out of habit.

File: src/features/import/components/ImportDialog/elements/ImportMessageList/ProblemRowsText.tsx [hunk 2]
```diff
@@ -18,7 +18,7 @@ const ProblemRowsText: FC<Props> = ({ breakpoint = 8, rows }) => {
         values={{ row: rows[0] }}
       />
     );
-  } else if (rows.length <= breakpoint) {
+  } else if (rows.length <= breakpoint || rows.length - breakpoint == 1) {
```
Comment (richardolsson) [inline src/features/import/components/ImportDialog/elements/ImportMessageList/ProblemRowsText.tsx:21]: Would this make sense instead? I find it slightly easier to read.

```suggestion
  } else if (rows.length <= (breakpoint + 1)) {
```

**Review by richardolsson — COMMENTED** [review]
Nice work! I think we're close to merging your first contribution to the Zetkin web app!

I've left two comments below. One is just some general knowledge sharing. The other is a suggested change that I would like to hear your thoughts about.

File: src/features/import/components/ImportDialog/elements/ImportMessageList/ProblemRowsText.tsx (hunk 1 above)
Comment (DemianVoksi) [reply src/features/import/components/ImportDialog/elements/ImportMessageList/ProblemRowsText.tsx:4]: Hej! Thanks for the comment! This has happened because I have the "editor.codeActionsOnSave": "source.sortImports" enabled in my global VS Code settings, and I have forgotten to turn it off for the workspace. I've done it in the aftermath so it won't happen again, but I'll follow your suggestions just to make sure something similar doesn't happen again. Thanks!

File: src/features/import/components/ImportDialog/elements/ImportMessageList/ProblemRowsText.tsx (hunk 2 above)
Comment (DemianVoksi) [reply src/features/import/components/ImportDialog/elements/ImportMessageList/ProblemRowsText.tsx:21]: Yes, I was actually debating whether to put one or the other but it seemed to me that the longer version shows the logic behind the change a bit clearer. But yes, the +1 version is more readable, I can change it to that.

**Comment by richardolsson** [comment]
@DemianVoksi: Did you make any further changes to this today?

**Comment by DemianVoksi** [comment]
> @DemianVoksi: Did you make any further changes to this today?

I have applied the change that you suggested, I just haven't commited it yet. I can do it as soon as I'm at a computer again.

**Review by richardolsson — APPROVED** [review]
I have retried the preview build, and reviewed the changes again. I think this is ready to merge. Nice work! 💯
