### PR TITLE
Retain order of organizations in OrgSwitcher during filtering

### LINKED ISSUE #1507: Recent organizations in organization switcher are swapped when filtering
## Description
The recent section of the organization switcher is sorted by most recently selected organization. When using the switcher's filter on organization tree, the order of the most recent changes. 

## Steps to reproduce
1. Open organization switcher
2. Type something in the filter that will match several of the most recent organizations

### Expected Behaviour
For the order of the items in the "Recent organizations (filtered)" that also matches the filter **to remain sorted by the original logic**.

### Actual Behaviour
Item order is changed

## Screenshots (if you have any)
bild
bild

### PR DESCRIPTION
**Pull request by ajoensson**
## Description
This PR makes sure the order of the organizations in `OrgSwitcher` does not change when a filter is applied. This affects both the recent orgs and all orgs.

## Screenshots
Before/bugged/fixed
Screenshot 2023-09-10 at 14 07 48Screenshot 2023-09-10 at 14 07 55Screenshot 2023-09-10 at 14 51 53

## Changes

* Changes `shouldSort` option from default value to `false` for Fuse.js-objects in `useOrgSwitcher`.

## Notes to reviewer
None

## Related issues
Resolves #1507

### CODE REVIEW

File: src/features/organizations/components/OrganizationSwitcher/useOrgSwitcher.ts [hunk 1]
```diff
@@ -61,7 +62,11 @@ function useOrgSwitcher(orgId: number, searchString: string) {
   }, [searchString]);
 
   const allOrgsFuse = useMemo(() => {
-    return new Fuse(flatOrgData, { keys: ['title'], threshold: 0.4 });
+    return new Fuse(flatOrgData, {
+      keys: ['title'],
+      shouldSort: false,
```
Comment (rebecarubio) [inline src/features/organizations/components/OrganizationSwitcher/useOrgSwitcher.ts:67]: Nice and clean solution 💯!

**Review by rebecarubio — APPROVED** [review]
@ajoensson great work fixing this bug! And I love this solution to make the fuzzy search not changing the sorting order. Everything looks good to me, so we will take it from here... Thanks a lot for contributing! 🚀
