### PR TITLE
fix bug so tabs reflect navigation state

### LINKED ISSUE #211: Tabs do not reflect navigation state
Steps to reproduce:

1. Navigate to http://localhost:3000/organize/1/campaigns/1
2. In the list of events, click "See all in calendar"

Expected results: As the user navigates to the calendar, the "Calendar" tab should become selected
Actual results: The "Summary" tab remains selected

### PR DESCRIPTION
**Pull request by nehahirve**
Resolves #211

### CODE REVIEW

**Review by djbusstop — APPROVED** [review]
Tested this out, it works as expected now! Well done :+1:

File: src/components/OrganizeCampaignTabs.tsx [hunk 1]
```diff
@@ -26,6 +26,8 @@ const OrganizeCampaignTabs: FunctionComponent<OrganizeCampaignTabsProps> = ({ ch
         onSelectTab(newValue);
     };
 
+    useEffect(() => setValue(currentTab), [currentTab]);
```
Comment (richardolsson) [inline src/components/OrganizeCampaignTabs.tsx:29]: Ah of course! Nice catch! 👏

**Review by richardolsson — APPROVED** [review]
LGTM! 💯
