### PR TITLE
Only add campId property to query if you are in a project.

### LINKED ISSUE #1416: Redundant `campId` query parameter automatically added in calendar URLs
## Description
When navigating the _global_ calendar (the one that includes all events, regardless of project/campaign), there is a redundant `campId` query parameter added to the URL.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/calendar

### Expected Behaviour
URL should be rewritten to include `focusDate` and `timeScale`.

### Actual Behaviour
URL is rewritten to include `campId`, `focusDate` and `timeScale`.

## Screenshots
image

## Possible solutions
I believe this is because of the logic that syncs the calendar's internal state with the URL, introduced (or rather, modified) by #1384. It adds the `campId` property which is necessary for project-specific calendars, e.g. http://localhost:3000/organize/1/projects/1/calendar, but there probably needs to be some condition to only add it to the object when there is a project/campaign.

### PR DESCRIPTION
**Pull request by ziggabyte**
## Description
This PR attempts to fix a small bug where `campId` was added to the url without needing to be, when you visited the calendar for all projects.

## Screenshots
bild

## Changes
* Adds condition to test if you are in a project, and if so adds `campId` property to the query

## Related issues
Resolves #1416

### CODE REVIEW

File: src/features/calendar/components/index.tsx [hunk 1]
```diff
@@ -70,7 +70,7 @@ const Calendar = () => {
       {
         pathname: undefined,
         query: {
-          campId: campId,
+          ...(campId && { campId: campId }),
```
Comment (richardolsson) [inline src/features/calendar/components/index.tsx:73]: This syntax is crazy (but effective). 😊

**Review by richardolsson — APPROVED** [review]
Nice work! I have reviewed the code and I have tried the preview build, comparing it with current `main` at app.dev.zetkin.org, and I have found this to solve the bug correctly.

File: src/features/calendar/components/index.tsx (hunk 1 above)
Comment (ziggabyte) [reply src/features/calendar/components/index.tsx:73]: If someone had shown to me like two years ago that I would write and understand this, I would have laughed in their face 😂
