### PR TITLE
Issue 281/nav bar design

### LINKED ISSUE #281: Nav bar design
Update the nav bar design to match mock-ups, with the following exceptions:

* Separate the top four (organization realted) and the bottom two (user related) items
* Don't include the add button / speed dial in nav bar
* Don't show labels

image

### PR DESCRIPTION
**Pull request by nehahirve**
Resolves #281

### CODE REVIEW

File: src/icons/ZetkinLogo.tsx [hunk 1]
```diff
@@ -0,0 +1,26 @@
+import SvgIcon from '@material-ui/core/SvgIcon';
+
+interface ZetkinLogoProps {
+    size?: number;
+    color?: 'inherit' | 'disabled' | 'action' | 'secondary' | 'primary' | 'error';
+}
+
+const ZetkinLogo = ({ size, color }: ZetkinLogoProps):JSX.Element => {
```
Comment (richardolsson) [inline src/icons/ZetkinLogo.tsx:8]: Nice one! ✨

**Review by richardolsson — APPROVED** [review]
Great work! Already looks really good. And I love the SVG icon solution. 👍

**Comment by nehahirve** [comment]
can you merge @richardolsson ?
