### PR TITLE
Remove broken link and dead code

### LINKED ISSUE #1782: Projects: "Set yourself as manager" link does nothing
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Steps to reproduce
1 Go to a project and select to "edit project" in the ellipsis menu up to the right
2 click on the text "Set yourself as manager"

### Expected Behaviour
To not even see this text, since we are not displaying the "manager" field. 

### Actual Behaviour
The text disappears and nothing happens 

## Screenshots (if you have any)
bild
bild

## Suggested solution
Hide this link

### PR DESCRIPTION
**Pull request by nAjk87**
## Description
This PR removes the dead link for settings yourself as manager and also removes dead code related to setting yourself as manager functionality.

## Screenshots
image

## Changes
* Removed non working link and dead code.

## Notes to reviewer
Try editing a project and the link for setting yourself as manager will be gone.

## Related issues
Resolves #1782

### CODE REVIEW

File: src/features/campaigns/components/CampaignDetailsForm.tsx [hunk 1]
```diff
@@ -93,39 +84,6 @@ const CampaignDetailsForm = ({
...
-                  id: userProfile.id,
-                  last_name: '',
-                } as ZetkinPerson);
-              }}
-              underline="hover"
-            >
-              <Msg id={messageIds.form.manager.selectSelf} />
-            </Link>
-          )}
-
```
Comment (richardolsson) [inline src/features/campaigns/components/CampaignDetailsForm.tsx:128]: I say _yes_ to removing dead code. Kill it with fire!

File: src/features/campaigns/components/CampaignDetailsForm.tsx [hunk 2]
```diff
@@ -93,39 +84,6 @@ const CampaignDetailsForm = ({
...
-                // so for simplicity we pass the entire name as first name.
-                setSelectedManager({
-                  first_name: userProfile.name,
-                  id: userProfile.id,
-                  last_name: '',
-                } as ZetkinPerson);
-              }}
-              underline="hover"
-            >
-              <Msg id={messageIds.form.manager.selectSelf} />
```
Comment (richardolsson) [inline src/features/campaigns/components/CampaignDetailsForm.tsx:125]: Maybe you can find and remove the messageId as well? Hint: Use your IDE to find the definition of `selectSelf`, or go look in the `messageIds.ts` module of this feature (`campaigns`).

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! In order to fully remove the dead code, I think we should also get rid of the now unused messageId for `selectSelf`.

Other than that, I find nothing wrong with this (although I haven't been able to test it yet because Vercel is taking some time to deploy the preview). Can you have a go at the messageIds in the meantime?

**Comment by richardolsson** [comment]
I've tried the preview build now and it seems to work fine. Great work @nAjk87. If you're able to make that minor change to remove the now unused internationalization "message IDs" I feel ready to merge after that.

There is some information about messageIds (and internationalization in general) in the CONTRIBUTING file: https://github.com/zetkin/app.zetkin.org/blob/main/CONTRIBUTING.md#4-handling-text-and-i18n

Let me know if you have any questions!

File: src/features/campaigns/components/CampaignDetailsForm.tsx (hunk 2 above)
Comment (nAjk87) [reply src/features/campaigns/components/CampaignDetailsForm.tsx:125]: Removed it from messageIds.ts.

I did not remove the strings for the different locale files because those are generated, right?

File: src/features/campaigns/components/CampaignDetailsForm.tsx [hunk 3]
```diff
@@ -22,16 +20,9 @@ const CampaignDetailsForm = ({
...
   const messages = useMessages(messageIds);
 
-  const membershipsFuture = useMemberships();
-  const activeMembership = membershipsFuture.data?.find(
-    (m) => m.organization.id == orgId
-  );
-  const userProfile = activeMembership?.profile;
-
-  const [selectedManager, setSelectedManager] = useState<ZetkinPerson | null>(
+  const [selectedManager] = useState<ZetkinPerson | null>(
```
Comment (richardolsson) [inline src/features/campaigns/components/CampaignDetailsForm.tsx:25]: I believe you can also delete this (and all uses of it). Do you agree?

File: src/features/campaigns/l10n/messageIds.ts [hunk 4]
```diff
@@ -96,7 +96,6 @@ export default makeMessages('feat.campaigns', {
     },
     manager: {
       label: m('Project manager'),
-      selectSelf: m('Set yourself as manager'),
```
Comment (richardolsson) [inline src/features/campaigns/l10n/messageIds.ts:99]: Thank you! I think it should be possible to delete the entire `manager` section, right? It doesn't seem like it's used anywhere.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Great work finding the relevant code. Your work killed even more code, that can now be removed. Are you ok to do that as well? Comments below. 👇

File: src/features/campaigns/components/CampaignDetailsForm.tsx (hunk 3 above)
Comment (nAjk87) [reply src/features/campaigns/components/CampaignDetailsForm.tsx:25]: Sure ill come around to it soon.

**Comment by richardolsson** [comment]
I'm going to go ahead and merge this as is. There is some dead code in the form of unused internationalized messages. But there are probably tons of unused messages in the codebase and we need a better way to find and remove them anyway, so that can be handled separately.

Nice work @nAjk87!

**Review by richardolsson — APPROVED** [review]
