### PR TITLE
Change message to represent activist instead of caller

### LINKED ISSUE #2611: Area assignments: Incorrect placeholder in instructions
### The feature
Zetkin has a new (beta) feature called "Area Assignments", which is similar to call assignments, but instead of being used to call people over the phone, it's used to visit people at their doors in a geographical area.

Area assignments have instructions, that the organizer can write to the canvasser.

### The bug
The placeholder in the instructions editor says "callers", which is probably a copy-paste mistake from call assignments. It should say "activists" instead.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1
2. Go to any area assignment
3. Go to the "instructions" tab

### Expected Behaviour
The placeholder text in the editor should say "Add instructions for the activists".

### Actual Behaviour
The placeholder says "Add instructions for your callers".

## Screenshots

Image

## Note: Feature flags
This feature is currently hidden behind a feature flag. You need to add the feature flag `FEAT_AREAS=*` in your environment variables, and also configure a mongodb database URL in the `MONGODB_URL` environment variable. It can be any instance of mongodb.

### PR DESCRIPTION
**Pull request by a-jaxell**
## Description
This PR change messages from 'Callers' to 'Activists' in the area assignment instruction editor

## Screenshots
activists

## Changes
- Changed 'caller' to 'activist'

## Notes to reviewer
1. Go to [app.dev.zetkin.org/organize/1](https://app.dev.zetkin.org/organize/1)
2. Go to any Area assignment
3. Go to Instruction tab
4. Placeholder text in editor should say 'activists' and not 'callers'

This feature is currently hidden behind a feature flag. You need to add the feature flag `FEAT_AREAS=*` in your environment variables, and also configure a mongodb database URL in the `MONGODB_URL` environment variable. It can be any instance of mongodb.

## Related issues
Resolves #2611

### CODE REVIEW

File: src/features/areaAssignments/l10n/messageIds.ts [hunk 1]
```diff
@@ -15,12 +15,12 @@ export default makeMessages('feat.areaAssignments', {
...
         'Do you want to delete all unsaved changes and go back to saved instructions?'
       ),
-      editorPlaceholder: m('Add instructions for your callers'),
+      editorPlaceholder: m('Add instructions for your activists'),
       revertLink: m('Revert to saved version?'),
       saveButton: m('Save'),
       savedMessage: m('Everything is up to date!'),
       savingButton: m('Saving...'),
-      title: m('Caller instructions'),
+      title: m('Activist instructions'),
```
Comment (ziggabyte) [inline src/features/areaAssignments/l10n/messageIds.ts:23]: There are two `title` keys, this one on line 23 and one on line 26. The only one that is being used is the one on line 26. So I think this message can be deleted.

**Review by ziggabyte — CHANGES_REQUESTED** [review]
Just noticed a teeny tiny thing! Fix it, then we're ready for merge!

File: src/features/areaAssignments/l10n/messageIds.ts (hunk 1 above)
Comment (a-jaxell) [reply src/features/areaAssignments/l10n/messageIds.ts]: Removed line 23 !

**Review by ziggabyte — APPROVED** [review]
Hell yeah! Let's do it!
