### PR TITLE
Issue 1464/fix avatar

### LINKED ISSUE #1464: User avatar not working in sidebar
## Description
The user avatar in the sidebar is not rendering correctly. It seems like it's trying to use a person avatar instead of a user avatar, by passing the user ID to the `ZUIAvatar` component's `personId` property.

## Steps to reproduce
1. Go to http://localhost:3000/organize/11
2. Sign in as testadmin@example.com
3. Check avatar at bottom of sidebar

### Expected Behaviour
Should render initials of testadmin user (currently "CW").

### Actual Behaviour
Renders a default MUI avatar.

## Screenshots (if you have any)
image

## Proposed solution
Change `ZUIAvatar` to support user avatars, here:
https://github.com/zetkin/app.zetkin.org/blob/d2d1517496f8d3e9c5049e61f6b59591d04d41e5/src/zui/ZUIOrganizeSidebar/index.tsx#L342

User avatars are at /api/users/ID/avatar

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR adds support for user avatars in the ZUIAvatar component and implements the support in the ZUIOrganizeSidebar to render the correct user avatar.

## Screenshots
image

## Changes
* Adds a new conditional prop `isUserAvatar` in the ZUIAvatar component to select the correct API to use
* Adds the prop with value true in the `ZUIAvatar ` inside `ZUIOrganizerSidebar ` to render the user avatar.

## Notes to reviewer
none

## Related issues
Resolves #1464

### CODE REVIEW

File: src/zui/ZUIOrganizeSidebar/index.tsx [hunk 1]
```diff
@@ -322,6 +322,7 @@ const ZUIOrganizeSidebar = (): JSX.Element => {
                     }}
                   >
                     <ZUIAvatar
+                      isUserAvatar={true}
```
Comment (ziggabyte) [inline src/zui/ZUIOrganizeSidebar/index.tsx:325]: Nice! :D

**Review by ziggabyte — APPROVED** [review]
Looks like a nice, simple solution to me! :D

File: src/zui/ZUIAvatar/index.tsx [hunk 2]
```diff
@@ -5,6 +5,7 @@ import { forwardRef } from 'react';
 interface ZUIAvatarProps {
   orgId: number;
   personId: number;
+  isUserAvatar?: boolean;
```
Comment (richardolsson) [inline src/zui/ZUIAvatar/index.tsx:8]: As mentioned elsewhere, I think this is problematic because it uses a boolean to not just _tweak_ functionality, but actually change the _role_ of the component. For a user avatar, the `orgId` and `personId` are irrelevant, but those properties are still here (and still used) which is a hint to me that this is not a good solution.

File: src/zui/ZUIAvatar/index.tsx [hunk 3]
```diff
@@ -14,12 +15,19 @@ const SIZES = {
...
+    ref
+  ) => {
     return (
       <Avatar
         ref={ref}
         {...restProps}
-        src={`/api/orgs/${orgId}/people/${personId}/avatar`}
+        src={
+          isUserAvatar
+            ? `/api/users/${personId}/avatar`
```
Comment (richardolsson) [inline src/zui/ZUIAvatar/index.tsx:28]: Note how `orgId` is not used here, and `personId` is used to indicate the _user ID_ even though it's called `personId`. That's telling me that this component is not a good fit for the use case of showing user avatars.

**Review by richardolsson — CHANGES_REQUESTED** [review]
I would like this to be refactored. My suggestion would be to have two different components, `ZUIPersonAvatar` and `ZUIUserAvatar` that have different interfaces, both which both use a common avatar component internally.

That common avatar component might be a new rendition of `ZUIAvatar` for the size functionality etc, or it could just be the MUI `Avatar`. But I think probably we want to keep the size functionality.

In summary:

* Rename `ZUIAvatar` to `ZUIPersonAvatar`
* Break out the rendering from `ZUIPersonAvatar` into a new `ZUIAvatar` that takes the URL as a property and just renders it
* Create a new `ZUIUserAvatar` that uses the new `ZUIAvatar`

After these changes, the responsibility will be shared as such:

* `ZUIAvatar` is responsible for rendering an avatar URL as a avatar in a consistent way
* `ZUIPersonAvatar` is responsible for assembling a URL (and delegates rendering to `ZUIAvatar`)
* `ZUIUserAvatar` is responsible for assembling a URL (and delegates rendering to `ZUIAvatar`)
* Create `ZUIPersonAvatar` (which replaces the old

**Review by richardolsson — APPROVED** [review]
I like how this came out. Nice work! 💯
