### PR TITLE
JoinForm gender field

### LINKED ISSUE #2365: Embedded Join Forms: Gender field can be invalid
## Description
Join forms are a way to create a small form where data can be submitted to create a new person object in Zetkin. The intent is for forms to be embedded on websites and the likes. The feature was originally implemented only as an API endpoint and building the forms would have to happen on the website side of things.

Recently, we added capabilities to the webapp for rendering a form so that it can be embedded on another website (PR #2155). This was very "MVP", and did not treat the various fields in any specialized ways. In the case of the gender field, this is a problem because the field should only allow the values `'f' | 'm' | 'o' | null`.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people/joinforms
2. Find a join form that includes the gender field or create a new one
3. In the join form list, click the ellipsis menu of the field that contains gender
4. Click "Copy embed URL"
5. Browse to the copied URL
6. In the rendered join form, type "blah" into the gender field
7. Submit the form

### Expected Behaviour
This should not be allowed, ideally prevented already in step 6.

### Actual Behaviour
The data is submitted without any validation.

## Screenshots (if you have any)
image

## Proposed solution
Render the `gender` field using a drop-down instead of a simple text input, with the four allowed values:

* `'f'` = "Female"
* `'m'` = "Male"
* `'o'` = "Other"
* `null` = "Unspecified"

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR modifies embeddable join forms so that the "gender" field is no longer a text input field, but a dropdown with only the allowed values as options.

## Screenshots
image

## Changes
* Changes the `gender` field to be rendered with a `<select>`
* Changes the `first_name` and `last_name` fields to be required

## Notes to reviewer
None

## Related issues
Resolves #2365

### CODE REVIEW

File: src/core/i18n/globalMessageIds.ts [hunk 1]
```diff
@@ -6,6 +6,12 @@ export default makeMessages('glob', {
     edit: m('Editing'),
     readonly: m('Read-only'),
   },
+  genderOptions: {
+    f: m('Male'),
+    m: m('Female'),
```
Comment (WULCAN) [inline src/core/i18n/globalMessageIds.ts:11]: Isn't `f` supposed to be Female and `m` supposed to be Male?

**Review by WULCAN — CHANGES_REQUESTED** [review]
This looks good to me, but I think there is a small mistake.

File: src/core/i18n/globalMessageIds.ts (hunk 1 above)
Comment (ziggabyte) [reply src/core/i18n/globalMessageIds.ts:11]: no it's the Zetkin Mandatory Genderfuck Policy in operation 😛

Comment (richardolsson) [reply src/core/i18n/globalMessageIds.ts:11]: Haha, thanks for noticing this. 💯

**Review by ziggabyte — APPROVED** [review]
APprove!! ✔️ ✅
