### PR TITLE
1443: Add a check statement to avoid calendar crash

### LINKED ISSUE #1443: Calendar crashes after deleting event
## Description
When navigating to the calendar after deleting event, an error is thrown. I believe it's because the event still exists in the `eventsByDate` part of the store, causing it to render, but failing because when it tries to retrieve data for the event it is no longer available (404).

## Steps to reproduce
I'm unsure. I can't reproduce it using either bulk ops or deleting form the ellipsis menu. Will investigate, but anyone can try.

## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/36491300/6e9d6a99-2759-4529-b187-c00c1528371e

image

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR adds a check statement of the `sortedEvents `array to avoid the calendar crashed after deleting an event.

## Screenshots
Before:

https://github.com/zetkin/app.zetkin.org/assets/36491300/b66f6d35-121f-4767-a1c9-846fcd6363de

After:

https://github.com/zetkin/app.zetkin.org/assets/36491300/f0a2c420-0f55-4741-af8f-7f72daf5fc9a

## Changes
* Adds an IF statement before reading properties from empty array in `getOffsetStartEnd`()

## Notes to reviewer
The deleting exception still there but that was not the reason for crashing

## Related issues
Resolves #1443

### CODE REVIEW

File: src/features/events/components/SelectionBar/getOffsetStartEnd.ts [hunk 1]
```diff
@@ -17,6 +17,10 @@ export default function getOffsetStartEnd(
     }
   });
 
+  if (sortedEvents.length === 0) {
```
Comment (richardolsson) [inline src/features/events/components/SelectionBar/getOffsetStartEnd.ts:20]: Nice catch! Again with that typescript issue.

**Review by richardolsson — APPROVED** [review]
Great work! This looks good to merge IMO, unless @ziggabyte (who wrote the code) sees any reason not to?

**Comment by ziggabyte** [comment]
> Great work! This looks good to merge IMO, unless @ziggabyte (who wrote the code) sees any reason not to?

I see no problem!
