### PR TITLE
links organize button to correct url

### LINKED ISSUE #186: Link organize button to current org or org select screen
Building on the work from #168, on org pages (e.g. /o/2) the Organize button should not just link to the first organization in which the user has an official role, but to either the currently displayed organization, or /organize if that's an organization in which the user has no role.

# On organization pages
All pages below the `/o/{org_id}` path belong to a specific organization, and clicking the Organize button while on those pages should link directly to organize that organization, if the user can access it.

## When user has official role in rendered org
Steps to reproduce:

1. Navigate to /login and login as testadmin@example.com
2. Navigate to /o/2 (org page of "My other organization")
3. Click the Organize button at the top of the screen

Expected results: Should navigate to /organize/2
Actual results: Navigates to /organize/1

## When user does not have official role in rendered org
Steps to reproduce:

1. Navigate to /login and login as testadmin@example.com
2. Navigate to /o/5 (in which user does not have an official role)
3. Click the Organize button at the top of the screen

Expected results: Should navigate to /organize (404, which is fine for now)
Actual results: Navigates to /organize/1

Note that the /organize path is not yet implemented and tracked by #137. It does not have to be created as a part solving of this issue.

# On all other pages
On all other pages, the "Organize" button should link to /organize, where the user can pick which organization to organize.

Steps to reproduce:

1. Navigate to /login and login as testadmin@example.com
2. Navigate to / (home page)
3. Click the Organize button

Expected results: Should navigate to /organize (wher user can pick organization)
Actual results: Navigates to /organize/1

### PR DESCRIPTION
**Pull request by fannysoderlund**
Resolves #186

### CODE REVIEW

**Comment by richardolsson** [comment]
@nehahirve would you like to review this?

File: src/components/PublicHeader.tsx [hunk 1]
```diff
@@ -23,6 +23,13 @@ const PublicHeader = ({ user, org, userMemberships } : PublicHeaderProps) : JSX.
         membership => membership.role) || [];
 
     const canOrganize = userMemberships.length > 0;
+    let currentOrg = '';
+
+    for (let i = 0 ; i < userMemberships.length ; i++) {
+        if (userMemberships[i].organization.id == org?.id && userMemberships[i].role == 'admin') {
+            currentOrg = org?.id.toString();
+        }
+    }
```
Comment (nehahirve) [inline src/components/PublicHeader.tsx:32]: Can this be expressed in a more concise way? 
We are already filtering the user memberships on line 22 to check if they are memberships in which the user has any kind of role (user doesn't need to be an admin to organize, just needs to have any role). So on line 29 it is redundant to check for an admin role again. 

One suggestion is to use an array method instead of a for loop, for less lines of code -- maybe something like 
`const currentOrg = userMemberships.find(membership => membership.organization.id == org.id)`

this will return the first membership that satisfies the testing condition, or undefined if nothing does.

and then assign a variable for the organize url that you can refer to when rendering -- 

`const organizeUrl = currentOrg? `/organize/${currentOrg.organization.id}` : `/organize``

There wouldn't be any need to convert the number to a string explicitly with .toString() inside the template literal

File: src/components/PublicHeader.tsx [hunk 2]
```diff
@@ -75,7 +82,7 @@ const PublicHeader = ({ user, org, userMemberships } : PublicHeaderProps) : JSX.
                         </View>
                         <>
                             { canOrganize && (
-                                <NextLink href={ `/organize/${userMemberships[0].organization.id}` }>
+                                <NextLink href={ `/organize/${currentOrg}` }>
```
Comment (nehahirve) [inline src/components/PublicHeader.tsx:85]: So here you would refer to ${organizeUrl} instead of ${currentOrg}, which is also a more precise description of the variable in question

File: src/components/PublicHeader.spec.tsx [hunk 3]
```diff
@@ -52,11 +52,33 @@ describe('PublicHeader', () => {
         cy.get('[data-testid="organize-button"]').should('not.exist');
     });
 
-    it('organize button leads to proper organization page', () => {
+    it('leads to organization page to pick organization', () => {
```
Comment (nehahirve) [inline src/components/PublicHeader.spec.tsx:55]: Very nice, test names should start with a verb, like the sentence It (aka the component or page) 'does something'

**Review by nehahirve — CHANGES_REQUESTED** [review]
This looks good! Just a minor comment.

**Review by nehahirve — APPROVED** [review]
looks good!

**Comment by nehahirve** [comment]
@richardolsson think you can merge this?

**Review by richardolsson — APPROVED** [review]
Great work @fannysoderlund, and thanks to @nehahirve for reviewing. 🙌
