### PR TITLE
Issue 2099/misleading info message

### LINKED ISSUE #2099: Duplicates: "No data will be lost" is misleading
## Description
When two or more person objects are merged to resolve a duplicate, all related objects (such as events, phone calls, journeys, tags etc) are transferred to the remaining person object, while all other person objects are deleted. This means that no _related (but separate)_ data will be lost.

However, if there are conflicting field values on the person records, e.g. two different email addresses or two different last names, the user must pick which one to keep, and the other one will be lost. This means that some data (field values) can be lost when merging duplicates.

There is a message in the dialog that can easily be interpreted as claiming that _no data_ will be lost, which is not true, as described above.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people/duplicates
2. Click on "Resolve" on any of the duplicates
3. Scroll the right hand half of the modal to the bottom to find the message

### Expected Behaviour
Message should indicate that related data will be transferred.

### Actual Behaviour
The message claims that no data will be lost, which indicates that field values are also kept.

> **No data will be lost**
> All activity history and tags from all people being merged will carry over and will be visible on the merged person.

## Screenshots (if you have any)
image

## Proposed solution
The text should be changed to not imply that _no data_ will be lost, perhaps by more explicitly pointing to related data. When making these changes, new message IDs should be introduced so that translations will be updated.

### PR DESCRIPTION
**Pull request by a-jaxell**
## Description
This PR changes the disclaimer in in the Modal when resolving duplicate persons.
A clear message to describe what happens with data and a bit more serious color to bring attention to the disclaimer.

Logic has been implemented to render the information when there is conflicting field values. I have used existing functionality in the `useFieldSettings` and added a boolean `hasConflictingValues` to its return object.

### No conflicts
noconflicts

### Conflicts
conflicts

## Changes

* Adds messageId `warningTitle` and `warningMessage`
* Removes obsolete `infoTitle` and `infoMessage`
* Changes Alert component prop to `severity='warning'`
* Add exported to `useFieldSettings` hook

## Notes to reviewer
~~Have been unable to recreate duplicates to test this on, PR is set to draft until I can.~~

If there are no duplicates present use the below codesnippet to mock duplicates in `useDuplicates.tsx`

This should present two cases of duplicate persons, one where there are two persons matching with identical personal data which should not trigger an warning about potential data loss. The other is a case with three people that should cause the the warning to render. 

```typescript
  const test: PotentialDuplicate[] = [
    {
      duplicates: [
        {
          alt_phone: '098-765-4321',
          is_user: true,
          zip_code: '54321',
          last_name: 'Smith',
          city: 'Another City',
          first_name: 'Jane',
          gender: 'f',
          street_address: '456 Another St',
          co_address: null,
          ext_id: null,
          email: 'jane.smith@example.com',
          country: 'Sample Country',
          id: 1,
          phone: '111-222-3333',
        },
        {
          alt_phone: '098-765-4321',
          is_user: true,
          zip_code: '54321',
          last_name: 'Smith',
          city: 'Another City',
          first_name: 'Jane',
          gender: 'f',
          street_address: '456 Another St',
          co_address: null,
          ext_id: null,
          email: 'jane.smith@example.com',
          country: 'Sample Country',
          id: 12,
          phone: '111-222-3333',
        },
      ],
      dismissed: null,
      id: 1,
      merged: null,
      organization: {
        id: 123,
        title: 'Sample Organization',
      },
      status: 'pending',
    },
    {
      duplicates: [
        {
          alt_phone: '123-456-7890',
          is_user: true,
          zip_code: '12345',
          last_name: 'Doe',
          city: 'Sample City',
          first_name: 'John',
          gender: 'm',
          street_address: '123 Main St',
          co_address: null,
          ext_id: null,
          email: 'john.doe@example.com',
          country: 'Sample Country',
          id: 1,
          phone: '098-765-4321',
        },
        {
          alt_phone: '098-765-4321',
          is_user: true,
          zip_code: '54321',
          last_name: 'Smith',
          city: 'Another City',
          first_name: 'Jane',
          gender: 'f',
          street_address: '456 Another St',
          co_address: null,
          ext_id: null,
          email: 'jane.smith@example.com',
          country: 'Sample Country',
          id: 2,
          phone: '111-222-3333',
        },
        {
          alt_phone: '555-555-5555',
          is_user: false,
          zip_code: '67890',
          last_name: 'Brown',
          city: 'Cityville',
          first_name: 'Charlie',
          gender: 'm',
          street_address: '789 Brown St',
          co_address: null,
          ext_id: null,
          email: 'charlie.brown@example.com',
          country: 'Sample Country',
          id: 3,
          phone: '666-666-6666',
        },
      ],
      dismissed: null,
      id: 1,
      merged: null,
      organization: {
        id: 123,
        title: 'Sample Organization',
      },
      status: 'pending',
    },
  ];

  return loadListIfNecessary(duplicatesList, dispatch, {
    actionOnLoad: () => potentialDuplicatesLoad(),
    actionOnSuccess: (duplicates) => potentialDuplicatesLoaded(duplicates),
    loader: () => Promise.resolve(test),
  });
```

## Related issues
Resolves #2099

### CODE REVIEW

**Comment by a-jaxell** [comment]
Have marked this as draft until I can test it.

**Comment by richardolsson** [comment]
You can mock a dummy duplicate by hardcoding some data in the `useDuplicates()` hook, instead of actually loading them from the API. That should be enough to be able to test UI changes like these.

Once you've done that, including a patch in a comment on the PR is a helpful way to also allow a reviewer to do the same thing, without you having to commit the dummy code (which should not be in git).

File: src/features/duplicates/l10n/messageIds.ts [hunk 1]
```diff
@@ -29,6 +29,10 @@ export default makeMessages('feat.duplicates', {
       phone: m('Phone'),
     },
     title: m('Merge duplicates'),
+    warningMessage: m(
+      'Related activity data will transfer to the merged person, but conflicting fields must be resolved. Any unmerged data will be lost.'
```
Comment (richardolsson) [inline src/features/duplicates/l10n/messageIds.ts:33]:
```suggestion
      'All data related to any of the person records will transfer to the merged person. This includes event participation, survey submissions, tags etc. But the values you discard in the fields above will be lost.'
```

File: src/features/duplicates/components/ConfigureModal.tsx [hunk 2]
```diff
@@ -96,9 +96,9 @@ const ConfigureModal: FC<ConfigureModalProps> = ({
             }}
           />
           <Box marginBottom={2} />
-          <Alert severity="info">
-            <AlertTitle>{messages.modal.infoTitle()}</AlertTitle>
```
Comment (richardolsson) [inline src/features/duplicates/components/ConfigureModal.tsx:100]: Please also delete the old (now obsolete) messages from the `messageIds.ts`.

File: src/features/duplicates/components/ConfigureModal.tsx [hunk 3]
```diff
@@ -96,9 +96,9 @@ const ConfigureModal: FC<ConfigureModalProps> = ({
...
-            {messages.modal.infoMessage()}
+          <Alert severity="warning">
```
Comment (richardolsson) [inline src/features/duplicates/components/ConfigureModal.tsx:99]: Maybe this warning should be hidden entirely when there are no conflicting values. In those cases, no data will be lost, and it can be confusing for the user that the message refers to "the values you discard" when there has been no UI in which any values could have been discarded.

Could you try implementing logic that only shows this alert when there have been conflicting values (presented in the UI as dropdowns) above?

**Review by richardolsson — CHANGES_REQUESTED** [review]
I've been looking at this and thinking about it over the past few days, and I worry a little about whether this new phrasing (especially the title) are unnecessarily alarming. And it got me thinking. Details below. 👇

File: src/features/duplicates/hooks/useFieldSettings.ts [hunk 4]
```diff
@@ -39,5 +39,13 @@ export default function useFieldSettings(duplicates: ZetkinPerson[]) {
     }
   });
 
-  return { fieldValues, initialOverrides };
+  function entryContainsOneValue(entry: Array<string | string[]>) {
+    return entry[1].length < 2;
+  }
```
Comment (richardolsson) [inline src/features/duplicates/hooks/useFieldSettings.ts:44]: I think the name of this function is misleading, because it doesn't really check if there's just one value – it checks if there are less than two (which could also mean zero).

File: src/features/duplicates/hooks/useFieldSettings.ts [hunk 5]
```diff
@@ -39,5 +39,13 @@ export default function useFieldSettings(duplicates: ZetkinPerson[]) {
...
+
+  const hasConflictingValues = !Object.entries(fieldValues).every(
+    entryContainsOneValue
+  );
```
Comment (richardolsson) [inline src/features/duplicates/hooks/useFieldSettings.ts:48]: There's some unnecessary negation going on here, making the code slightly more difficult to read for me than I think it needs to be. I would have "flipped it" around so that instead of making sure that _every_ entry has _one_ value, it would check whether _any_ value has _multiple_ (using `some`, and the opposite logic of `entryContainsOneValue()`).

But that's just a matter of taste! One thing that you've done here which is very good, is to give the variable a name that explains everything. By just reading the name, given that I trust the code (which I will be able to do if I'm reading this after this has been reviewed or merged) I can immediately understand that the purpose of the logic is do figure out whether _there are conflicting values_. That's a huge benefit of naming things nicely! 😊

**Review by richardolsson — APPROVED** [review]
Nice work on this! And thanks for being so accommodating with the changes.

I have tried the build locally to confirm that it works as expected, and I have reviewed the code. I left some mostly philosophical questions below, but I believe this is ready to merge as is. 🎉

File: src/features/duplicates/hooks/useFieldSettings.ts (hunk 5 above)
Comment (a-jaxell) [reply src/features/duplicates/hooks/useFieldSettings.ts:48]: Thanks for the feedback! My aim was to make it readable and understandable. 

I did rewrite it using `some` instead and can see the difference it makes. It can be easy to miss a single `!` when reading it for the first time.
