### PR TITLE
Invalidate map size on resize event

### LINKED ISSUE #2608: Geography: The map does not fill entire screen when menu is collapsed
### The feature
There are several full-page maps in the Zetkin interface, one of which is the "Geography" section. "Full-page" in this context means that the map covers the largest area of the UI, from the bottom and right edges of the browser window, to the header at the top and the main menu on the left. The main menu in the Zetkin organizer interface can either be expanded (wide) or collapsed (narrow).

### The bug
Arriving at a map page with the menu expanded, and then collapsing the menu, results in the map not filling the full container anymore.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Expand the left hand side menu
3. Navigate to the "Geography" section
4. Pan around

### Expected Behaviour
The map should continuously cover the entire surface enclosed by header at the top, menu on the left, and the browser edges at the bottom and right. As you pan around, map tiles will load which means that for short moments the map may be blank, but should then fill up with map tiles across the surface.

### Actual Behaviour
At certain panning positions, the map does not properly load tiles on one side. It seems as if the map "thinks" that it's still the smaller size that it was when it was initialized while the menu was expanded.

## Screenshots
Note the grey area on the right-hand side.

Image

### PR DESCRIPTION
**Pull request by Jrende**
## Description
This PR runs `invalidateSize();` on the geography map whenever it's containing element changes size, so fix an issue where the edge of the map screen would be grey when panning.

It will call invalidateResize multiple times (around 12 in my case) when you expand or contract the sidebar. I didn't notice it leading to performance issues (though I tested it using my stationary computer). Since the user probably won't expand/collapse the sidebar that often it should be fine. I tried to add a debounce which delayed calling the function until after the sidebar had stopped moving, but this created a noticeable jump in the map.

## Changes
* Adds a resize observer to GeographyMap which calls invalidateSize()

## Related issues
Resolves #2608

### CODE REVIEW

File: src/features/geography/components/GeographyMap/index.tsx [hunk 1]
```diff
@@ -138,7 +151,13 @@ const GeographyMap: FC<MapProps> = ({ areas }) => {
           width: '100%',
         }}
       >
-        <Box display="flex" justifyContent="space-between" px={2} py={1}>
+        <Box
+          ref={(ref) => (containerElm.current = ref as HTMLElement)}
```
Comment (richardolsson) [inline src/features/geography/components/GeographyMap/index.tsx:155]: Would it be possible to just do this?

```suggestion
          ref={containerElm}
```

File: src/features/geography/components/GeographyMap/index.tsx [hunk 2]
```diff
@@ -128,6 +129,18 @@ const GeographyMap: FC<MapProps> = ({ areas }) => {
     }
   };
 
+  useEffect(() => {
+    if (containerElm.current !== undefined) {
```
Comment (richardolsson) [inline src/features/geography/components/GeographyMap/index.tsx:133]: Is falsy enough?

```suggestion
    if (containerElm.current) {
```

**Review by richardolsson — APPROVED** [review]
Nice work! I've looked at the code and I've tried the preview build, which is working as expected. I left some comments on the code below, but none of them are blockers, so let's merge this! 💯
