### PR TITLE
Issue 3182/easier retake survey

### LINKED ISSUE #3182: Surveys: Should be easy to respond again
### The feature
Surveys is a feature in Zetkin by which organizers can create forms with questions that members and other contacts respond to. The feature can also be used to collect responses when talking to people in the streets.

Surveys can be collected in two ways. Either over the phone (via the caller interface) or using a public facing survey form page, which is also used when activists collect responses in the street. After submitting the standalone survey page, a confirmation message is presented.

### The bug
There should be a simple way to restart the process after submitting a survey response, to make it more efficient for in-the-street survey collection.

## Steps to reproduce

1. Go to https://app.dev.zetkin.org/o/1/surveys/1
2. Fill out the survey
3. Sign using any name and email (or anonymously)
4. Submit the survey

### Expected Behaviour
The survey should be submitted, and you should arrive to a page with a confirmation that the survey was submitted. On that page there should also be a button to fill out the survey again.

### Actual Behaviour
The survey is submitted, and you arrive to a page with a confirmation, but there is no button on that page to fill out the survey again.

## Screenshots

Image

### PR DESCRIPTION
**Pull request by Linuswidmer**
## Description
This PR adds the possibility to retake the survey after submitting it

## Screenshots
image

## Changes
* Adds button to ZUIAlert, that reloads page

## Related issues
Resolves #3182

### CODE REVIEW

File: src/features/surveys/pages/PublicSurveyPage.tsx [hunk 1]
```diff
@@ -237,6 +237,12 @@ const PublicSurveyPage: FC<PublicSurveyPageProps> = ({ survey, user }) => {
         )}
         {showSuccess && (
           <ZUIAlert
+            button={{
+              label: messages.surveyRetake.text(),
+              onClick: () => {
+                location.reload();
```
Comment (richardolsson) [inline src/features/surveys/pages/PublicSurveyPage.tsx]: Simple, I like it!

File: src/features/surveys/pages/PublicSurveyPage.tsx [hunk 2]
```diff
@@ -18,23 +18,23 @@ import {
...
 import {
   ZetkinSurveyExtended,
   ZetkinSurveyFormStatus,
   ZetkinSurveySignatureType,
   ZetkinUser,
 } from 'utils/types/zetkin';
+import ZUIAlert from 'zui/components/ZUIAlert';
+import ZUIButton from 'zui/components/ZUIButton';
+import ZUILink from 'zui/components/ZUILink';
+import ZUIPublicSurveyOption from 'zui/components/ZUIPublicSurveyOption';
```
Comment (richardolsson) [inline src/features/surveys/pages/PublicSurveyPage.tsx]: All of the changes to imports seem unnecessary to me. If you're not sure how they happened, please have a look in your editor in case it does some sort of automatic sorting of imports, or something like that, and disable it for future PRs. 😊
