### PR TITLE
Canvass: Add Undo button in visit stepper

### LINKED ISSUE #2548: Canvassing: Editability of visit reporting answers isn't apparent
### The feature
Zetkin features a new tool for organizing so-called canvassing (visiting households for talking and distributing material). Canvassers are provided with a dedicated interface in which they can view and interact with areas and locations visualized on a map. The canvasser may report visits to each household created within each location by providing answers to a small survey provided by the organizer creator of the area assignment.

### The bug
When reporting a visit and regretting an already selected survey answer, it is not apparent to the user that the answer can still be edited.

## Steps to reproduce

1. Go to https://app.dev.zetkin.org/organize/1
2. Make sure you're signed in as `testadmin@example.com`
3. Click on **🗺 Geography** in the side menu
4. Draw an area (currently by clicking the DRAW button and putting a few points on screen) 
5. Click SAVE button to save the area.
6. Create a project from the top-right button
7. Create an area assignment from the "CREATE" button, call it `Reporting test`
8. Click on maps tab in the newly created area assignment 
9. Use the map interface to locate and click on the area created in step 4
10. Type to find, and select the user `Angela Davis` in the **Add assignee dropdown**.
11. Click the top-right START ASSIGNMENT button
12. Go to https://app.dev.zetkin.org/my
13. Locate the **and tap** the `Reporting test` area assignment (possibly filed under "Canvass" category)
14. Tap START ASSIGNMENT
15. Use the + button until the map is maximally zoomed in
16. Tap ADD LOCATION, name it, tap CREATE LOCATION
17. Use the appearing drawer UI to open the location details by tapping the element or its ߍ button
18. Tap HOUSEHOLDS button
19. Tap + ADD NEW HOUSEHOLD button
20. Tap LOG VISIT button 
21. Reply to the survey question

### Expected Behaviour
It is apparent that answers can be edited. 

### Actual Behaviour
It is not apparent answers can be edited. 

## Screenshots

Image

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR adds and Undo button to show the user that they can edit their responses. It also adds some small style fixes in the stepper.

## Screenshots
image

## Changes
* Adds `Undo` icon
* Adds logic to reset future responses when navigating to a previous step
* Aligns stepper icon to be always inline with the first line of text

## Notes to reviewer
None

## Related issues
Resolves #2548

### CODE REVIEW

File: src/features/canvass/components/LocationDialog/pages/HouseholdVisitPage.tsx [hunk 1]
```diff
@@ -105,28 +106,56 @@ const HouseholdVisitPage: FC<HouseholdVisitPageProps> = ({
...
+                    <Typography
+                      sx={{
+                        overflow: 'hidden',
+                        textOverflow: 'ellipsis',
+                        whiteSpace: stepIsCurrent ? 'normal' : 'nowrap',
+                      }}
+                    >
+                      {metric.question}
+                    </Typography>
+                    {!stepIsCurrent && completed && <Undo />}
```
Comment (richardolsson) [inline src/features/canvass/components/LocationDialog/pages/HouseholdVisitPage.tsx:150]: I don't think `completed` is the right condition here, because it means that there is no "Undo" button on skipped questions (which are not considered completed). Maybe use the index instead, i.e. whether `index < step`?
