### PR TITLE
Fix broken tag select in Smart Search dialog

### LINKED ISSUE #856: Polish the interface post-MUI 5 migration
Some visual improvements to follow up the migration to MUI 5

- [ ] Tab spacing on pages has shrunk
- [ ] Campaign cards are weirdly spaced
- [ ] Campaign cards cta button has no space around it
- [ ] The "previous/next" buttons at top of calendar is out of place
- [ ] Things that were black but have now become red: Search magnifying glass, Hide page header button, ellipsis menu, clock on journey instance header, 
- [ ] Timeline notes about milestones have wonky placement in them
- [ ] The top left zetkin logo is blue on Journey instance page (but not elsewhere, to my knowledge)
- [ ] Tag smart search filter has stopped working (tags render incorrectly and can't be clicked)

_Originally posted by @ziggabyte in https://github.com/zetkin/app.zetkin.org/pull/854#pullrequestreview-1213563395_

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR fixes a bug that was discovered after the MUI migration.

### Before
image

### After
image

## Changes
* Adapts to the new workings of MUIv5 `Autocomplete`
* Uses boxes to render chips

## Notes to reviewer
Please do not review until #855 has been merged.

To reproduce the issue on main:

1. Navigate to any Smart Search dialog
2. Go to configure a selection by tag
3. Note how tags are rendered empty and can't be clicked

## Related issues
Related to, but does not fully resolve #856

### CODE REVIEW

File: src/features/smartSearch/components/inputs/StyledItemSelect.tsx [hunk 1]
```diff
@@ -51,20 +51,28 @@ const StyledItemSelect = (props: StyledItemSelectProps): JSX.Element => {
...
+            ) : (
+              <Tooltip key={item.id} title={item.title}>
+                <Chip
+                  color="primary"
+                  label={shortenedLabel}
+                  variant="outlined"
+                />
+              </Tooltip>
+            )}
+          </Box>
```
Comment (ziggabyte) [inline src/features/smartSearch/components/inputs/StyledItemSelect.tsx:75]: Box solves all problems 👼

**Review by ziggabyte — APPROVED** [review]
good for finding and solving this! :D
