### PR TITLE
Render Settings page/menu option if organization has Officials flag

### LINKED ISSUE #2911: Settings: Feature flag the "Officials" section
### The feature
The "Settings" part of the Zetkin webapp currently only contains a single feature, and that's a UI to add/remove "officials", which is the term we use to refer to "admins" and "organizers", the two roles in Zetkin with elevated privileges.

Within in a (sub-) organization, any official can add another official. This is sometimes not what an organization wants, and this will be solved by a more granular permissions system that is taking shape on the backend.

### The bug
In the meantime, it would have been good if the "Settings" section was entirely hidden for those organizations where it should not be so easy to add new admins. This is not a security feature, just a way of decreasing the manual workload for those who are currently monitoring role assignment.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize
2. Pick any organization
3. Click the "Settings" item in the menu

### Expected Behaviour
The navbar on the left should contain: Search, People, Projects, Journeys, Tags, Geography. The final "Settings" option should only be visible for organizations with the `FEAT_OFFICIALS` feature flag.

Trying to directly access https://app.dev.zetkin.org/organize/1/settings should only work with `FEAT_OFFICIALS` set. Otherwise it should give a 404.

### Actual Behaviour
The navbar on the left contains "Settings", and clicking it takes you to the Officials settings, regardless of the feature flag.

## Screenshots
None

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR adds the Officials flag feature to only show the Settings page (and option in the menu) to organizations that have the flag active. 

## Screenshots
image

## Changes
* Adds `OFFICIALS` flag in the environment
* Require `Officials` flag in settings page, otherwise returns 404
* Checks if officials flag exists to render Settings in `ZUIOrganizeSideBar` component

## Notes to reviewer
Add/remove in `.env.local` file the flag `FEAT_OFFICIALS=* `

## Related issues
Resolves #2911

### CODE REVIEW

File: src/pages/organize/[orgId]/settings/index.tsx [hunk 1]
```diff
@@ -24,6 +25,7 @@ export const getServerSideProps: GetServerSideProps = scaffold(
   },
   {
     authLevelRequired: 2,
+    featuresRequired: [OFFICIALS],
```
Comment (richardolsson) [inline src/pages/organize/[orgId]/settings/index.tsx:28]: Let's remove this. You've done the right thing to add it, but we actually need this page to be accessible by those who know the URL. It just shouldn't be accessed accidentally.

Please verify that if we remove this change, the page can be accessed, just not listed in the menu.

**Review by richardolsson — CHANGES_REQUESTED** [review]
This looks good and the solution you've implemented is "correct", but we need it to work slightly differently. Details below. 👇
