### PR TITLE
issue-1892/remove-dummy-title

### LINKED ISSUE #1892: Calendar: Remove use of dummy title when creating multi-shift events
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When creating multi shift events we want the experience to be the same as when creating a single event. For the title that means: 
- If no title is added, show the title of the type as the title
- If the type is null, aka the "uncategorized" type, represent that in the title field as "Untitled multi-shift event"

## Steps to reproduce
1. Go to the weekly calendar
2. Drag to create and select to create a multi shift event
3. Select a type for the event

### Expected Behaviour
The contents of the title field changes to match the type

### Actual Behaviour
The contents of the title field stay the same

## Screenshots (if you have any)
bild

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR updates the title of multi-shift events when the event type changes. If there is no specified event type, it will display the default title.

## Screenshots
image

image

## Changes

* Adds `placeholder` and `InputLabelProps={{ shrink: true }}` in `TextField`

## Related issues
Resolves #1892

### CODE REVIEW

**Review by richardolsson — CHANGES_REQUESTED** [review]
I believe there is a misunderstanding here. IMO, the title field should always be "empty" unless the user has typed something into it. We should be displaying the "automatic" title (whether it's the "no title" one or the name of the current event type) as a placeholder.

Let's discuss when we get a chance!

File: src/features/calendar/components/EventShiftModal/index.tsx [hunk 1]
```diff
@@ -26,9 +26,7 @@ const EventShiftModal: FC<EventShiftModalProps> = ({ close, dates, open }) => {
   const { orgId, campId } = useNumericRouteParams();
 
   const [type, setType] = useState<ZetkinEvent['activity']>(null);
-  const [eventTitle, setEventTitle] = useState<string>(
-    messages.eventShiftModal.noTitle()
-  );
+  const [eventTitle, setEventTitle] = useState<string>('');
```
Comment (richardolsson) [inline src/features/calendar/components/EventShiftModal/index.tsx:29]: This is empty string, which means that an empty string is being sent to the server when this event is created. I think it would be better if the data being sent to the server was `null`, or that the `title` field wasn't included at all in the payload being sent to the server. You could keep the empty string default here, and then elsewhere (where the payload is being assembled for the server) if the string is empty, replace it with `null`.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Almost there! Let me know if you have questions about my comment below.

File: src/features/calendar/components/EventShiftModal/index.tsx (hunk 1 above)
Comment (kaulfield23) [reply src/features/calendar/components/EventShiftModal/index.tsx:29]: Yes sounds better with `null` ! will fix it right away!

Comment (kaulfield23) [reply src/features/calendar/components/EventShiftModal/index.tsx:29]: @richardolsson When I create a single event (by dragging on a calendar), it has an empty string ("") as the default value for the title. Should we also consider changing the default title value of single event to null?

Comment (richardolsson) [reply src/features/calendar/components/EventShiftModal/index.tsx:29]: Yeah, I think that's a good idea. Will you create a small entry-level issue for this?

Comment (kaulfield23) [reply src/features/calendar/components/EventShiftModal/index.tsx:29]: Yes! Will do :)
