### PR TITLE
Issue 1777/sort import as dropdown

### LINKED ISSUE #1777: Importer: items in the "Import as" dropdown are not in order
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When selecting what to import a field as, the items in the dropdown "Import as" is not sorted in any meaningful way. I would be easier to overview if it had some sorting logic.

## Steps to reproduce
1. Go to `/people` and select "import people" from the top right corner button
2. Select a file and load it
3. When you are in the Configure stage - open the "import as" dropdown

### Expected Behaviour
The items in the dropdown are sorted in a way that make them easy to overlook and pick from

### Actual Behaviour
The items are in no order at all

## Screenshots (if you have any)
bild

## Suggested solution
Group the items into: ID, fields (native + custom together) and "other" (tags, orgs). Sort alphabetically on the translated title within each group.

### PR DESCRIPTION
**Pull request by 262871**
## Description
This PR sorts and groups the items in the "import as..." drop-down from the import feature.

## Screenshots
zetkin ListSubheader dropdown

## Changes
* Adds group names in messageIds
* Updates changes from yarn make-yaml
* Updates useColumn() clients minimally for compatibility
* Changes useColumn() return type minimally
* Adds groups
* Sorts options by their translated label
* Adds ListSubheader to MappingRow's Select
* Adds paddingLeft: 4 to MenuItems

## Notes to reviewer
Go to /people and select "import people" from the top right corner button
Select a file and load it, e.g. this as a csv:
```
ID,forename,surname,phone
00000,Alice,Smith,0123456789
00001,Bob,Smith,0987654321
```
When you are in the Configure stage - open the "import as" dropdown

## Related issues
Resolves #1777

### CODE REVIEW

File: src/features/import/components/ImportDialog/Configure/Mapping/MappingRow.tsx [hunk 1]
```diff
@@ -21,7 +22,7 @@ import { Msg, useMessages } from 'core/i18n';
 interface MappingRowProps {
   clearConfiguration: () => void;
   column: UIDataColumn<Column>;
-  columnOptions: Option[];
+  columnOptions: Option[][];
```
Comment (richardolsson) [inline src/features/import/components/ImportDialog/Configure/Mapping/MappingRow.tsx:25]: I think we need to change this data structure a little bit, as expressed in another comment. Here are some suggestions:

* Split it up into three separate props of type `Option[]`, e.g. `idOptions`, `fieldOptions` and `otherOptions`
* Change the type of `columnOptions` to be an object with three pre-defined fields, i.e. `{ idOptions: Option[], fieldOptions: Option[], otherOptions: Option[] }`

But all of this makes me think about a wider topic, that I never considered part of the scope for this issue, but am now thinking is an opportunity to improve the code now that we've come across it.

Why are we passing in arrays of hard-coded values to this component, instead of just hard-coding them inside the component? I'm thinking now about the ID field option and the "Other" options. I think they could just be hard-coded inside this component.

For that reason, I think my main proposal is to rename `columnOptions` to `fieldOptions: Option[]` and pass in the fields from outside. For the ID and other options, hard-code them inside this component instead.

File: src/features/import/hooks/useColumn.ts [hunk 2]
```diff
@@ -56,37 +56,46 @@ export default function useColumn(orgId: number) {
     return !!exists;
   };
 
-  const columnOptions: Option[] = [];
+  const columnOptionsIDPartition: Option[] = [];
```
Comment (richardolsson) [inline src/features/import/hooks/useColumn.ts:59]: Move this hard-coded array into `MappingRow` (see previous comment for reasoning).

File: src/features/import/hooks/useColumn.ts [hunk 3]
```diff
@@ -56,37 +56,46 @@ export default function useColumn(orgId: number) {
...
+  const columnOptionsFieldsPartition: Option[] = [];
+  const columnOptionsOtherPartition: Option[] = [];
```
Comment (richardolsson) [inline src/features/import/hooks/useColumn.ts:61]: Move this hard-coded array into `MappingRow` (see previous comment for reasoning).

File: src/features/import/hooks/useColumn.ts [hunk 4]
```diff
@@ -56,37 +56,46 @@ export default function useColumn(orgId: number) {
...
 
-  columnOptions.push({
+  columnOptionsIDPartition.push({
```
Comment (richardolsson) [inline src/features/import/hooks/useColumn.ts:63]: Move this hard-coded array into `MappingRow` (see previous comment for reasoning).

File: src/features/import/hooks/useColumn.ts [hunk 5]
```diff
@@ -56,37 +56,46 @@ export default function useColumn(orgId: number) {
...
   customFields.forEach((field) =>
-    columnOptions.push({
+    columnOptionsFieldsPartition.push({
       label: field.title,
       value: `field:${field.slug}`,
     })
   );
 
-  columnOptions.push({
+  columnOptionsOtherPartition.push({
```
Comment (richardolsson) [inline src/features/import/hooks/useColumn.ts:84]: Move this hard-coded array into `MappingRow` (see previous comment for reasoning).

File: src/features/import/hooks/useColumn.ts [hunk 6]
```diff
@@ -56,37 +56,46 @@ export default function useColumn(orgId: number) {
...
     label: messages.configuration.mapping.tags(),
     value: 'tag',
   });
-  columnOptions.push({
+  columnOptionsOtherPartition.push({
```
Comment (richardolsson) [inline src/features/import/hooks/useColumn.ts:88]: Move this hard-coded array into `MappingRow` (see previous comment for reasoning).

File: src/features/import/hooks/useColumn.ts [hunk 7]
```diff
@@ -56,37 +56,46 @@ export default function useColumn(orgId: number) {
     return !!exists;
   };
 
-  const columnOptions: Option[] = [];
+  const columnOptionsIDPartition: Option[] = [];
+  const columnOptionsFieldsPartition: Option[] = [];
```
Comment (richardolsson) [inline src/features/import/hooks/useColumn.ts:60]: Keep this here.

File: src/features/import/hooks/useColumn.ts [hunk 8]
```diff
@@ -56,37 +56,46 @@ export default function useColumn(orgId: number) {
...
-  columnOptions.push({
+  columnOptionsIDPartition.push({
     label: messages.configuration.mapping.id(),
     value: 'id',
   });
 
   Object.values(NATIVE_PERSON_FIELDS).forEach((fieldSlug) => {
     if (fieldSlug != 'id' && fieldSlug != 'ext_id') {
-      columnOptions.push({
+      columnOptionsFieldsPartition.push({
```
Comment (richardolsson) [inline src/features/import/hooks/useColumn.ts:70]: Keep this here.

File: src/features/import/hooks/useColumn.ts [hunk 9]
```diff
@@ -56,37 +56,46 @@ export default function useColumn(orgId: number) {
...
         label: globalMessages.personFields[fieldSlug](),
         value: `field:${fieldSlug}`,
       });
     }
   });
 
   customFields.forEach((field) =>
-    columnOptions.push({
+    columnOptionsFieldsPartition.push({
```
Comment (richardolsson) [inline src/features/import/hooks/useColumn.ts:78]: Keep this here.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Awesome work @262871! I'm impressed by how quickly you were able to navigate the codebase and figure out a solution in a programming language you had very little experience with going in.

I think the solution is in many ways fine, but there is one thing that rubs me the wrong way, and that's the use of an array (or rather, a tuple) that is not properly typed as a tuple. It made me think about another way to distribute responsibilities within the code, and I ended up leaving a bunch of comments below that explain it.

How do you feel about changing the code the way I'm suggesting below?

**Comment by ajoensson** [comment]
Great work! I gave it a shot at implementing Richard's suggestions. PTAL @richardolsson !

**Review by richardolsson — APPROVED** [review]
Nice work on this, both of you! I believe it's ready to merge. 🎉
